# Generated by Django 5.2.17 on 2026-09-30 00:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical", "0012_labworktype_category_labworktype_unit"),
        ("core", "0015_place_look_and_hours"),
        ("stock", "0005_stockcategory_lab_blocks_alter_stockcategory_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabPriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "lab price list",
                "verbose_name_plural": "lab price lists",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LabSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_text",
                    models.TextField(
                        blank=True,
                        default="أهلاً د. {doctor}، استلمنا شغل المريض {patient} ({work}) في {lab}.\nرقم الحالة: {number}. الميعاد المتوقع: {due}.\nللمتابعة ابعت رقم الحالة على الرقم ده في أي وقت.",
                        verbose_name="message when a case is received",
                    ),
                ),
                (
                    "ready_text",
                    models.TextField(
                        blank=True,
                        default="أهلاً د. {doctor}، شغل المريض {patient} ({work}) جاهز في {lab}. رقم الحالة: {number}.",
                        verbose_name="message when a case is ready",
                    ),
                ),
                (
                    "delivered_text",
                    models.TextField(
                        blank=True,
                        default="أهلاً د. {doctor}، شغل المريض {patient} ({work}) خرج من {lab} في الطريق إليك. رقم الحالة: {number}.",
                        verbose_name="message when a case is sent back",
                    ),
                ),
                (
                    "auto_reply",
                    models.BooleanField(
                        default=False,
                        help_text="Needs the WhatsApp Business platform of Meta and the server reachable from the internet. A doctor who sends a case number gets its real status at once.",
                        verbose_name="answer the follow-ups by itself",
                    ),
                ),
                (
                    "wa_phone_number_id",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="WhatsApp phone number ID",
                    ),
                ),
                (
                    "wa_token",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="WhatsApp access token"
                    ),
                ),
                (
                    "wa_verify_token",
                    models.CharField(
                        blank=True,
                        help_text="Any word you choose, written the same in Meta's page.",
                        max_length=100,
                        verbose_name="webhook verify token",
                    ),
                ),
                (
                    "wa_app_secret",
                    models.CharField(
                        blank=True,
                        help_text="Checks that each message really comes from WhatsApp.",
                        max_length=100,
                        verbose_name="app secret",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab options",
                "verbose_name_plural": "lab options",
            },
        ),
        migrations.CreateModel(
            name="LabBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Written on the block. Empty = given by itself (B-0001...).",
                        max_length=30,
                        verbose_name="block number",
                    ),
                ),
                (
                    "lot",
                    models.CharField(blank=True, max_length=60, verbose_name="lot"),
                ),
                (
                    "shade",
                    models.CharField(blank=True, max_length=20, verbose_name="shade"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_use", "In use"),
                            ("finished", "Finished"),
                            ("broken", "Broken / thrown"),
                        ],
                        db_index=True,
                        default="in_use",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="opened at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finished at"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="cost of the block",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_blocks",
                        to="stock.stockitem",
                        verbose_name="block / disc",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="opened by",
                    ),
                ),
            ],
            options={
                "verbose_name": "block / disc",
                "verbose_name_plural": "blocks and discs",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="LabCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="case number",
                    ),
                ),
                (
                    "remake_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fit", "Does not fit / open margin"),
                            ("contacts", "Contacts (tight / open)"),
                            ("occlusion", "Occlusion (high / low)"),
                            ("shade", "Shade"),
                            ("shape", "Shape / aesthetics"),
                            ("fracture", "Fracture / chipping"),
                            ("design", "Design"),
                            ("impression", "Impression or scan problem"),
                            ("patient", "The patient's request"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                        verbose_name="why the remake",
                    ),
                ),
                (
                    "remake_fault",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lab", "The lab"),
                            ("clinic", "The clinic / the doctor"),
                            ("patient", "The patient"),
                            ("unknown", "Not known yet"),
                        ],
                        max_length=8,
                        verbose_name="whose fault",
                    ),
                ),
                (
                    "doctor",
                    models.CharField(blank=True, max_length=120, verbose_name="doctor"),
                ),
                (
                    "doctor_phone",
                    models.CharField(
                        blank=True,
                        help_text="The WhatsApp messages of this case go here (else to the client).",
                        max_length=20,
                        verbose_name="doctor's mobile",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="patient"
                    ),
                ),
                (
                    "impression",
                    models.CharField(
                        choices=[
                            ("digital", "Digital (intraoral scan)"),
                            ("conventional", "Conventional impression"),
                            ("models", "Models (poured)"),
                        ],
                        default="digital",
                        max_length=12,
                        verbose_name="impression",
                    ),
                ),
                (
                    "enclosures",
                    models.JSONField(
                        blank=True, default=list, verbose_name="came with the work"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("final", "Final work"),
                            ("framework", "Framework try-in"),
                            ("bisque", "Bisque try-in"),
                            ("wax", "Wax try-in / wax-up"),
                            ("temporary", "Temporary (PMMA)"),
                            ("repair", "Repair / remake"),
                        ],
                        default="final",
                        max_length=12,
                        verbose_name="send for",
                    ),
                ),
                (
                    "shade",
                    models.CharField(blank=True, max_length=80, verbose_name="shade"),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="instructions"),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="received at"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="promised for"
                    ),
                ),
                ("urgent", models.BooleanField(default=False, verbose_name="urgent")),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("incoming", "On the way to the lab"),
                            ("received", "Received: waiting to start"),
                            ("models", "Models and scanning"),
                            ("design", "CAD design"),
                            ("design_check", "Design check"),
                            ("milling", "Milling"),
                            ("printing", "3D printing"),
                            ("metal_printing", "Metal printing (laser)"),
                            ("casting", "Wax-up and casting"),
                            ("sintering", "Sintering / crystallization"),
                            ("ceramic", "Ceramic build-up"),
                            ("stain_glaze", "Stain and glaze"),
                            ("setup", "Teeth set-up"),
                            ("processing", "Processing (acrylic)"),
                            ("finishing", "Finishing and polishing"),
                            ("qc", "Quality check"),
                            ("ready", "Ready to deliver"),
                            ("delivered", "Delivered to the clinic"),
                            ("try_in", "At the clinic for a try-in"),
                            ("outsourced", "At another lab"),
                            ("on_hold", "On hold: waiting for the doctor"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=15,
                        verbose_name="step",
                    ),
                ),
                (
                    "route",
                    models.JSONField(
                        blank=True, default=list, verbose_name="steps of this case"
                    ),
                ),
                (
                    "step_since",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="in this step since",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered at"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="discount",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="price of the case",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="notes of the lab"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="delivered by",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="received by",
                    ),
                ),
                (
                    "remake_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remakes",
                        to="lab.labcase",
                        verbose_name="remake of",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_case",
                        to="clinical.labrequest",
                        verbose_name="lab request of our place",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab case",
                "verbose_name_plural": "lab cases",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="LabBlockUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "units",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="units made"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date"
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uses",
                        to="lab.labblock",
                        verbose_name="block",
                    ),
                ),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="by",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_uses",
                        to="lab.labcase",
                        verbose_name="case",
                    ),
                ),
            ],
            options={
                "verbose_name": "units made from a block",
                "verbose_name_plural": "units made from the blocks",
                "ordering": ["-used_at"],
            },
        ),
        migrations.CreateModel(
            name="LabCaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teeth",
                    models.CharField(blank=True, max_length=100, verbose_name="teeth"),
                ),
                (
                    "units",
                    models.PositiveSmallIntegerField(default=1, verbose_name="units"),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="material"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Empty = the client's price list.",
                        max_digits=10,
                        null=True,
                        verbose_name="unit price",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lab.labcase",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_items",
                        to="clinical.labworktype",
                        verbose_name="work",
                    ),
                ),
            ],
            options={
                "verbose_name": "work of a case",
                "verbose_name_plural": "work of a case",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="LabClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("place", "One of our places"),
                            ("clinic", "Outside clinic"),
                            ("doctor", "Outside doctor"),
                        ],
                        default="clinic",
                        max_length=10,
                        verbose_name="client",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="doctor / contact person",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="mobile"),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="Empty = the mobile. The case's messages and answers go here.",
                        max_length=20,
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "branch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_client",
                        to="core.branch",
                        verbose_name="our place",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients",
                        to="lab.labpricelist",
                        verbose_name="price list",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab client",
                "verbose_name_plural": "lab clients",
                "ordering": ["kind", "name"],
            },
        ),
        migrations.AddField(
            model_name="labcase",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cases",
                to="lab.labclient",
                verbose_name="client",
            ),
        ),
        migrations.CreateModel(
            name="LabFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("scan", "Scan / STL"),
                            ("photo", "Photo"),
                            ("design", "Design (screenshot)"),
                            ("other", "Other"),
                        ],
                        default="photo",
                        max_length=8,
                        verbose_name="kind",
                    ),
                ),
                ("file", models.FileField(upload_to="lab/%Y/%m/", verbose_name="file")),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="note"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="added at"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="lab.labcase",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "file of a case",
                "verbose_name_plural": "files of the cases",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LabMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("received", "Case received"),
                            ("ready", "Case ready"),
                            ("delivered", "Case sent back"),
                            ("status", "Answer: where the case is"),
                            ("auto", "Automatic answer"),
                            ("statement", "Account statement"),
                        ],
                        max_length=10,
                        verbose_name="message",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="to"),
                ),
                ("text", models.TextField(blank=True, verbose_name="text")),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="sent at"
                    ),
                ),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="by",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="lab.labcase",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="lab.labclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab WhatsApp message",
                "verbose_name_plural": "lab WhatsApp messages",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="LabOutsource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work",
                    models.CharField(max_length=150, verbose_name="what was sent"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="sent at"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="back by"),
                ),
                (
                    "back_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="came back at"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="cost",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outsourced",
                        to="lab.labcase",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outsourced_cases",
                        to="clinical.lab",
                        verbose_name="sent to the lab",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sent by",
                    ),
                ),
            ],
            options={
                "verbose_name": "work sent to another lab",
                "verbose_name_plural": "work sent to other labs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="LabPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="receipt number",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="amount"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Visa / card"),
                            ("instapay", "InstaPay"),
                            ("wallet", "Mobile wallet (Vodafone Cash...)"),
                            ("bank", "Bank transfer"),
                            ("bank_deposit", "Bank deposit"),
                            ("cheque", "Cheque"),
                            ("fawry", "Fawry POS machine"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="paid by",
                    ),
                ),
                (
                    "paid_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="date",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Transfer or cheque number.",
                        max_length=60,
                        verbose_name="reference",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="written at"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="why cancelled"
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cancelled by",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="lab.labclient",
                        verbose_name="client",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="received by",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab receipt",
                "verbose_name_plural": "lab receipts",
                "ordering": ["-paid_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="LabWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "jobs",
                    models.JSONField(blank=True, default=list, verbose_name="works on"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="mobile"),
                ),
                (
                    "fee_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For designers paid by the unit (e.g. CIA doctors): the lab report adds up what they are owed.",
                        max_digits=8,
                        null=True,
                        verbose_name="paid per unit designed",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="With a login they see their own work (My lab work) and are told when a case is given to them.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_worker",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="login",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab worker",
                "verbose_name_plural": "lab staff",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LabCaseStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("incoming", "On the way to the lab"),
                            ("received", "Received: waiting to start"),
                            ("models", "Models and scanning"),
                            ("design", "CAD design"),
                            ("design_check", "Design check"),
                            ("milling", "Milling"),
                            ("printing", "3D printing"),
                            ("metal_printing", "Metal printing (laser)"),
                            ("casting", "Wax-up and casting"),
                            ("sintering", "Sintering / crystallization"),
                            ("ceramic", "Ceramic build-up"),
                            ("stain_glaze", "Stain and glaze"),
                            ("setup", "Teeth set-up"),
                            ("processing", "Processing (acrylic)"),
                            ("finishing", "Finishing and polishing"),
                            ("qc", "Quality check"),
                            ("ready", "Ready to deliver"),
                            ("delivered", "Delivered to the clinic"),
                            ("try_in", "At the clinic for a try-in"),
                            ("outsourced", "At another lab"),
                            ("on_hold", "On hold: waiting for the doctor"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        max_length=15,
                        verbose_name="step",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="from"
                    ),
                ),
                (
                    "done_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="to"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=True,
                        help_text="False when the case was put on hold before this step was finished.",
                        verbose_name="finished",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="lab.labcase",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="moved on by",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="steps",
                        to="lab.labworker",
                        verbose_name="done by",
                    ),
                ),
            ],
            options={
                "verbose_name": "step of a case",
                "verbose_name_plural": "steps of the cases",
                "ordering": ["started_at", "pk"],
            },
        ),
        migrations.AddField(
            model_name="labcase",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_cases",
                to="lab.labworker",
                verbose_name="with",
            ),
        ),
        migrations.CreateModel(
            name="LabPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_prices",
                        to="clinical.labworktype",
                        verbose_name="work",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="lab.labpricelist",
                        verbose_name="price list",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab price",
                "verbose_name_plural": "lab prices",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("price_list", "work_type"), name="unique_lab_price"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="labcase",
            index=models.Index(
                fields=["client", "delivered_at"], name="lab_labcase_client__7d2329_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labcase",
            index=models.Index(
                fields=["received_at"], name="lab_labcase_receive_edfe1a_idx"
            ),
        ),
    ]
