# Generated by Django 5.2.17 on 2026-09-25 07:50

import apps.purchasing.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="name (English)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "kind",
                    models.CharField(
                        choices=[("dental", "Dental"), ("non_dental", "Non-dental")],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase category",
                "verbose_name_plural": "purchase categories",
                "ordering": ["kind", "sort_order", "name_ar"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="purchase date",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="supplier invoice no."
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Visa / card"),
                            ("instapay", "InstaPay"),
                            ("wallet", "Mobile wallet (Vodafone Cash...)"),
                            ("bank", "Bank transfer"),
                            ("cheque", "Cheque"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("partial", "Partly paid"),
                            ("credit", "On credit (not paid)"),
                        ],
                        default="paid",
                        max_length=20,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty when the full invoice is paid.",
                        max_digits=12,
                        null=True,
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "invoice_image",
                    models.FileField(
                        blank=True,
                        upload_to=apps.purchasing.models.invoice_path,
                        verbose_name="invoice photo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="core.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase",
                "verbose_name_plural": "purchases",
                "ordering": ["-purchase_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="item")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="piece, box, kg...",
                        max_length=30,
                        verbose_name="unit",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="unit price",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchasing.purchasecategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchasing.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase item",
                "verbose_name_plural": "purchase items",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="company / shop name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="phone"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contact person"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier",
                "verbose_name_plural": "suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="purchase",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="purchasing.supplier",
                verbose_name="supplier",
            ),
        ),
    ]
