# Generated by Django 5.2.17 on 2026-09-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Visa / card"),
                    ("instapay", "InstaPay"),
                    ("wallet", "Mobile wallet (Vodafone Cash...)"),
                    ("bank", "Bank transfer"),
                    ("bank_deposit", "Bank deposit"),
                    ("cheque", "Cheque"),
                ],
                default="cash",
                max_length=20,
                verbose_name="payment method",
            ),
        ),
    ]
