# Generated by Django 5.2.17 on 2026-09-25 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0002_alter_purchase_payment_method"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="stock_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_lines",
                to="stock.stockitem",
                verbose_name="add to stock item",
            ),
        ),
    ]
