# Generated by Django 5.2.17 on 2026-10-02 06:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0004_fawry_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "returned_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="date",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Damaged or broken"),
                            ("expired", "Expired or near expiry"),
                            ("wrong", "Wrong item or size"),
                            ("extra", "More than we need"),
                            ("quality", "Bad quality"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="why",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="details"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "1. Waiting for the supplier to take them"),
                            (
                                "taken",
                                "2. Taken by the supplier: waiting for the refund",
                            ),
                            ("done", "3. Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="step",
                    ),
                ),
                (
                    "taken_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="taken by the supplier on"
                    ),
                ),
                (
                    "taken_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="taken by (the supplier's person)",
                    ),
                ),
                (
                    "settlement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("money", "Money given back"),
                            (
                                "credit",
                                "Credit with the supplier (off the next invoice)",
                            ),
                            ("replaced", "New items instead (no money)"),
                        ],
                        max_length=20,
                        verbose_name="refund",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Money or credit. Empty = the value of the items given back.",
                        max_digits=12,
                        null=True,
                        verbose_name="amount given back",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Visa / card"),
                            ("instapay", "InstaPay"),
                            ("wallet", "Mobile wallet (Vodafone Cash...)"),
                            ("bank", "Bank transfer"),
                            ("bank_deposit", "Bank deposit"),
                            ("cheque", "Cheque"),
                            ("fawry", "Fawry POS machine"),
                        ],
                        max_length=20,
                        verbose_name="how the money came back",
                    ),
                ),
                (
                    "settled_on",
                    models.DateField(blank=True, null=True, verbose_name="refunded on"),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="why cancelled"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="purchasing.purchase",
                        verbose_name="purchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase return",
                "verbose_name_plural": "purchase returns",
                "ordering": ["-returned_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="quantity given back",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returned",
                        to="purchasing.purchaseitem",
                        verbose_name="item",
                    ),
                ),
                (
                    "purchase_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchasing.purchasereturn",
                    ),
                ),
            ],
            options={
                "verbose_name": "item given back",
                "verbose_name_plural": "items given back",
            },
        ),
    ]
