# Generated by Django 5.2.17 on 2026-10-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0005_purchase_returns"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchasecategory",
            options={
                "ordering": ["kind", "group", "sort_order", "name_ar"],
                "verbose_name": "purchase category",
                "verbose_name_plural": "purchase categories",
            },
        ),
        migrations.AddField(
            model_name="purchasecategory",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("implants", "Implants and surgery"),
                    ("materials", "Dental materials"),
                    ("instruments", "Instruments and equipment"),
                    ("consumables", "Consumables and infection control"),
                    ("medicines", "Medicines and anaesthesia"),
                    ("lab", "Lab materials"),
                    ("hospitality", "Kitchen and guests"),
                    ("office", "Office and printing"),
                    ("cleaning", "Cleaning"),
                    ("building", "Maintenance, bills and the building"),
                    ("other", "Other"),
                ],
                help_text="Dental groups: implants and surgery, materials, instruments, consumables, medicines, lab. The type follows the group.",
                max_length=20,
                verbose_name="group",
            ),
        ),
    ]
