from django.urls import path

from . import views

app_name = "lab"

urlpatterns = [
    path("", views.board, name="board"),
    path("cases/", views.case_list, name="case_list"),
    path("cases/new/", views.case_create, name="case_create"),
    path("incoming/", views.incoming, name="incoming"),
    path("mine/", views.my_work, name="my_work"),
    path("cases/<int:pk>/", views.case_detail, name="case_detail"),
    path("cases/<int:pk>/edit/", views.case_edit, name="case_edit"),
    path("cases/<int:pk>/move/", views.case_move, name="case_move"),
    path("cases/<int:pk>/assign/", views.case_assign, name="case_assign"),
    path("cases/<int:pk>/receive/", views.case_receive, name="case_receive"),
    path("cases/<int:pk>/remake/", views.case_remake, name="case_remake"),
    path("cases/<int:pk>/outsource/", views.case_outsource, name="case_outsource"),
    path("cases/<int:pk>/file/", views.case_file, name="case_file"),
    path("cases/<int:pk>/block/", views.case_block, name="case_block"),
    path("cases/<int:pk>/print/", views.case_print, name="case_print"),
    path("cases/<int:pk>/label/", views.case_label, name="case_label"),
    path("cases/<int:pk>/whatsapp/<slug:kind>/", views.case_whatsapp, name="case_whatsapp"),
    path("outsourced/<int:pk>/back/", views.outsource_back, name="outsource_back"),
    path("blocks/", views.blocks, name="blocks"),
    path("blocks/open/", views.block_open, name="block_open"),
    path("blocks/<int:pk>/", views.block_detail, name="block_detail"),
    path("blocks/<int:pk>/finish/", views.block_finish, name="block_finish"),
    path("stock/move/", views.stock_move, name="stock_move"),
    path("clients/", views.client_list, name="clients"),
    path("clients/new/", views.client_edit, name="client_create"),
    path("clients/<int:pk>/", views.client_detail, name="client_detail"),
    path("clients/<int:pk>/edit/", views.client_edit, name="client_edit"),
    path("clients/<int:pk>/statement/", views.client_statement, name="client_statement"),
    path("prices/", views.prices, name="prices"),
    path("receipts/", views.payment_list, name="payments"),
    path("receipts/new/", views.payment_create, name="payment_create"),
    path("receipts/<int:pk>/", views.payment_detail, name="payment_detail"),
    path("receipts/<int:pk>/cancel/", views.payment_cancel, name="payment_cancel"),
    path("report/", views.report, name="report"),
    path("whatsapp/", views.whatsapp_page, name="whatsapp"),
    path("whatsapp/answer/<int:pk>/", views.whatsapp_answer, name="whatsapp_answer"),
    path("whatsapp/hook/", views.whatsapp_hook, name="whatsapp_hook"),
    path("staff/", views.staff, name="staff"),
    path("staff/new/", views.worker_edit, name="worker_create"),
    path("staff/<int:pk>/", views.worker_edit, name="worker_edit"),
    path("settings/", views.lab_settings, name="settings"),
    path("request-form/", views.universal_form, name="universal_form"),
]
