# Generated by Django 5.2.17 on 2026-09-29 08:06

import apps.specialties.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical", "0011_detailed_lab_prescription"),
        ("core", "0015_place_look_and_hours"),
        ("dentists", "0006_specialty_and_title"),
        ("patients", "0009_patient_brought_by"),
        ("scheduling", "0016_whatsapp_requests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EndoCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("tooth", models.PositiveSmallIntegerField(verbose_name="tooth")),
                (
                    "started_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="first visit",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "In treatment"),
                            ("obturated", "Obturated (finished)"),
                            ("stopped", "Stopped"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(blank=True, verbose_name="chief complaint"),
                ),
                (
                    "pain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "No pain"),
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        max_length=10,
                        verbose_name="pain now",
                    ),
                ),
                (
                    "pain_kinds",
                    models.JSONField(blank=True, default=list, verbose_name="the pain"),
                ),
                (
                    "cold_test",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal response"),
                            ("none", "No response"),
                            ("lingering", "Lingering response"),
                            ("exaggerated", "Exaggerated, short"),
                            ("not_done", "Not done"),
                        ],
                        max_length=12,
                        verbose_name="cold test",
                    ),
                ),
                (
                    "heat_test",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal response"),
                            ("none", "No response"),
                            ("lingering", "Lingering response"),
                            ("exaggerated", "Exaggerated, short"),
                            ("not_done", "Not done"),
                        ],
                        max_length=12,
                        verbose_name="heat test",
                    ),
                ),
                (
                    "ept",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="electric pulp test (reading)",
                    ),
                ),
                (
                    "percussion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Not tender"),
                            ("tender", "Tender"),
                            ("very", "Very tender"),
                        ],
                        max_length=8,
                        verbose_name="percussion",
                    ),
                ),
                (
                    "palpation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Not tender"),
                            ("tender", "Tender"),
                            ("very", "Very tender"),
                        ],
                        max_length=8,
                        verbose_name="palpation",
                    ),
                ),
                (
                    "mobility",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(0, "0"), (1, "I"), (2, "II"), (3, "III")],
                        null=True,
                        verbose_name="mobility (grade)",
                    ),
                ),
                (
                    "probing",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="deepest probing (mm)"
                    ),
                ),
                (
                    "swelling",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("local", "Localised"),
                            ("diffuse", "Diffuse (cellulitis)"),
                        ],
                        max_length=8,
                        verbose_name="swelling",
                    ),
                ),
                (
                    "sinus_tract",
                    models.BooleanField(default=False, verbose_name="sinus tract"),
                ),
                (
                    "radiographic",
                    models.TextField(
                        blank=True,
                        help_text="e.g. PDL widening, periapical radiolucency 4 × 5 mm, calcified canal.",
                        verbose_name="X-ray / CBCT findings",
                    ),
                ),
                (
                    "pulpal_diagnosis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal pulp"),
                            ("reversible", "Reversible pulpitis"),
                            ("sym_irreversible", "Symptomatic irreversible pulpitis"),
                            ("asym_irreversible", "Asymptomatic irreversible pulpitis"),
                            ("necrosis", "Pulp necrosis"),
                            ("treated", "Previously treated"),
                            ("initiated", "Previously initiated therapy"),
                        ],
                        max_length=20,
                        verbose_name="pulpal diagnosis",
                    ),
                ),
                (
                    "apical_diagnosis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal apical tissues"),
                            ("symptomatic", "Symptomatic apical periodontitis"),
                            ("asymptomatic", "Asymptomatic apical periodontitis"),
                            ("chronic_abscess", "Chronic apical abscess"),
                            ("acute_abscess", "Acute apical abscess"),
                            ("condensing", "Condensing osteitis"),
                        ],
                        max_length=20,
                        verbose_name="apical diagnosis",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minimal", "Minimal difficulty"),
                            ("moderate", "Moderate difficulty"),
                            ("high", "High difficulty"),
                        ],
                        max_length=10,
                        verbose_name="case difficulty (AAE)",
                    ),
                ),
                (
                    "difficulty_factors",
                    models.JSONField(
                        blank=True, default=list, verbose_name="what makes it difficult"
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        choices=[
                            ("pulpotomy", "Pulpotomy (vital pulp therapy)"),
                            ("initial", "Initial root canal treatment"),
                            ("retreatment", "Non-surgical retreatment"),
                            ("apexification", "Apexification (MTA plug)"),
                            ("regenerative", "Regenerative endodontics"),
                            ("apicoectomy", "Apical surgery (apicoectomy)"),
                            ("other", "Other"),
                        ],
                        default="initial",
                        max_length=15,
                        verbose_name="treatment",
                    ),
                ),
                (
                    "anaesthesia",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Articaine 4% IANB + buccal infiltration",
                        max_length=120,
                        verbose_name="anaesthesia",
                    ),
                ),
                (
                    "rubber_dam",
                    models.BooleanField(default=True, verbose_name="rubber dam"),
                ),
                (
                    "magnification",
                    models.CharField(
                        blank=True,
                        help_text="e.g. microscope, loupes 3.5×",
                        max_length=60,
                        verbose_name="magnification",
                    ),
                ),
                (
                    "instruments",
                    models.CharField(
                        blank=True,
                        help_text="e.g. ProTaper Gold to F2, WaveOne Gold Primary, K-files",
                        max_length=120,
                        verbose_name="files / system",
                    ),
                ),
                (
                    "irrigants",
                    models.JSONField(
                        blank=True, default=list, verbose_name="irrigation"
                    ),
                ),
                (
                    "activation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "Needle only"),
                            ("sonic", "Sonic (EndoActivator)"),
                            ("ultrasonic", "Ultrasonic (PUI)"),
                            ("xp", "XP-endo Finisher"),
                            ("laser", "Laser"),
                        ],
                        max_length=12,
                        verbose_name="irrigant activation",
                    ),
                ),
                (
                    "obturation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lateral", "Cold lateral condensation"),
                            ("warm_vertical", "Warm vertical condensation"),
                            ("continuous_wave", "Continuous wave"),
                            ("single_cone", "Single cone with bioceramic sealer"),
                            ("carrier", "Carrier-based (Thermafil / GuttaCore)"),
                            ("mta", "MTA / bioceramic plug"),
                        ],
                        max_length=20,
                        verbose_name="obturation",
                    ),
                ),
                (
                    "sealer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ah_plus", "AH Plus (epoxy resin)"),
                            ("bioceramic", "Bioceramic (BC Sealer / TotalFill)"),
                            ("adseal", "Adseal"),
                            ("zoe", "Zinc oxide eugenol"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                        verbose_name="sealer",
                    ),
                ),
                (
                    "obturated_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="obturated on"
                    ),
                ),
                (
                    "restoration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("crown", "Full crown"),
                            ("onlay", "Onlay / overlay"),
                            ("post_crown", "Fibre post, core and crown"),
                            ("composite", "Direct composite"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                        verbose_name="final restoration advised",
                    ),
                ),
                (
                    "prognosis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("favourable", "Favourable"),
                            ("questionable", "Questionable"),
                            ("unfavourable", "Unfavourable"),
                        ],
                        max_length=15,
                        verbose_name="prognosis",
                    ),
                ),
                (
                    "recall",
                    models.CharField(
                        blank=True,
                        help_text="e.g. X-ray after 6 and 12 months",
                        max_length=100,
                        verbose_name="recall",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="dentists.dentist",
                        verbose_name="doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "treatment_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="clinical.treatmentstep",
                        verbose_name="in the treatment log",
                    ),
                ),
            ],
            options={
                "verbose_name": "endodontic case",
                "verbose_name_plural": "endodontic cases",
                "ordering": ["-started_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="EndoCanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12, verbose_name="canal")),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="e.g. MB cusp",
                        max_length=40,
                        verbose_name="reference point",
                    ),
                ),
                (
                    "working_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(40),
                        ],
                        verbose_name="working length (mm)",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apex_locator", "Apex locator"),
                            ("xray", "X-ray"),
                            ("both", "Apex locator + X-ray"),
                        ],
                        max_length=12,
                        verbose_name="measured by",
                    ),
                ),
                (
                    "master_file",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 25/.06",
                        max_length=20,
                        verbose_name="master apical file",
                    ),
                ),
                (
                    "master_cone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="master cone"
                    ),
                ),
                (
                    "curvature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("straight", "Straight"),
                            ("mild", "Mild (< 10°)"),
                            ("moderate", "Moderate (10–25°)"),
                            ("severe", "Severe (> 25°)"),
                        ],
                        max_length=10,
                        verbose_name="curvature",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=150, verbose_name="notes"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canals",
                        to="specialties.endocase",
                    ),
                ),
            ],
            options={
                "verbose_name": "canal",
                "verbose_name_plural": "canals",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="EndoVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                (
                    "work",
                    models.JSONField(
                        blank=True, default=list, verbose_name="done at this visit"
                    ),
                ),
                (
                    "medication",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("caoh", "Calcium hydroxide"),
                            ("ledermix", "Ledermix"),
                            ("tap", "Triple antibiotic paste"),
                            ("chx", "Chlorhexidine gel"),
                            ("cresophene", "Cresophene / formocresol pellet"),
                        ],
                        max_length=12,
                        verbose_name="intracanal medication",
                    ),
                ),
                (
                    "temporary",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cavit", "Cavit"),
                            ("gic", "Glass ionomer"),
                            ("irm", "IRM"),
                            ("composite", "Composite"),
                            ("none", "None"),
                        ],
                        max_length=10,
                        verbose_name="temporary filling",
                    ),
                ),
                (
                    "pain",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="pain before (0–10)",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="specialties.endocase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "endodontic visit",
                "verbose_name_plural": "endodontic visits",
                "ordering": ["date", "pk"],
            },
        ),
        migrations.CreateModel(
            name="OrthoCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("records", "Records and planning"),
                            ("active", "In treatment"),
                            ("retention", "Retention"),
                            ("finished", "Finished"),
                            ("stopped", "Stopped"),
                        ],
                        db_index=True,
                        default="records",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "records_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="records taken on",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(blank=True, verbose_name="chief complaint"),
                ),
                (
                    "profile",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("straight", "Straight"),
                            ("convex", "Convex"),
                            ("concave", "Concave"),
                        ],
                        max_length=10,
                        verbose_name="profile",
                    ),
                ),
                (
                    "symmetric",
                    models.BooleanField(default=True, verbose_name="face symmetric"),
                ),
                (
                    "lips",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("competent", "Competent"),
                            ("incompetent", "Incompetent"),
                        ],
                        max_length=12,
                        verbose_name="lips",
                    ),
                ),
                (
                    "smile_line",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("average", "Average"),
                            ("high", "High (gummy smile)"),
                        ],
                        max_length=8,
                        verbose_name="smile line",
                    ),
                ),
                (
                    "molar_right",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Class I"),
                            ("II_half", "Class II (½ unit)"),
                            ("II", "Class II (full unit)"),
                            ("III_half", "Class III (½ unit)"),
                            ("III", "Class III (full unit)"),
                        ],
                        max_length=10,
                        verbose_name="molars right",
                    ),
                ),
                (
                    "molar_left",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Class I"),
                            ("II_half", "Class II (½ unit)"),
                            ("II", "Class II (full unit)"),
                            ("III_half", "Class III (½ unit)"),
                            ("III", "Class III (full unit)"),
                        ],
                        max_length=10,
                        verbose_name="molars left",
                    ),
                ),
                (
                    "canine_right",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Class I"),
                            ("II_half", "Class II (½ unit)"),
                            ("II", "Class II (full unit)"),
                            ("III_half", "Class III (½ unit)"),
                            ("III", "Class III (full unit)"),
                        ],
                        max_length=10,
                        verbose_name="canines right",
                    ),
                ),
                (
                    "canine_left",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Class I"),
                            ("II_half", "Class II (½ unit)"),
                            ("II", "Class II (full unit)"),
                            ("III_half", "Class III (½ unit)"),
                            ("III", "Class III (full unit)"),
                        ],
                        max_length=10,
                        verbose_name="canines left",
                    ),
                ),
                (
                    "overjet",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="overjet (mm)",
                    ),
                ),
                (
                    "overbite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Below 0 = open bite.",
                        max_digits=4,
                        null=True,
                        verbose_name="overbite (mm)",
                    ),
                ),
                (
                    "crossbite",
                    models.CharField(
                        blank=True,
                        help_text="Which teeth, e.g. 12, 22",
                        max_length=100,
                        verbose_name="crossbite",
                    ),
                ),
                (
                    "midline",
                    models.CharField(
                        blank=True,
                        help_text="e.g. upper centred, lower 2 mm to the left",
                        max_length=100,
                        verbose_name="midlines",
                    ),
                ),
                (
                    "crowding_upper",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Below 0 = spacing.",
                        max_digits=4,
                        null=True,
                        verbose_name="upper crowding (mm)",
                    ),
                ),
                (
                    "crowding_lower",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="lower crowding (mm)",
                    ),
                ),
                (
                    "habits",
                    models.CharField(
                        blank=True,
                        help_text="e.g. thumb sucking, tongue thrust, mouth breathing",
                        max_length=150,
                        verbose_name="habits",
                    ),
                ),
                (
                    "sna",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="SNA (°)",
                    ),
                ),
                (
                    "snb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="SNB (°)",
                    ),
                ),
                (
                    "anb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="ANB (°)",
                    ),
                ),
                (
                    "fma",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="FMA / SN-MP (°)",
                    ),
                ),
                (
                    "u1_sn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="U1-SN (°)",
                    ),
                ),
                (
                    "impa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="IMPA (°)",
                    ),
                ),
                (
                    "wits",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Wits (mm)",
                    ),
                ),
                (
                    "skeletal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Skeletal Class I"),
                            ("II", "Skeletal Class II"),
                            ("III", "Skeletal Class III"),
                        ],
                        max_length=5,
                        verbose_name="skeletal class",
                    ),
                ),
                (
                    "vertical",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal angle"),
                            ("high", "High angle (long face)"),
                            ("low", "Low angle (short face)"),
                        ],
                        max_length=8,
                        verbose_name="vertical pattern",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True, verbose_name="diagnosis and problem list"
                    ),
                ),
                (
                    "appliance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("metal", "Fixed: metal brackets"),
                            ("ceramic", "Fixed: ceramic brackets"),
                            ("self_ligating", "Fixed: self-ligating"),
                            ("lingual", "Fixed: lingual"),
                            ("aligners", "Clear aligners"),
                            ("removable", "Removable appliance"),
                            ("functional", "Functional appliance (e.g. Twin Block)"),
                            ("expander", "Expander (RPE)"),
                        ],
                        max_length=15,
                        verbose_name="appliance",
                    ),
                ),
                (
                    "prescription",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mbt", "MBT"),
                            ("roth", "Roth"),
                            ("damon", "Damon"),
                            ("other", "Other"),
                        ],
                        max_length=6,
                        verbose_name="bracket prescription",
                    ),
                ),
                (
                    "extraction",
                    models.CharField(
                        blank=True,
                        help_text="Empty = no extraction. e.g. 14, 24, 34, 44",
                        max_length=100,
                        verbose_name="extractions",
                    ),
                ),
                (
                    "anchorage",
                    models.JSONField(
                        blank=True, default=list, verbose_name="anchorage"
                    ),
                ),
                (
                    "months",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="expected months"
                    ),
                ),
                (
                    "retention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bonded", "Bonded (fixed) retainer"),
                            ("hawley", "Hawley retainer"),
                            ("essix", "Clear (Essix) retainer"),
                            ("combined", "Bonded + clear retainer"),
                        ],
                        max_length=10,
                        verbose_name="retention",
                    ),
                ),
                (
                    "bonded_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="bonded / first aligners on"
                    ),
                ),
                (
                    "debonded_on",
                    models.DateField(blank=True, null=True, verbose_name="debonded on"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="dentists.dentist",
                        verbose_name="doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "orthodontic case",
                "verbose_name_plural": "orthodontic cases",
                "ordering": ["-records_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="OrthoVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                (
                    "upper_wire",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="upper wire"
                    ),
                ),
                (
                    "lower_wire",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="lower wire"
                    ),
                ),
                (
                    "aligner",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="aligner number"
                    ),
                ),
                (
                    "elastics",
                    models.CharField(
                        blank=True,
                        help_text='e.g. Class II 3/16" 6 oz',
                        max_length=80,
                        verbose_name="elastics",
                    ),
                ),
                (
                    "done",
                    models.CharField(
                        blank=True,
                        help_text="e.g. rebond 25, power chain 13–23, IPR 0.2 mm, TAD placed",
                        max_length=200,
                        verbose_name="what was done",
                    ),
                ),
                (
                    "hygiene",
                    models.CharField(
                        blank=True,
                        choices=[("good", "Good"), ("fair", "Fair"), ("poor", "Poor")],
                        max_length=5,
                        verbose_name="oral hygiene",
                    ),
                ),
                (
                    "next_weeks",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="next visit in (weeks)"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="specialties.orthocase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "orthodontic visit",
                "verbose_name_plural": "orthodontic visits",
                "ordering": ["date", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="number",
                    ),
                ),
                (
                    "to_outside",
                    models.CharField(
                        blank=True,
                        help_text="The doctor or centre outside, e.g. a radiology centre.",
                        max_length=150,
                        verbose_name="or outside the clinic",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("general", "General dentist"),
                            ("prosthodontist", "Prosthodontist"),
                            ("endodontist", "Endodontist"),
                            ("oral_surgeon", "Oral surgeon"),
                            ("tmj", "TMJ specialist (oral surgeon)"),
                            ("orthodontist", "Orthodontist"),
                            ("periodontist", "Periodontist"),
                            ("pedodontist", "Paediatric dentist"),
                            ("implantologist", "Implantologist"),
                            ("cosmetic", "Cosmetic dentist"),
                        ],
                        max_length=20,
                        verbose_name="specialty",
                    ),
                ),
                (
                    "teeth",
                    models.CharField(blank=True, max_length=100, verbose_name="teeth"),
                ),
                ("reason", models.TextField(verbose_name="what to do, and why")),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("soon", "Soon (within a week)"),
                            ("urgent", "Urgent (pain / swelling)"),
                        ],
                        default="routine",
                        max_length=10,
                        verbose_name="urgency",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent: to book"),
                            ("booked", "Booked"),
                            ("done", "Seen: answer sent back"),
                            ("declined", "The patient did not want it"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "reply",
                    models.TextField(
                        blank=True,
                        help_text="What was found, what was done, and what the referring doctor should do next.",
                        verbose_name="the specialist's answer",
                    ),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="answered at"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="scheduling.appointment",
                        verbose_name="appointment",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "from_dentist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals_sent",
                        to="dentists.dentist",
                        verbose_name="referred by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "replied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="answered by",
                    ),
                ),
                (
                    "to_dentist",
                    models.ForeignKey(
                        blank=True,
                        help_text="One of our doctors. Empty when the patient goes outside the clinic.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals_received",
                        to="dentists.dentist",
                        verbose_name="to the doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral",
                "verbose_name_plural": "referrals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="orthocase",
            name="referral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="specialties.referral",
                verbose_name="for the referral",
            ),
        ),
        migrations.AddField(
            model_name="endocase",
            name="referral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="specialties.referral",
                verbose_name="for the referral",
            ),
        ),
        migrations.CreateModel(
            name="ShadeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "taken_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                ("teeth", models.CharField(max_length=100, verbose_name="teeth")),
                (
                    "prosthesis",
                    models.CharField(
                        blank=True,
                        help_text="e.g. zirconia crowns 11, 21 or e.max veneers 13–23",
                        max_length=120,
                        verbose_name="for",
                    ),
                ),
                (
                    "guide",
                    models.CharField(
                        choices=[
                            ("classical", "VITA classical"),
                            ("3d_master", "VITA 3D-Master"),
                        ],
                        default="classical",
                        max_length=10,
                        verbose_name="shade guide",
                    ),
                ),
                (
                    "shade",
                    models.CharField(
                        max_length=10, verbose_name="shade (middle third)"
                    ),
                ),
                (
                    "shade_cervical",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="cervical third"
                    ),
                ),
                (
                    "shade_incisal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="incisal third"
                    ),
                ),
                (
                    "stump",
                    models.CharField(
                        blank=True,
                        help_text="For all-ceramic crowns and veneers (IPS Natural Die ND1–ND9).",
                        max_length=5,
                        verbose_name="prepared tooth (stump) shade",
                    ),
                ),
                (
                    "translucency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low (opaque)"),
                            ("medium", "Medium"),
                            ("high", "High (translucent incisal)"),
                        ],
                        max_length=8,
                        verbose_name="translucency",
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("smooth", "Smooth, glossy"),
                            ("medium", "Some texture"),
                            ("textured", "Strong texture (perikymata)"),
                        ],
                        max_length=10,
                        verbose_name="surface",
                    ),
                ),
                (
                    "characters",
                    models.JSONField(
                        blank=True, default=list, verbose_name="characters to copy"
                    ),
                ),
                (
                    "light",
                    models.CharField(
                        choices=[
                            ("daylight", "Daylight (by the window)"),
                            ("lamp", "Shade lamp (5500 K)"),
                            ("polarized", "Cross-polarized photo"),
                            ("clinic", "Clinic light"),
                        ],
                        default="daylight",
                        max_length=10,
                        verbose_name="taken in",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.specialties.models.shade_photo_path,
                        verbose_name="photo with the shade tab",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="dentists.dentist",
                        verbose_name="doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="specialties.referral",
                        verbose_name="for the referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "shade taken",
                "verbose_name_plural": "shades taken",
                "ordering": ["-taken_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="TMJExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "exam_date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(blank=True, verbose_name="chief complaint"),
                ),
                (
                    "since",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="since when"
                    ),
                ),
                (
                    "pain_vas",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="pain now (0–10)",
                    ),
                ),
                (
                    "pain_sites",
                    models.JSONField(
                        blank=True, default=list, verbose_name="where it hurts"
                    ),
                ),
                (
                    "headache",
                    models.BooleanField(default=False, verbose_name="headaches"),
                ),
                (
                    "bruxism",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("awake", "Awake clenching"),
                            ("sleep", "Sleep grinding"),
                            ("both", "Awake and sleep"),
                        ],
                        max_length=8,
                        verbose_name="clenching / grinding",
                    ),
                ),
                (
                    "habits",
                    models.CharField(
                        blank=True,
                        help_text="e.g. gum chewing, nail biting",
                        max_length=150,
                        verbose_name="habits",
                    ),
                ),
                (
                    "opening",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="mouth opening without help (mm)",
                    ),
                ),
                (
                    "opening_max",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="maximum opening with help (mm)",
                    ),
                ),
                (
                    "opening_pain",
                    models.BooleanField(default=False, verbose_name="pain on opening"),
                ),
                (
                    "right_lateral",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="to the right (mm)"
                    ),
                ),
                (
                    "left_lateral",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="to the left (mm)"
                    ),
                ),
                (
                    "protrusion",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="forward (mm)"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("straight", "Straight"),
                            ("deviation_r", "Deviation to the right (comes back)"),
                            ("deviation_l", "Deviation to the left (comes back)"),
                            ("deflection_r", "Deflection to the right"),
                            ("deflection_l", "Deflection to the left"),
                        ],
                        max_length=15,
                        verbose_name="opening path",
                    ),
                ),
                (
                    "sound_right",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("opening", "Click on opening"),
                            ("closing", "Click on closing"),
                            ("reciprocal", "Reciprocal click"),
                            ("crepitus", "Crepitus"),
                        ],
                        max_length=12,
                        verbose_name="right joint sounds",
                    ),
                ),
                (
                    "sound_left",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("opening", "Click on opening"),
                            ("closing", "Click on closing"),
                            ("reciprocal", "Reciprocal click"),
                            ("crepitus", "Crepitus"),
                        ],
                        max_length=12,
                        verbose_name="left joint sounds",
                    ),
                ),
                (
                    "locking",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("closed_now", "Closed lock now"),
                            ("closed_past", "Closed lock in the past"),
                            ("intermittent", "Catches, then opens"),
                            ("open", "Open lock (cannot close)"),
                        ],
                        max_length=15,
                        verbose_name="locking",
                    ),
                ),
                (
                    "joint_tender_right",
                    models.BooleanField(
                        default=False, verbose_name="right joint tender"
                    ),
                ),
                (
                    "joint_tender_left",
                    models.BooleanField(
                        default=False, verbose_name="left joint tender"
                    ),
                ),
                (
                    "muscles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="tender muscles"
                    ),
                ),
                (
                    "occlusion",
                    models.CharField(
                        blank=True,
                        help_text="e.g. missing back teeth, Class II, deep bite, interferences",
                        max_length=200,
                        verbose_name="occlusion",
                    ),
                ),
                (
                    "imaging",
                    models.TextField(blank=True, verbose_name="panorama / CBCT / MRI"),
                ),
                (
                    "diagnoses",
                    models.JSONField(
                        blank=True, default=list, verbose_name="diagnosis (DC/TMD)"
                    ),
                ),
                (
                    "plan",
                    models.JSONField(
                        blank=True, default=list, verbose_name="treatment plan"
                    ),
                ),
                (
                    "splint",
                    models.CharField(
                        blank=True,
                        help_text="e.g. hard upper stabilization splint, worn at night",
                        max_length=120,
                        verbose_name="splint",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="dentists.dentist",
                        verbose_name="doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="specialties.referral",
                        verbose_name="for the referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "TMJ examination",
                "verbose_name_plural": "TMJ examinations",
                "ordering": ["-exam_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="TMJVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                (
                    "opening",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="mouth opening (mm)"
                    ),
                ),
                (
                    "pain_vas",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="pain (0–10)",
                    ),
                ),
                (
                    "done",
                    models.CharField(
                        blank=True,
                        help_text="e.g. splint delivered and adjusted, botox 25 U each masseter",
                        max_length=200,
                        verbose_name="what was done",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="specialties.tmjexam",
                    ),
                ),
            ],
            options={
                "verbose_name": "TMJ follow-up",
                "verbose_name_plural": "TMJ follow-ups",
                "ordering": ["date", "pk"],
            },
        ),
    ]
