# Generated by Django 5.2.17 on 2026-10-05 17:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_clinicsettings_one_device_per_login_and_more"),
        ("dentists", "0007_signatures"),
        ("patients", "0013_remove_patient_patient_one_id_per_place_and_more"),
        ("specialties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProsthoCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "examined_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("examined", "Examined and planned"),
                            ("in_work", "In work (preparation to try-in)"),
                            ("delivered", "Delivered"),
                            ("recall", "On recall"),
                        ],
                        default="examined",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True, verbose_name="chief complaint and wishes"
                    ),
                ),
                (
                    "upper",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Class I (bilateral free end)"),
                            ("II", "Class II (one free end)"),
                            ("III", "Class III (bounded, one side)"),
                            ("IV", "Class IV (anterior, across the midline)"),
                            ("edentulous", "Completely edentulous"),
                            ("none", "No missing teeth"),
                        ],
                        max_length=12,
                        verbose_name="upper jaw",
                    ),
                ),
                (
                    "lower",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Class I (bilateral free end)"),
                            ("II", "Class II (one free end)"),
                            ("III", "Class III (bounded, one side)"),
                            ("IV", "Class IV (anterior, across the midline)"),
                            ("edentulous", "Completely edentulous"),
                            ("none", "No missing teeth"),
                        ],
                        max_length=12,
                        verbose_name="lower jaw",
                    ),
                ),
                (
                    "missing_teeth",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="missing teeth"
                    ),
                ),
                (
                    "ridge",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good height and width"),
                            ("resorbed", "Resorbed"),
                            ("knife", "Knife edge"),
                            ("flabby", "Flabby ridge"),
                        ],
                        max_length=10,
                        verbose_name="the ridge",
                    ),
                ),
                (
                    "abutment_teeth",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="abutment teeth"
                    ),
                ),
                (
                    "abutment_findings",
                    models.JSONField(
                        blank=True, default=list, verbose_name="abutment findings"
                    ),
                ),
                (
                    "vertical_dimension",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal"),
                            ("reduced", "Reduced (collapsed bite)"),
                            ("increased", "Increased"),
                        ],
                        max_length=10,
                        verbose_name="vertical dimension",
                    ),
                ),
                (
                    "interocclusal_space",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="space for the prosthesis (mm)",
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("canine", "Canine guidance"),
                            ("group", "Group function"),
                            ("balanced", "Bilateral balanced (dentures)"),
                            ("mutually", "Mutually protected"),
                        ],
                        max_length=10,
                        verbose_name="occlusal scheme",
                    ),
                ),
                (
                    "parafunction",
                    models.JSONField(
                        blank=True, default=list, verbose_name="parafunction"
                    ),
                ),
                (
                    "smile_line",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low (teeth only)"),
                            ("medium", "Medium (papillae show)"),
                            ("high", "High (gummy smile)"),
                        ],
                        max_length=8,
                        verbose_name="smile line",
                    ),
                ),
                (
                    "lip_support",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="lip support"
                    ),
                ),
                (
                    "midline",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="midline"
                    ),
                ),
                (
                    "old_prosthesis",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="the old prosthesis"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True, verbose_name="prosthodontic diagnosis"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("crowns", "Single crowns"),
                            ("bridge", "Bridge on teeth"),
                            ("implant_crowns", "Crowns / bridge on implants"),
                            ("full_arch", "Full arch fixed on implants"),
                            ("overdenture", "Overdenture on implants"),
                            ("complete_denture", "Complete denture"),
                            ("partial_denture", "Removable partial denture"),
                            ("veneers", "Veneers"),
                            ("inlays", "Inlays / onlays"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="the prosthesis planned",
                    ),
                ),
                (
                    "plan_teeth",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="on the teeth"
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("zirconia", "Zirconia"),
                            ("emax", "E.max (lithium disilicate)"),
                            ("pfm", "Porcelain fused to metal"),
                            ("pmma", "PMMA (temporary)"),
                            ("acrylic", "Acrylic"),
                            ("cocr", "Cobalt-chrome framework"),
                            ("peek", "PEEK / BioHPP"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="material",
                    ),
                ),
                (
                    "retention",
                    models.CharField(
                        blank=True,
                        help_text="e.g. cemented, screw-retained, locators, bar",
                        max_length=40,
                        verbose_name="retention",
                    ),
                ),
                (
                    "other_options",
                    models.TextField(
                        blank=True, verbose_name="other options told to the patient"
                    ),
                ),
                (
                    "delivered_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="delivered on"
                    ),
                ),
                (
                    "next_recall",
                    models.DateField(blank=True, null=True, verbose_name="next recall"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="dentists.dentist",
                        verbose_name="doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="specialties.referral",
                        verbose_name="for the referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "prosthodontic case",
                "verbose_name_plural": "prosthodontic cases",
                "ordering": ["-examined_on", "-pk"],
            },
        ),
    ]
