# Generated by Django 5.2.17 on 2026-09-26 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("dentists", "0004_dentist_arabic_name"),
        ("patients", "0006_fill_dates_and_governorate_codes"),
        ("scheduling", "0009_late_not_seen_follow_up"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="teeth",
            field=models.CharField(blank=True, max_length=100, verbose_name="teeth"),
        ),
        migrations.AlterField(
            model_name="patientpayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Visa / card"),
                    ("instapay", "InstaPay"),
                    ("wallet", "Mobile wallet (Vodafone Cash...)"),
                    ("bank", "Bank transfer"),
                    ("bank_deposit", "Bank deposit"),
                    ("cheque", "Cheque"),
                    ("fawry", "Fawry POS machine"),
                ],
                default="cash",
                max_length=20,
                verbose_name="payment method",
            ),
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="bill number",
                    ),
                ),
                (
                    "billed_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="date",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("reception", "Reception"),
                            ("dentist", "Dentist (after the treatment)"),
                        ],
                        default="reception",
                        max_length=10,
                        verbose_name="made by",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills",
                        to="scheduling.appointment",
                        verbose_name="visit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills",
                        to="dentists.dentist",
                        verbose_name="dentist",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "bill",
                "verbose_name_plural": "bills",
                "ordering": ["-billed_on", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="charge",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charges",
                to="billing.bill",
                verbose_name="bill",
            ),
        ),
        migrations.AddField(
            model_name="patientpayment",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="billing.bill",
                verbose_name="bill",
            ),
        ),
    ]
