# Generated by Django 5.2.17 on 2026-09-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_bills"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="quick_button",
            field=models.BooleanField(
                default=False,
                help_text="Shown as a one-click button on a new bill, e.g. first-visit examination and CBCT.",
                verbose_name="quick button on a new bill",
            ),
        ),
    ]
