# Generated by Django 5.2.17 on 2026-09-26 12:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_fawry_method"),
        ("billing", "0003_service_quick_button"),
        ("core", "0007_fawry"),
        ("purchasing", "0004_fawry_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FawryMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="number",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("collection", "Card payment taken on the machine"),
                            ("service", "Bill paid through the machine"),
                            ("top_up", "Money put on the machine"),
                            ("settlement", "Fawry transferred to the bank"),
                            ("charge", "Other Fawry charge (rent, fees)"),
                        ],
                        default="collection",
                        max_length=20,
                        verbose_name="move",
                    ),
                ),
                (
                    "moved_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="date",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What Fawry kept. Leave empty on a card payment to use the percentage in Settings.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Fawry fee",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile", "Mobile recharge / bill"),
                            ("electricity", "Electricity"),
                            ("water", "Water"),
                            ("gas", "Gas"),
                            ("internet", "Internet / landline"),
                            ("supplier", "Supplier (purchase)"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="bill paid",
                    ),
                ),
                (
                    "cash_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="When you paid someone else's bill (mobile, electricity...) and took cash from him.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="cash taken for it",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="transaction reference"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="details"
                    ),
                ),
                (
                    "academy_payment",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fawry_move",
                        to="academy.payment",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="The academy, the private clinic or CIC.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fawry_moves",
                        to="core.branch",
                        verbose_name="for",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "patient_payment",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fawry_move",
                        to="billing.patientpayment",
                    ),
                ),
                (
                    "purchase",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fawry_move",
                        to="purchasing.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fawry move",
                "verbose_name_plural": "Fawry moves",
                "ordering": ["-moved_on", "-pk"],
            },
        ),
    ]
