# Generated by Django 5.2.17 on 2026-09-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_fawry"),
        ("core", "0010_cic_name"),
        ("dentists", "0005_places"),
    ]

    operations = [
        migrations.CreateModel(
            name="FawryMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="name")),
                (
                    "terminal_id",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="terminal / serial number",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "Fawry machine",
                "verbose_name_plural": "Fawry machines",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="core.branch",
                verbose_name="place",
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charges",
                to="core.branch",
                verbose_name="place",
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="dentist",
            field=models.ForeignKey(
                blank=True,
                help_text="Counts for the doctor's share at clinics that pay a percentage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charges",
                to="dentists.dentist",
                verbose_name="dentist who did the work",
            ),
        ),
        migrations.AddField(
            model_name="patientpayment",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient_payments",
                to="core.branch",
                verbose_name="place",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Empty = offered at every place. For a price list of one place (e.g. CIC), choose it here.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="core.branch",
                verbose_name="only at",
            ),
        ),
        migrations.AddField(
            model_name="fawrymove",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moves",
                to="billing.fawrymachine",
                verbose_name="Fawry machine",
            ),
        ),
        migrations.AddField(
            model_name="patientpayment",
            name="fawry_machine",
            field=models.ForeignKey(
                blank=True,
                help_text="For card payments: the machine that took it.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient_payments",
                to="billing.fawrymachine",
                verbose_name="Fawry machine",
            ),
        ),
    ]
