# Generated by Django 5.2.17 on 2026-09-28 06:05

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_fill_places_and_machine"),
        ("core", "0011_backup_runs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientpayment",
            options={
                "base_manager_name": "every",
                "ordering": ["-paid_on", "-pk"],
                "verbose_name": "patient payment",
                "verbose_name_plural": "patient payments",
            },
        ),
        migrations.AlterModelManagers(
            name="patientpayment",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("every", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="patientpayment",
            name="cancel_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="why cancelled"
            ),
        ),
        migrations.AddField(
            model_name="patientpayment",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="cancelled at"
            ),
        ),
        migrations.AddField(
            model_name="patientpayment",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="cancelled by",
            ),
        ),
        migrations.AddField(
            model_name="patientpayment",
            name="refund_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="billing.patientpayment",
                verbose_name="refund of the receipt",
            ),
        ),
        migrations.AlterField(
            model_name="patientpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="A refund is written as a receipt with the amount given back.",
                max_digits=10,
                verbose_name="amount paid",
            ),
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("corrected", "Corrected"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=10,
                        verbose_name="what was done",
                    ),
                ),
                (
                    "before",
                    models.CharField(blank=True, max_length=255, verbose_name="before"),
                ),
                (
                    "after",
                    models.CharField(blank=True, max_length=255, verbose_name="after"),
                ),
                ("reason", models.CharField(max_length=255, verbose_name="why")),
                (
                    "done_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="when"
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="by",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="billing.patientpayment",
                        verbose_name="receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "receipt change",
                "verbose_name_plural": "receipt changes",
                "ordering": ["-done_at"],
            },
        ),
        migrations.CreateModel(
            name="DayClosing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="day")),
                (
                    "totals",
                    models.JSONField(
                        default=dict, verbose_name="totals by payment method"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total received",
                    ),
                ),
                (
                    "receipts",
                    models.PositiveIntegerField(default=0, verbose_name="receipts"),
                ),
                (
                    "cash_expected",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="cash that should be in the drawer",
                    ),
                ),
                (
                    "cash_counted",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="cash counted in the drawer",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="closed at"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "review_notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="review notes"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="day_closings",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="closed by",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "day closing",
                "verbose_name_plural": "day closings",
                "ordering": ["-day"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "day"), name="one_closing_a_day_per_place"
                    )
                ],
            },
        ),
    ]
