# Generated by Django 5.2.17 on 2026-09-29 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_receipts_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Taken off what the patient paid before the doctor's percentage, when his rule says so.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="lab / implant cost",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="e.g. the lab's price of a zirconia crown, or the implant's price. Taken off before a doctor's percentage when his rule says so; each bill line can be corrected.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="usual lab / implant cost (each tooth)",
            ),
        ),
    ]
