# Generated by Django 5.2.17 on 2026-10-01 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_lab_and_implant_costs"),
        ("core", "0018_speed_indexes"),
        ("dentists", "0006_specialty_and_title"),
        ("patients", "0010_medicalconsult"),
        ("scheduling", "0016_whatsapp_requests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["branch", "billed_on"], name="bill_place_date"),
        ),
        migrations.AddIndex(
            model_name="charge",
            index=models.Index(
                fields=["branch", "charged_on"], name="charge_place_date"
            ),
        ),
        migrations.AddIndex(
            model_name="patientpayment",
            index=models.Index(fields=["branch", "paid_on"], name="payment_place_date"),
        ),
    ]
