# Generated by Django 5.2.17 on 2026-10-05 17:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_fawry_moves_by"),
        ("core", "0022_clinicsettings_one_device_per_login_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerCash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "moved_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="date",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("in", "Put in by the owner"),
                            ("out", "Taken by the owner"),
                        ],
                        default="in",
                        max_length=3,
                        verbose_name="money",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Visa / card"),
                            ("instapay", "InstaPay"),
                            ("wallet", "Mobile wallet (Vodafone Cash...)"),
                            ("bank", "Bank transfer"),
                            ("bank_deposit", "Bank deposit"),
                            ("cheque", "Cheque"),
                            ("fawry", "Fawry POS machine"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="how",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="e.g. to pay the implant supplier, the salaries, the rent.",
                        max_length=255,
                        verbose_name="what for",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_cash",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "owner's money",
                "verbose_name_plural": "owner's money",
                "ordering": ["-moved_on", "-pk"],
            },
        ),
    ]
