# Generated by Django 5.2.17 on 2026-09-25 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purchasing", "0002_alter_purchase_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="name (English)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "stock category",
                "verbose_name_plural": "stock categories",
                "ordering": ["sort_order", "name_ar"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="item"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="piece, box, carpule, pack...",
                        max_length=30,
                        verbose_name="unit",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        verbose_name="in stock",
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="The stock manager is warned when the quantity falls to this number or below.",
                        max_digits=10,
                        verbose_name="reorder level",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="e.g. store, room 2, sterilisation",
                        max_length=100,
                        verbose_name="place",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="code / barcode"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="last unit price",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="in use")),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="stock.stockcategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock item",
                "verbose_name_plural": "stock items",
                "ordering": ["category__sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("in", "Received into stock"),
                            ("out", "Taken out / used"),
                            ("waste", "Damaged / expired"),
                            ("count", "Stock count (correct the quantity)"),
                        ],
                        max_length=10,
                        verbose_name="movement",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="For a stock count, write the quantity you counted.",
                        max_digits=10,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="change",
                    ),
                ),
                (
                    "moved_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="date",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        help_text="e.g. room 3, Dr. Mona, sterilisation, kitchen",
                        max_length=150,
                        verbose_name="for / taken by",
                    ),
                ),
                (
                    "lot",
                    models.CharField(blank=True, max_length=60, verbose_name="lot"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="expiry date"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="unit price",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="stock.stockitem",
                        verbose_name="item",
                    ),
                ),
                (
                    "purchase_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movement",
                        to="purchasing.purchaseitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock movement",
                "verbose_name_plural": "stock movements",
                "ordering": ["-moved_at", "-pk"],
            },
        ),
    ]
