# Generated by Django 5.2.17 on 2026-09-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
        ("surgery", "0002_operators"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="implant_diameter",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="implant diameter (mm)",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="implant_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="implant length (mm)",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="implant_system",
            field=models.ForeignKey(
                blank=True,
                help_text="For implants only: the surgery chart then takes them out of stock by lot.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="surgery.implantsystem",
                verbose_name="implant company / type",
            ),
        ),
    ]
