# Generated by Django 5.2.17 on 2026-09-27 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_cic_name"),
        ("stock", "0002_implants_from_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Empty = shared by all the places. Choose a place (e.g. CIC) for material bought for it only.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_items",
                to="core.branch",
                verbose_name="belongs to",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="The place that used it (or received it), so each place's use of the stock can be followed.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="core.branch",
                verbose_name="place",
            ),
        ),
    ]
