# Generated by Django 5.2.17 on 2026-09-28 06:51

from django.db import migrations, models


# The categories made by the first setup, put in their group.
GROUPS = {
    "Dental materials": "dental",
    "Instruments": "equipment",
    "Implants & components": "implants",
    "Anaesthesia & drugs": "medicines",
    "Consumables (gloves, masks, gauze...)": "infection",
    "Equipment": "equipment",
    "Food & beverage": "beverage",
    "Cleaning": "cleaning",
    "Stationery": "stationery",
}


def put_in_groups(apps, schema_editor):
    category = apps.get_model("stock", "StockCategory")
    for name_en, group in GROUPS.items():
        category.objects.filter(name_en=name_en, group="other").update(group=group)


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockcategory",
            name="group",
            field=models.CharField(
                choices=[
                    ("dental", "Dental materials"),
                    ("implants", "Implants & surgery"),
                    ("infection", "Infection control & disposables"),
                    ("medicines", "Anaesthesia & medicines"),
                    ("equipment", "Instruments & equipment"),
                    ("beverage", "Beverage & hospitality"),
                    ("cleaning", "Cleaning"),
                    ("stationery", "Stationery & printing"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
                verbose_name="group",
            ),
        ),
        migrations.RunPython(put_in_groups, migrations.RunPython.noop),
    ]
