# Generated by Django 5.2.17 on 2026-09-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_stock_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockcategory",
            name="lab_blocks",
            field=models.BooleanField(
                default=False,
                help_text="The lab opens each block (zirconia, e.max, PMMA...) and counts the units made from it.",
                verbose_name="blocks or discs followed one by one",
            ),
        ),
        migrations.AlterField(
            model_name="stockcategory",
            name="group",
            field=models.CharField(
                choices=[
                    ("dental", "Dental materials"),
                    ("implants", "Implants & surgery"),
                    ("infection", "Infection control & disposables"),
                    ("medicines", "Anaesthesia & medicines"),
                    ("equipment", "Instruments & equipment"),
                    ("beverage", "Beverage & hospitality"),
                    ("cleaning", "Cleaning"),
                    ("stationery", "Stationery & printing"),
                    ("lab", "Dental lab"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
                verbose_name="group",
            ),
        ),
    ]
