# Generated by Django 5.2.17 on 2026-09-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_stockcategory_lab_blocks_alter_stockcategory_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="implant_diameter",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="implant diameter (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="implant_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="implant length (mm)",
            ),
        ),
    ]
