# Generated by Django 5.2.17 on 2026-10-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_implant_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("in", "Received into stock"),
                    ("out", "Taken out / used"),
                    ("waste", "Damaged / expired"),
                    ("count", "Stock count (correct the quantity)"),
                    ("return", "Given back to the supplier"),
                ],
                max_length=10,
                verbose_name="movement",
            ),
        ),
    ]
