# Generated by Django 5.2.17 on 2026-09-25 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="complaint number",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting time / delay"),
                            ("treatment", "Treatment result"),
                            ("pain", "Pain / problem after treatment"),
                            ("staff", "Staff behaviour"),
                            ("doctor", "Doctor behaviour"),
                            ("billing", "Payment / prices"),
                            ("cleanliness", "Cleanliness"),
                            ("lab", "Lab work"),
                            ("appointment", "Appointments"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High - urgent"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="severity",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="complaint (in the patient's words)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "New"),
                            ("in_progress", "Being followed up"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "follow_up_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="next follow-up date"
                    ),
                ),
                (
                    "resolution",
                    models.TextField(blank=True, verbose_name="how it was solved"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolved at"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_complaints",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="followed up by",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints",
                        to="core.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "concerned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_about",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="concerned doctor / staff",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="resolved by",
                    ),
                ),
            ],
            options={
                "verbose_name": "complaint",
                "verbose_name_plural": "complaints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("called", "Called the patient"),
                            ("met", "Met the patient"),
                            ("staff", "Spoke to the doctor / staff"),
                            ("retreat", "Booked a correction visit"),
                            ("refund", "Refund / discount"),
                            ("note", "Note"),
                        ],
                        default="note",
                        max_length=20,
                        verbose_name="action taken",
                    ),
                ),
                ("note", models.TextField(verbose_name="details")),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("open", "New"),
                            ("in_progress", "Being followed up"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        max_length=20,
                        verbose_name="status after this step",
                    ),
                ),
                (
                    "next_follow_up",
                    models.DateField(
                        blank=True, null=True, verbose_name="next follow-up date"
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="complaints.complaint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "follow-up",
                "verbose_name_plural": "follow-ups",
                "ordering": ["created_at"],
            },
        ),
    ]
