# Generated by Django 5.2.17 on 2026-09-25 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
        ("dentists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="concerned_dentist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints_about",
                to="dentists.dentist",
                verbose_name="concerned dentist",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="concerned_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints_about",
                to=settings.AUTH_USER_MODEL,
                verbose_name="concerned staff member",
            ),
        ),
    ]
