# Generated by Django 5.2.17 on 2026-09-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_complaint_concerned_dentist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="answer_alert_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="no-answer alert sent at"
            ),
        ),
        migrations.AlterField(
            model_name="complaintfollowup",
            name="action",
            field=models.CharField(
                choices=[
                    ("called", "Called the patient"),
                    ("met", "Met the patient"),
                    ("staff", "Spoke to the doctor / staff"),
                    ("retreat", "Booked a correction visit"),
                    ("refund", "Refund / discount"),
                    ("dentist", "Dentist's answer and plan to solve it"),
                    ("note", "Note"),
                ],
                default="note",
                max_length=20,
                verbose_name="action taken",
            ),
        ),
    ]
