# Generated by Django 5.2.17 on 2026-09-26 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_dentist_answers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="current_situation",
            field=models.TextField(
                blank=True,
                help_text="Where the case stands now, in a few words.",
                verbose_name="current situation",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="situation_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="situation updated at"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="situation_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="situation updated by",
            ),
        ),
        migrations.AddField(
            model_name="complaintfollowup",
            name="edited_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="corrected at"
            ),
        ),
    ]
