# Generated by Django 5.2.17 on 2026-10-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_situation_and_corrections"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="calls",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Each time the patient calls again for the same reason (round 15).",
                verbose_name="times the patient called",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="last_call_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="last call"),
        ),
        migrations.AlterField(
            model_name="complaintfollowup",
            name="action",
            field=models.CharField(
                choices=[
                    ("called", "Called the patient"),
                    ("met", "Met the patient"),
                    ("staff", "Spoke to the doctor / staff"),
                    ("retreat", "Booked a correction visit"),
                    ("refund", "Refund / discount"),
                    ("dentist", "Dentist's answer and plan to solve it"),
                    ("called_again", "The patient called again (same reason)"),
                    ("note", "Note"),
                ],
                default="note",
                max_length=20,
                verbose_name="action taken",
            ),
        ),
    ]
