# Generated by Django 5.2.17 on 2026-09-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Automatic (Arabic for secretaries, English for dentists)"),
                    ("ar", "Arabic"),
                    ("en", "English"),
                ],
                max_length=5,
                verbose_name="interface language",
            ),
        ),
    ]
