# Generated by Django 5.2.17 on 2026-09-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "late_threshold_minutes",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="a patient is late after (minutes)"
                    ),
                ),
                (
                    "default_appointment_minutes",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="usual appointment length (minutes)"
                    ),
                ),
                (
                    "complaint_follow_up_days",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="follow up a complaint within (days)"
                    ),
                ),
                (
                    "stock_expiry_days",
                    models.PositiveSmallIntegerField(
                        default=60,
                        verbose_name="warn about stock expiring within (days)",
                    ),
                ),
                (
                    "reminder_days_before",
                    models.PositiveSmallIntegerField(
                        default=1,
                        verbose_name="send appointment reminders (days before)",
                    ),
                ),
                (
                    "whatsapp_country_code",
                    models.CharField(
                        default="20",
                        help_text="20 for Egypt. Mobiles written as 010... are sent as 2010...",
                        max_length=4,
                        verbose_name="country code for WhatsApp",
                    ),
                ),
            ],
            options={
                "verbose_name": "clinic options",
                "verbose_name_plural": "clinic options",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="access_days",
            field=models.CharField(
                blank=True,
                help_text="Empty = every day.",
                max_length=20,
                verbose_name="days allowed",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="access_end",
            field=models.TimeField(blank=True, null=True, verbose_name="to hour"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="access_from",
            field=models.DateField(
                blank=True, null=True, verbose_name="access starts on"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="access_start",
            field=models.TimeField(blank=True, null=True, verbose_name="from hour"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="access_until",
            field=models.DateField(
                blank=True,
                help_text="After this day the login stops working (e.g. end of a course or contract).",
                null=True,
                verbose_name="access ends on",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="read_only",
            field=models.BooleanField(
                default=False,
                help_text="Can open the pages of their role but cannot save or change anything.",
                verbose_name="read only",
            ),
        ),
        migrations.CreateModel(
            name="AreaAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=20, verbose_name="role")),
                (
                    "area",
                    models.CharField(max_length=30, verbose_name="part of the system"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("full", "Normal access"),
                            ("read", "Read only"),
                            ("hidden", "No access"),
                        ],
                        default="full",
                        max_length=10,
                        verbose_name="access",
                    ),
                ),
            ],
            options={
                "verbose_name": "access of a role",
                "verbose_name_plural": "access of the roles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "area"), name="unique_area_access"
                    )
                ],
            },
        ),
    ]
