# Generated by Django 5.2.17 on 2026-09-25 18:29

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_settings_and_access"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="day_end",
            field=models.TimeField(
                default=datetime.time(17, 0), verbose_name="appointments end at"
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="day_start",
            field=models.TimeField(
                default=datetime.time(9, 0), verbose_name="appointments start at"
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="dicom_email",
            field=models.EmailField(
                blank=True,
                default="ciapts@gmail.com",
                help_text="Printed on CBCT requests: the centre sends the DICOM files here.",
                max_length=254,
                verbose_name="e-mail for CBCT files",
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="surgery_days",
            field=models.CharField(
                blank=True,
                default="3,4",
                help_text="A new shift on these days is a surgery day unless you change it.",
                max_length=20,
                verbose_name="usual surgery days",
            ),
        ),
        migrations.AlterField(
            model_name="clinicsettings",
            name="default_appointment_minutes",
            field=models.PositiveSmallIntegerField(
                default=30, verbose_name="usual appointment length (minutes)"
            ),
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("patient", "Patient data"),
                            ("visit_times", "Visit times"),
                        ],
                        max_length=20,
                        verbose_name="change of",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200, verbose_name="record")),
                ("changes", models.JSONField(default=list, verbose_name="changes")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="why"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="asked at"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="decided at"
                    ),
                ),
                (
                    "decision_note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="decided by",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="asked by",
                    ),
                ),
            ],
            options={
                "verbose_name": "change waiting for approval",
                "verbose_name_plural": "changes waiting for approval",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_change_content_b08406_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonAreaAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.CharField(max_length=30, verbose_name="part of the system"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("full", "Normal access"),
                            ("read", "Read only"),
                            ("hidden", "No access"),
                        ],
                        max_length=10,
                        verbose_name="access",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "access of a person",
                "verbose_name_plural": "access of people",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "area"), name="unique_person_area_access"
                    )
                ],
            },
        ),
    ]
