# Generated by Django 5.2.17 on 2026-09-25 22:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_hours_access_and_approvals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reported", "Told by a user"),
                            ("automatic", "Page error (recorded automatically)"),
                        ],
                        default="reported",
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("seen", "Being looked at"),
                            ("solved", "Solved"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "page",
                    models.CharField(blank=True, max_length=500, verbose_name="page"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="what happened"),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        upload_to="problems/%Y/%m/",
                        verbose_name="screenshot or photo",
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, verbose_name="technical details"),
                ),
                (
                    "signature",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("times", models.PositiveIntegerField(default=1, verbose_name="times")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="last time"
                    ),
                ),
                (
                    "answer",
                    models.TextField(blank=True, verbose_name="answer / what was done"),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="handled by",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reported by",
                    ),
                ),
            ],
            options={
                "verbose_name": "problem report",
                "verbose_name_plural": "problem reports",
                "ordering": ["-last_seen_at"],
            },
        ),
    ]
