# Generated by Django 5.2.17 on 2026-09-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_problem_reports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changerequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("patient", "Patient data"),
                    ("visit_times", "Visit times"),
                    ("operator", "Operator of a treatment or surgery"),
                ],
                max_length=20,
                verbose_name="change of",
            ),
        ),
    ]
