# Generated by Django 5.2.17 on 2026-09-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_operators"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="fawry_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="What Fawry keeps from each payment taken on its machine, e.g. 1.5. Each move can still be corrected.",
                max_digits=5,
                verbose_name="Fawry percentage on card payments (%)",
            ),
        ),
    ]
