# Generated by Django 5.2.17 on 2026-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_fawry"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="show_hints",
            field=models.BooleanField(
                default=True,
                help_text="A short tip at the top of each page on what to do there.",
                verbose_name="show hints",
            ),
        ),
    ]
