# Generated by Django 5.2.17 on 2026-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_profile_show_hints"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="places",
            field=models.ManyToManyField(
                blank=True,
                help_text="The places this person works in. With more than one, a switch in the top bar chooses the place they work in now.",
                related_name="staff_places",
                to="core.branch",
                verbose_name="works at",
            ),
        ),
    ]
