# Generated by Django 5.2.17 on 2026-09-27 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_cic_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("database", "All the data (ZIP)"),
                            ("files", "Copy of the photos and files"),
                        ],
                        max_length=10,
                        verbose_name="backup of",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finished at"
                    ),
                ),
                (
                    "ok",
                    models.BooleanField(
                        default=False, verbose_name="done without errors"
                    ),
                ),
                (
                    "where",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="saved in"
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(default=0, verbose_name="size (bytes)"),
                ),
                (
                    "files_copied",
                    models.PositiveIntegerField(default=0, verbose_name="files copied"),
                ),
                (
                    "files_checked",
                    models.PositiveIntegerField(
                        default=0, verbose_name="files checked"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="error")),
            ],
            options={
                "verbose_name": "backup run",
                "verbose_name_plural": "backup runs",
                "ordering": ["-started_at"],
            },
        ),
    ]
