# Generated by Django 5.2.17 on 2026-09-28 06:31

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_backup_runs"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="reception_sees",
            field=models.JSONField(
                blank=True,
                default=apps.core.models.reception_default,
                verbose_name="the reception sees in a patient's file",
            ),
        ),
    ]
