# Generated by Django 5.2.17 on 2026-09-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_reception_sees"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="has_cbct",
            field=models.BooleanField(
                default=False,
                help_text="A CBCT asked by a dentist here can then be marked as done in the clinic.",
                verbose_name="has a CBCT machine",
            ),
        ),
    ]
