# Generated by Django 5.2.17 on 2026-09-28 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_cbct_done"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Set when the owner gives a temporary password: the person chooses their own at the next login.",
                verbose_name="must choose a new password",
            ),
        ),
        migrations.CreateModel(
            name="PasswordHelp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, verbose_name="username written"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="note"),
                ),
                (
                    "asked_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="asked at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Waiting"),
                            ("done", "New password given"),
                            ("refused", "Refused"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "done_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="done at"),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="done by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "forgotten password",
                "verbose_name_plural": "forgotten passwords",
                "ordering": ["-asked_at"],
            },
        ),
    ]
