# Generated by Django 5.2.17 on 2026-09-29 08:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_forgotten_passwords"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="closed_days",
            field=models.CharField(
                blank=True,
                help_text="The days the place is closed: no free times are offered on them.",
                max_length=20,
                verbose_name="closed on",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="closes_at",
            field=models.TimeField(blank=True, null=True, verbose_name="closes at"),
        ),
        migrations.AddField(
            model_name="branch",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="e.g. #1F6FB2. Empty = the usual colour of the place.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$",
                        "Write the colour as # and 6 letters or digits, e.g. #1F6FB2.",
                    )
                ],
                verbose_name="colour",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="e-mail"),
        ),
        migrations.AddField(
            model_name="branch",
            name="file_prefix",
            field=models.CharField(
                blank=True,
                help_text="Empty = the code. e.g. EK gives the new files EK-00001.",
                max_length=10,
                verbose_name="file number prefix",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="On the top bar, the login page and the printed papers of this place.",
                upload_to="places/",
                verbose_name="logo",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="opens_at",
            field=models.TimeField(
                blank=True,
                help_text="Empty = the hours in the clinic options.",
                null=True,
                verbose_name="opens at",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="rooms_shared",
            field=models.BooleanField(
                default=False,
                help_text="Any doctor works in any free room: bookings need no room schedule, the room is chosen by itself and can be changed in one click.",
                verbose_name="rooms are shared",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="Printed under the name, e.g. Specialist dental care.",
                max_length=150,
                verbose_name="line under the name",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="theme",
            field=models.CharField(
                choices=[
                    ("standard", "Standard (light)"),
                    ("elite", "Elite (navy and gold)"),
                ],
                default="standard",
                help_text="The top bar, the buttons and the printed papers of this place.",
                max_length=10,
                verbose_name="look of the screens",
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Where it was asked: the heads of that place approve it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.branch",
                verbose_name="place",
            ),
        ),
    ]
