# Generated by Django 5.2.17 on 2026-09-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_place_look_and_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="diastolic_limit",
            field=models.PositiveSmallIntegerField(
                default=100,
                verbose_name="blood pressure from (diastolic, mmHg) needs a physician's opinion",
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="follow_up_days",
            field=models.PositiveSmallIntegerField(
                default=7, verbose_name="suture removal after other surgeries (days)"
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="follow_up_graft_days",
            field=models.PositiveSmallIntegerField(
                default=7, verbose_name="check after a bone or gum graft (days)"
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="follow_up_sinus_days",
            field=models.PositiveSmallIntegerField(
                default=2, verbose_name="check after a sinus lift (days)"
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="glucose_limit",
            field=models.PositiveSmallIntegerField(
                default=200,
                verbose_name="random blood sugar above (mg/dl) needs a physician's opinion",
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="hba1c_limit",
            field=models.DecimalField(
                decimal_places=1,
                default=7,
                max_digits=4,
                verbose_name="HbA1c above (%) needs a physician's opinion",
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="systolic_limit",
            field=models.PositiveSmallIntegerField(
                default=160,
                verbose_name="blood pressure from (systolic, mmHg) needs a physician's opinion",
            ),
        ),
    ]
