# Generated by Django 5.2.17 on 2026-10-01 09:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_round10_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprun",
            name="copy_error",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="second copy problem"
            ),
        ),
        migrations.AddField(
            model_name="backuprun",
            name="copy_where",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="second copy in"
            ),
        ),
        migrations.AddField(
            model_name="backuprun",
            name="records",
            field=models.PositiveIntegerField(default=0, verbose_name="records in it"),
        ),
        migrations.AddField(
            model_name="backuprun",
            name="verified",
            field=models.BooleanField(
                default=False, verbose_name="checked after saving"
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="force_strong_passwords",
            field=models.BooleanField(
                default=False,
                help_text="At their next login, people whose password is short, common or like their username choose a new one.",
                verbose_name="people with an easy password must change it",
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="idle_logout_minutes",
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text="A PC left open closes its session by itself. 0 = never.",
                verbose_name="log out after (minutes without use)",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weak_password",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Seen at the last login: the password is short, common or like the username (security.py).",
                verbose_name="easy password",
            ),
        ),
        migrations.CreateModel(
            name="DeletedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="kind of record"
                    ),
                ),
                ("label", models.CharField(max_length=300, verbose_name="record")),
                ("object_id", models.CharField(max_length=40, verbose_name="number")),
                ("data", models.JSONField(default=dict, verbose_name="what it held")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "page",
                    models.CharField(blank=True, max_length=300, verbose_name="page"),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "deleted record",
                "verbose_name_plural": "deleted records",
                "ordering": ["-deleted_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("login", "Logged in"),
                            ("login_failed", "Wrong password"),
                            ("locked", "Login closed after wrong passwords"),
                            ("unlocked", "Login opened again by the owner"),
                            ("logout", "Logged out"),
                            ("idle_logout", "Logged out after no use"),
                            ("forced_logout", "Logged out by the owner"),
                            ("password_changed", "Password changed"),
                            ("password_given", "Password set by the owner"),
                            ("export", "Data taken out (file, export or backup)"),
                            ("denied", "Page refused (no permission)"),
                            ("outside", "Refused: from outside the clinic's network"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="what",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="when",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=150,
                        verbose_name="username",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="device address (IP)",
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="browser"
                    ),
                ),
                (
                    "path",
                    models.CharField(blank=True, max_length=300, verbose_name="page"),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="details"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "security event",
                "verbose_name_plural": "security log",
                "ordering": ["-at", "-pk"],
            },
        ),
    ]
