# Generated by Django 5.2.17 on 2026-10-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_speed_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="signature",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="Drawn once on the screen (user menu → My signature): printed on receipts and prescriptions.",
                verbose_name="signature",
            ),
        ),
    ]
