# Generated by Django 5.2.17 on 2026-10-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_signatures"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemreport",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Recorded on the screen while the problem happens, or filmed with a phone.",
                upload_to="problems/%Y/%m/",
                verbose_name="video of the screen",
            ),
        ),
    ]
