# Generated by Django 5.2.17 on 2026-10-03 08:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_problem_video"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="opened at",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="last seen open"
                    ),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="last used"
                    ),
                ),
                (
                    "active_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="worked (seconds)"
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(default=0, verbose_name="pages opened"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ended at"
                    ),
                ),
                (
                    "end",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logout", "logged out"),
                            ("idle", "logged out for no use"),
                            ("closed", "closed the page"),
                        ],
                        max_length=10,
                        verbose_name="how it ended",
                    ),
                ),
                (
                    "device",
                    models.CharField(blank=True, max_length=120, verbose_name="device"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "time in the system",
                "verbose_name_plural": "time in the system",
                "ordering": ["-started_at"],
            },
        ),
    ]
