# Generated by Django 5.2.17 on 2026-10-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_work_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="one_device_per_login",
            field=models.BooleanField(
                default=True,
                help_text="A login opened on a second PC or tablet logs out the first one (it is told why).",
                verbose_name="one device per login",
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="session",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="A fingerprint of a session closed because the login was opened on another device: that device is told why.",
                max_length=64,
                verbose_name="session",
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("login", "Logged in"),
                    ("login_failed", "Wrong password"),
                    ("locked", "Login closed after wrong passwords"),
                    ("unlocked", "Login opened again by the owner"),
                    ("logout", "Logged out"),
                    ("idle_logout", "Logged out after no use"),
                    ("forced_logout", "Logged out by the owner"),
                    ("replaced", "Logged out: the same login opened on another device"),
                    ("password_changed", "Password changed"),
                    ("password_given", "Password set by the owner"),
                    ("export", "Data taken out (file, export or backup)"),
                    ("denied", "Page refused (no permission)"),
                    ("outside", "Refused: from outside the clinic's network"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="what",
            ),
        ),
    ]
