# Generated by Django 5.2.17 on 2026-10-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_clinicsettings_one_device_per_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="hba1c_recheck_days",
            field=models.PositiveSmallIntegerField(
                default=90,
                verbose_name="a high HbA1c: call for a new test after (days)",
            ),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="readings_recheck_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                verbose_name="a high blood sugar or pressure: call to check it again after (days)",
            ),
        ),
    ]
