# Generated by Django 5.2.17 on 2026-09-25 11:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dentists", "0003_cia_dentist_label"),
        ("patients", "0003_remove_patient_assigned_intern"),
        ("surgery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="name (English)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("antibiotic", "Antibiotic"),
                            ("painkiller", "Painkiller / anti-inflammatory"),
                            ("mouthwash", "Mouthwash / local"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        help_text="Printed on the prescription, usually in Arabic.",
                        max_length=255,
                        verbose_name="how to take it (for the patient)",
                    ),
                ),
            ],
            options={
                "verbose_name": "drug group (interchangeable drugs)",
                "verbose_name_plural": "drug groups (interchangeable drugs)",
                "ordering": ["sort_order", "name_ar"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstructionSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="name (English)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "procedures",
                    models.CharField(
                        blank=True,
                        help_text="Surgery procedures this fits, comma separated: extraction, flap, simple_implant, immediate_implant, guided, expansion, splitting, closed_sinus, open_sinus, gbr, soft_tissue. Empty = every surgery.",
                        max_length=255,
                        verbose_name="fits these procedures",
                    ),
                ),
                (
                    "body_ar",
                    models.TextField(
                        help_text="One instruction per line.",
                        verbose_name="instructions (Arabic)",
                    ),
                ),
                (
                    "body_en",
                    models.TextField(
                        blank=True,
                        help_text="One instruction per line.",
                        verbose_name="instructions (English)",
                    ),
                ),
            ],
            options={
                "verbose_name": "post-operative instruction sheet",
                "verbose_name_plural": "post-operative instruction sheets",
                "ordering": ["sort_order", "name_ar"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrescriptionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="name (English)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "procedures",
                    models.CharField(
                        blank=True,
                        help_text="Surgery procedures this fits, comma separated: extraction, flap, simple_implant, immediate_implant, guided, expansion, splitting, closed_sinus, open_sinus, gbr, soft_tissue. Empty = every surgery.",
                        max_length=255,
                        verbose_name="fits these procedures",
                    ),
                ),
                (
                    "for_penicillin_allergy",
                    models.BooleanField(
                        default=False,
                        verbose_name="for patients allergic to penicillin",
                    ),
                ),
            ],
            options={
                "verbose_name": "prescription template",
                "verbose_name_plural": "prescription templates",
                "ordering": ["sort_order", "name_ar"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, verbose_name="brand name and strength"
                    ),
                ),
                (
                    "preferred",
                    models.BooleanField(default=False, verbose_name="chosen first"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drugs",
                        to="prescriptions.druggroup",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "drug",
                "verbose_name_plural": "drugs",
                "ordering": ["group__sort_order", "-preferred", "name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "prescribed_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="notes for the patient"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="dentists.dentist",
                        verbose_name="dentist",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "surgery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="surgery.surgery",
                        verbose_name="surgery",
                    ),
                ),
            ],
            options={
                "verbose_name": "prescription",
                "verbose_name_plural": "prescriptions",
                "ordering": ["-prescribed_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dose",
                    models.CharField(max_length=255, verbose_name="how to take it"),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prescriptions.drug",
                        verbose_name="drug",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "prescription line",
                "verbose_name_plural": "prescription lines",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionTemplateLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        blank=True,
                        help_text="Leave empty to use the group's usual dose.",
                        max_length=255,
                        verbose_name="how to take it",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prescriptions.druggroup",
                        verbose_name="drug group",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="prescriptions.prescriptiontemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "template line",
                "verbose_name_plural": "template lines",
                "ordering": ["sort_order", "pk"],
            },
        ),
    ]
