# Generated by Django 5.2.17 on 2026-09-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="druggroup",
            name="kind",
            field=models.CharField(
                choices=[
                    ("antibiotic", "Antibiotic"),
                    ("painkiller", "Painkiller / anti-inflammatory"),
                    ("mouthwash", "Mouthwash / local"),
                    ("injection", "Injection (IM / IV)"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
