# Generated by Django 5.2.17 on 2026-09-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0002_injections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructionsheet",
            name="procedures",
            field=models.CharField(
                blank=True,
                help_text="Surgery procedures this fits, comma separated: extraction, flap, simple_implant, immediate_implant, guided, expansion, splitting, closed_sinus, open_sinus, gbr, soft_tissue; delivery = the day the teeth on the implants are delivered. Empty = every surgery.",
                max_length=255,
                verbose_name="fits these procedures",
            ),
        ),
        migrations.AlterField(
            model_name="prescriptiontemplate",
            name="procedures",
            field=models.CharField(
                blank=True,
                help_text="Surgery procedures this fits, comma separated: extraction, flap, simple_implant, immediate_implant, guided, expansion, splitting, closed_sinus, open_sinus, gbr, soft_tissue; delivery = the day the teeth on the implants are delivered. Empty = every surgery.",
                max_length=255,
                verbose_name="fits these procedures",
            ),
        ),
    ]
