# Generated by Django 5.2.17 on 2026-09-27 10:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0006_fill_places_and_machine"),
        ("core", "0010_cic_name"),
        ("dentists", "0005_places"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "paid_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="date",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Visa / card"),
                            ("instapay", "InstaPay"),
                            ("wallet", "Mobile wallet (Vodafone Cash...)"),
                            ("bank", "Bank transfer"),
                            ("bank_deposit", "Bank deposit"),
                            ("cheque", "Cheque"),
                            ("fawry", "Fawry POS machine"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="transaction reference"
                    ),
                ),
                (
                    "period_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="for the work from"
                    ),
                ),
                (
                    "period_to",
                    models.DateField(blank=True, null=True, verbose_name="to"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="dentists.dentist",
                        verbose_name="doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment to a doctor",
                "verbose_name_plural": "payments to doctors",
                "ordering": ["-paid_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="FeeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage of what the patient paid"),
                            ("per_unit", "Fixed amount for each service (each tooth)"),
                            ("per_visit", "Fixed amount for each visit"),
                        ],
                        default="percent",
                        max_length=12,
                        verbose_name="how the doctor is paid",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="e.g. 30 for 30%, or 1500 for 1,500 a tooth or a visit.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="percentage or amount",
                    ),
                ),
                (
                    "starts_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="from"
                    ),
                ),
                (
                    "ends_on",
                    models.DateField(
                        blank=True,
                        help_text="Empty = until changed.",
                        null=True,
                        verbose_name="until",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_rules",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_rules",
                        to="dentists.dentist",
                        verbose_name="doctor",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty = every service. A rule for one service (e.g. implants) comes before the rule for every service.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_rules",
                        to="billing.service",
                        verbose_name="for the service",
                    ),
                ),
            ],
            options={
                "verbose_name": "doctor's fee rule",
                "verbose_name_plural": "doctors' fee rules",
                "ordering": ["branch", "dentist__full_name", "service", "-starts_on"],
            },
        ),
    ]
