# Generated by Django 5.2.17 on 2026-09-29 08:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_lab_and_implant_costs"),
        ("clinics", "0001_initial"),
        ("core", "0015_place_look_and_hours"),
        ("dentists", "0006_specialty_and_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feerule",
            name="deduct_costs",
            field=models.BooleanField(
                default=False,
                help_text="The percentage is of what the patient paid less the lab and implant cost of the service.",
                verbose_name="take off the lab and implant cost first",
            ),
        ),
        migrations.AddField(
            model_name="feerule",
            name="patient_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Every patient"),
                    ("own", "His own patients (he brought them)"),
                    ("clinic", "Patients of the clinic (referred to him)"),
                ],
                default="",
                help_text="e.g. 40 percent of his own patients and 30 percent of the patients the clinic refers to him. A patient is the doctor's own when the patient's file says he brought him.",
                max_length=8,
                verbose_name="for the patients",
            ),
        ),
        migrations.CreateModel(
            name="DoctorPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="his price",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Empty = the cost written on the service.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="usual lab / implant cost (each tooth)",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_prices",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="dentists.dentist",
                        verbose_name="doctor",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_prices",
                        to="billing.service",
                        verbose_name="service",
                    ),
                ),
            ],
            options={
                "verbose_name": "doctor's price",
                "verbose_name_plural": "doctors' prices",
                "ordering": [
                    "branch",
                    "dentist__full_name",
                    "service__sort_order",
                    "service__name_ar",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dentist", "branch", "service"),
                        name="one_price_a_service",
                    )
                ],
            },
        ),
    ]
