# Generated by Django 5.2.17 on 2026-10-02 12:01

import django.db.models.deletion
import reading.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="file number"
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "national_id",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                (
                    "phone_primary",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                (
                    "phone_secondary",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                (
                    "values",
                    models.JSONField(
                        default=dict,
                        help_text="The patient's values in the dental system, as text.",
                    ),
                ),
            ],
            options={
                "verbose_name": "registered patient",
                "ordering": ["file_number"],
            },
        ),
        migrations.CreateModel(
            name="ReaderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="The pages leave this PC and go to Anthropic (the company that makes Claude) over the internet to be read. Anthropic does not use them to train its models. Switch on only after the patients' consent and your lawyer's advice.",
                        verbose_name="send the scanned pages to Claude to read",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("claude-opus-5-5", "Claude Opus 5.5 (the most accurate)"),
                            ("claude-sonnet-5-5", "Claude Sonnet 5.5 (half the price)"),
                        ],
                        default="claude-opus-5-5",
                        max_length=40,
                        verbose_name="model",
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        choices=[
                            ("low", "Low (the cheapest)"),
                            ("medium", "Medium (usual)"),
                            ("high", "High (hard handwriting; costs more)"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="how hard it thinks",
                    ),
                ),
                (
                    "two_readings",
                    models.BooleanField(
                        default=True,
                        help_text="Where the two readings differ, the field is marked for checking. It catches more mistakes and costs twice as much.",
                        verbose_name="read each page twice and compare",
                    ),
                ),
                (
                    "default_mode",
                    models.CharField(
                        choices=[
                            ("now", "Now (full price, about a minute a file)"),
                            (
                                "batch",
                                "In a batch (half price, back within a few hours)",
                            ),
                        ],
                        default="batch",
                        max_length=10,
                        verbose_name="usual way of sending",
                    ),
                ),
                (
                    "monthly_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        help_text="Nothing more is sent this month when the month's cost reaches it. 0 = no limit.",
                        max_digits=8,
                        verbose_name="monthly limit (US dollars)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "settings",
            },
        ),
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "made_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="made at"),
                ),
                ("place_code", models.CharField(max_length=10, verbose_name="place")),
                ("name", models.CharField(max_length=120, verbose_name="file name")),
                ("package", models.FileField(upload_to="exports/")),
                ("count", models.PositiveIntegerField(default=0, verbose_name="files")),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "package for the system",
                "ordering": ["-made_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PaperFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=reading.models.new_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("upload", models.CharField(blank=True, db_index=True, max_length=32)),
                (
                    "place_code",
                    models.CharField(blank=True, max_length=10, verbose_name="place"),
                ),
                (
                    "original",
                    models.FileField(
                        upload_to=reading.models.original_path,
                        verbose_name="the scan as it was uploaded",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="file name"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("now", "Now (full price, about a minute a file)"),
                            (
                                "batch",
                                "In a batch (half price, back within a few hours)",
                            ),
                        ],
                        default="batch",
                        max_length=10,
                        verbose_name="sent",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting to be read"),
                            ("reading", "Being read"),
                            ("review", "To check"),
                            ("approved", "Approved: ready to send to the system"),
                            ("exported", "Sent to the system"),
                            ("set_aside", "Set aside (typed by hand)"),
                            ("failed", "Could not be read"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "page_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="pages"),
                ),
                (
                    "cover_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="file number on the cover sheet",
                    ),
                ),
                (
                    "suggested",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="seems to be the file"
                    ),
                ),
                ("suggested_reason", models.CharField(blank=True, max_length=20)),
                (
                    "error",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="problem"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("approved", models.JSONField(blank=True, null=True)),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exported_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="reading.export",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper file",
                "verbose_name_plural": "paper files",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PaperPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="page")),
                (
                    "image",
                    models.FileField(
                        upload_to=reading.models.page_path, verbose_name="picture"
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cover", "Cover sheet (file number)"),
                            ("id_front", "ID card - front"),
                            ("id_back", "ID card - back"),
                            ("registration", "Registration (patient's data)"),
                            ("history", "Medical and dental history"),
                            ("examination", "Examination"),
                            ("tooth_chart", "Dental chart (drawing of the teeth)"),
                            ("plan", "Treatment plan"),
                            ("surgery", "Surgery chart"),
                            ("treatment_log", "Treatment log (visits)"),
                            ("prescription", "Prescription"),
                            ("lab", "Lab paper"),
                            ("consent", "Signed consent"),
                            ("receipt", "Receipt or payments"),
                            ("xray", "X-ray, CBCT or photo"),
                            ("other", "Other"),
                            ("blank", "Blank page"),
                        ],
                        max_length=20,
                        verbose_name="what the page is",
                    ),
                ),
                (
                    "turned",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="turned (degrees, clockwise)"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=300, verbose_name="notes"),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="reading.paperfile",
                    ),
                ),
            ],
            options={
                "ordering": ["file", "number"],
            },
        ),
        migrations.CreateModel(
            name="PaperField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("value", models.TextField(blank=True)),
                ("written", models.TextField(blank=True)),
                ("other", models.TextField(blank=True)),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("sure", "Sure"),
                            ("check", "Please check"),
                            ("unclear", "Cannot be read"),
                        ],
                        default="sure",
                        max_length=10,
                    ),
                ),
                ("problems", models.JSONField(blank=True, default=list)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "box",
                    models.JSONField(
                        blank=True,
                        help_text="[left, top, right, bottom] on the upright page picture.",
                        null=True,
                    ),
                ),
                ("checked", models.BooleanField(default=False)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="reading.paperfile",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="reading.paperpage",
                    ),
                ),
            ],
            options={
                "ordering": ["file", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PaperReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("sending", "Being sent"),
                            ("sent", "Sent"),
                            ("done", "Read"),
                            ("failed", "Not read"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=10,
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("batched", models.BooleanField(default=False)),
                ("model", models.CharField(blank=True, max_length=60)),
                ("result", models.JSONField(blank=True, null=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("cache_write_tokens", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("tries", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="reading.paperpage",
                    ),
                ),
            ],
            options={
                "ordering": ["page", "number"],
            },
        ),
        migrations.CreateModel(
            name="SystemLists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "place_code",
                    models.CharField(blank=True, max_length=10, verbose_name="place"),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="brought in at"
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "lists from the dental system",
            },
        ),
        migrations.AddConstraint(
            model_name="paperpage",
            constraint=models.UniqueConstraint(
                fields=("file", "number"), name="reader_page_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="paperfield",
            constraint=models.UniqueConstraint(
                fields=("file", "name"), name="reader_field_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="paperreading",
            constraint=models.UniqueConstraint(
                fields=("page", "number"), name="reader_reading_once"
            ),
        ),
    ]
