# Generated by Django 5.2.17 on 2026-09-25 07:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("patients", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabWorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="name (English)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "lab work type",
                "verbose_name_plural": "lab work types",
                "ordering": ["sort_order", "name_ar"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TreatmentStepType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="name (English)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "treatment step type",
                "verbose_name_plural": "treatment step types",
                "ordering": ["sort_order", "name_ar"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="name"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="phone"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contact person"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the lab is our own lab.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.branch",
                        verbose_name="our branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab",
                "verbose_name_plural": "labs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LabRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="request number",
                    ),
                ),
                (
                    "teeth",
                    models.CharField(
                        max_length=100, verbose_name="teeth (FDI numbers)"
                    ),
                ),
                (
                    "units",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="number of units"
                    ),
                ),
                (
                    "shade",
                    models.CharField(blank=True, max_length=30, verbose_name="shade"),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="material"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, verbose_name="instructions to the lab"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="needed back by"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Waiting for supervisor review"),
                            ("approved", "Reviewed - ready to send"),
                            ("sent", "At the lab"),
                            ("received", "Received from lab"),
                            ("delivered", "Delivered to patient"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="received at"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered to patient at"
                    ),
                ),
                (
                    "remake_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="times returned to lab"
                    ),
                ),
                (
                    "lab_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="lab cost",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_requests",
                        to="scheduling.appointment",
                        verbose_name="visit",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_requests",
                        to="core.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="clinical.lab",
                        verbose_name="lab",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_requests",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="received by",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requested by (doctor)",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sent by",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinical.labworktype",
                        verbose_name="work type",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab request",
                "verbose_name_plural": "lab requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabRequestEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("submitted", "Sent for review"),
                            ("approved", "Reviewed and approved"),
                            ("returned", "Returned to doctor for changes"),
                            ("sent", "Sent to lab"),
                            ("received", "Received from lab"),
                            ("remake", "Returned to lab for remake"),
                            ("delivered", "Delivered to patient"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="time"
                    ),
                ),
                (
                    "checked_against_request",
                    models.BooleanField(
                        default=False, verbose_name="work checked against the request"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="by",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="clinical.labrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "lab request history",
                "verbose_name_plural": "lab request history",
                "ordering": ["at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "teeth",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 36, 37 or 11-13",
                        max_length=100,
                        verbose_name="teeth (FDI numbers)",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="done at"
                    ),
                ),
                (
                    "implant_system",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="implant system / brand",
                    ),
                ),
                (
                    "implant_size",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="implant size (diameter x length)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="details")),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="checked at"
                    ),
                ),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="Supervisor evaluation from 1 (poor) to 5 (excellent).",
                        null=True,
                        verbose_name="grade",
                    ),
                ),
                (
                    "supervisor_comment",
                    models.TextField(blank=True, verbose_name="supervisor comment"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_steps",
                        to="scheduling.appointment",
                        verbose_name="visit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_steps",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="done by (intern)",
                    ),
                ),
                (
                    "supervised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="supervisor present",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="checked by",
                    ),
                ),
                (
                    "step_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinical.treatmentsteptype",
                        verbose_name="step",
                    ),
                ),
            ],
            options={
                "verbose_name": "treatment step",
                "verbose_name_plural": "treatment steps",
                "ordering": ["-performed_at"],
            },
        ),
    ]
