# Generated by Django 5.2.17 on 2026-09-25 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
        ("dentists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="labrequest",
            name="dentist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_requests",
                to="dentists.dentist",
                verbose_name="dentist",
            ),
        ),
        migrations.AddField(
            model_name="treatmentstep",
            name="assistant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatments_assisted",
                to="dentists.dentist",
                verbose_name="assistant",
            ),
        ),
        migrations.AddField(
            model_name="treatmentstep",
            name="chart_updated",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="dental chart updated"
            ),
        ),
        migrations.AddField(
            model_name="treatmentstep",
            name="material",
            field=models.CharField(blank=True, max_length=60, verbose_name="material"),
        ),
        migrations.AddField(
            model_name="treatmentstep",
            name="next_visit",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="next visit"
            ),
        ),
        migrations.AddField(
            model_name="treatmentstep",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treatments_operated",
                to="dentists.dentist",
                verbose_name="operator",
            ),
        ),
        migrations.AddField(
            model_name="treatmentstep",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatments_supervised",
                to="dentists.dentist",
                verbose_name="supervisor",
            ),
        ),
        migrations.AddField(
            model_name="treatmentstep",
            name="surfaces",
            field=models.CharField(
                blank=True,
                help_text="e.g. MO, DO, MOD",
                max_length=10,
                verbose_name="surfaces",
            ),
        ),
        migrations.AddField(
            model_name="treatmentsteptype",
            name="chart_effect",
            field=models.CharField(
                choices=[
                    ("none", "No change to the dental chart"),
                    ("caries", "Caries found"),
                    ("filling", "Filling / restoration"),
                    ("rct", "Root canal treatment"),
                    ("crown", "Crown on natural tooth"),
                    ("extraction", "Extraction (tooth becomes missing)"),
                    ("implant", "Implant placed"),
                    ("uncover", "Implant uncovered (2nd stage / healing abutment)"),
                    ("impression", "Impression / digital scan (implant stage)"),
                    (
                        "delivery",
                        "Final prosthesis delivered (implant loaded / tooth crowned)",
                    ),
                    ("implant_failed", "Implant failed / removed (becomes missing)"),
                    ("hopeless", "Tooth hopeless"),
                    ("sound", "Tooth sound (clear findings)"),
                ],
                default="none",
                help_text="When this step is recorded on tooth numbers, the chart of those teeth is updated this way.",
                max_length=20,
                verbose_name="effect on dental chart",
            ),
        ),
        migrations.AddField(
            model_name="treatmentsteptype",
            name="default_material",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="default material"
            ),
        ),
        migrations.AlterField(
            model_name="labrequest",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="requested by (doctor)",
            ),
        ),
        migrations.AlterField(
            model_name="treatmentstep",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treatment_steps",
                to=settings.AUTH_USER_MODEL,
                verbose_name="done by (intern)",
            ),
        ),
    ]
