# Generated by Django 5.2.17 on 2026-09-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0002_move_people_to_dentists"),
        ("clinical", "0002_labrequest_dentist_treatmentstep_assistant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labrequest",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="treatmentstep",
            name="performed_by",
        ),
        migrations.RemoveField(
            model_name="treatmentstep",
            name="supervised_by",
        ),
    ]
