# Generated by Django 5.2.17 on 2026-09-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0003_remove_labrequest_requested_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentsteptype",
            name="surgery_procedure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extraction", "Extraction"),
                    ("flap", "Flap"),
                    ("simple_implant", "Simple implant"),
                    ("immediate_implant", "Immediate implant"),
                    ("expansion", "Expansion"),
                    ("splitting", "Splitting"),
                    ("closed_sinus", "Closed sinus"),
                    ("open_sinus", "Open sinus"),
                    ("gbr", "GBR"),
                    ("guided", "Guided implant"),
                ],
                help_text="Planned items of this type are ticked automatically when the surgery chart records it.",
                max_length=20,
                verbose_name="matching surgery-chart procedure",
            ),
        ),
    ]
