# Generated by Django 5.2.17 on 2026-09-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0004_treatmentsteptype_surgery_procedure"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="name (English)"
            ),
        ),
    ]
