# Generated by Django 5.2.17 on 2026-09-25 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0005_lab_name_en"),
        ("dentists", "0003_cia_dentist_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="labrequest",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisors do not log in: choose who checked the request and it goes straight to the secretary.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_requests_reviewed",
                to="dentists.dentist",
                verbose_name="reviewed by supervisor",
            ),
        ),
    ]
