# Generated by Django 5.2.17 on 2026-09-25 18:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0006_labrequest_supervisor"),
        ("dentists", "0004_dentist_arabic_name"),
        ("patients", "0005_out_dates_governorates_documents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentsteptype",
            name="description_ar",
            field=models.CharField(
                blank=True,
                help_text="Plain words for the reception and the patient, e.g. حشو أبيض بلون السن لسد التسوس.",
                max_length=255,
                verbose_name="simple explanation (Arabic)",
            ),
        ),
        migrations.CreateModel(
            name="OutsideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cbct", "CBCT request"),
                            ("medical_lab", "Medical lab request"),
                        ],
                        max_length=20,
                        verbose_name="request",
                    ),
                ),
                (
                    "requested_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upper", "Upper jaw"),
                            ("lower", "Lower jaw"),
                            ("both", "Both jaws"),
                            ("teeth", "Only the teeth written below"),
                        ],
                        max_length=10,
                        verbose_name="area to scan",
                    ),
                ),
                (
                    "teeth",
                    models.CharField(blank=True, max_length=100, verbose_name="teeth"),
                ),
                (
                    "field_of_view",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small", "Small (a few teeth)"),
                            ("medium", "Medium (one jaw)"),
                            ("large", "Large (both jaws, sinuses)"),
                        ],
                        max_length=10,
                        verbose_name="field of view",
                    ),
                ),
                (
                    "purposes",
                    models.JSONField(blank=True, default=list, verbose_name="for"),
                ),
                (
                    "tests",
                    models.JSONField(blank=True, default=list, verbose_name="tests"),
                ),
                (
                    "other_tests",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="other tests"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="notes for the centre"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outside_requests",
                        to="dentists.dentist",
                        verbose_name="requested by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outside_requests",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "CBCT / medical lab request",
                "verbose_name_plural": "CBCT / medical lab requests",
                "ordering": ["-requested_on", "-pk"],
            },
        ),
    ]
