# Generated by Django 5.2.17 on 2026-09-25 19:02

from django.db import migrations, models


def set_categories(apps, schema_editor):
    """Implants, surgeries and their steps go to the implant section of the plans."""
    StepType = apps.get_model("clinical", "TreatmentStepType")
    implant = StepType.objects.exclude(surgery_procedure="") | StepType.objects.filter(
        chart_effect__in=("implant", "uncover", "implant_failed"))
    implant.update(category="implant")


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0007_explanations_and_outside_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentsteptype",
            name="category",
            field=models.CharField(
                choices=[
                    ("implant", "Implant and surgery"),
                    ("restorative", "Restorative and other"),
                ],
                default="restorative",
                max_length=20,
                verbose_name="plan section",
            ),
        ),
        migrations.RunPython(set_categories, migrations.RunPython.noop),
    ]
