# Generated by Django 5.2.17 on 2026-09-26 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0008_treatment_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="labrequest",
            name="collected_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="taken from the dentist at"
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="collected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="taken from the dentist by",
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="shade_guide",
            field=models.CharField(
                blank=True,
                choices=[
                    ("classical", "VITA classical"),
                    ("3d_master", "VITA 3D-Master"),
                ],
                max_length=10,
                verbose_name="shade guide",
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="work_form",
            field=models.CharField(
                choices=[
                    (
                        "physical",
                        "Physical (impression / model): the secretary takes it and sends it",
                    ),
                    ("digital", "Digital scan: the file goes to the lab"),
                ],
                default="physical",
                max_length=10,
                verbose_name="the work goes as",
            ),
        ),
        migrations.AddField(
            model_name="labworktype",
            name="default_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="When sent, the date the work is needed back is set this many days later.",
                null=True,
                verbose_name="usual days at the lab",
            ),
        ),
        migrations.AlterField(
            model_name="labrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Waiting for supervisor review"),
                    ("approved", "Reviewed - ready to send"),
                    ("collected", "Taken from the dentist - at the reception"),
                    ("sent", "At the lab"),
                    ("received", "Received from lab"),
                    ("delivered", "Delivered to patient"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="labrequestevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("submitted", "Sent for review"),
                    ("collected", "Taken from the dentist by the reception"),
                    ("approved", "Reviewed and approved"),
                    ("returned", "Returned to doctor for changes"),
                    ("sent", "Sent to lab"),
                    ("received", "Received from lab"),
                    ("remake", "Returned to lab for remake"),
                    ("delivered", "Delivered to patient"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
                verbose_name="action",
            ),
        ),
    ]
