# Generated by Django 5.2.17 on 2026-09-28 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0009_lab_cycle_shades_days"),
        ("patients", "0008_patients_per_place"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="outsiderequest",
            name="done_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="marked done by",
            ),
        ),
        migrations.AddField(
            model_name="outsiderequest",
            name="done_on",
            field=models.DateField(blank=True, null=True, verbose_name="done on"),
        ),
        migrations.AddField(
            model_name="outsiderequest",
            name="result",
            field=models.ForeignKey(
                blank=True,
                help_text="The X-ray / CBCT record with the folder or the link of the scan.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="patients.patientdocument",
                verbose_name="the scan",
            ),
        ),
        migrations.AddField(
            model_name="outsiderequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("done_here", "Done in our clinic"),
                    ("done_outside", "Done at the centre"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
