# Generated by Django 5.2.17 on 2026-09-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0010_cbct_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="labrequest",
            name="enclosures",
            field=models.JSONField(
                blank=True, default=list, verbose_name="sent with the work"
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="implant_details",
            field=models.CharField(
                blank=True,
                help_text="e.g. Neodent GM 4.3, Ti-base, multi-unit 17°",
                max_length=150,
                verbose_name="on implants: system, platform and abutment",
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="margin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chamfer", "Chamfer"),
                    ("heavy_chamfer", "Heavy chamfer"),
                    ("shoulder", "Shoulder"),
                    ("feather", "Knife edge / feather"),
                    ("vertical", "Vertical (BOPT)"),
                ],
                max_length=15,
                verbose_name="finish line",
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="occlusion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("normal", "Normal contacts"),
                    ("light", "Light contacts"),
                    ("out", "Out of occlusion"),
                ],
                max_length=10,
                verbose_name="occlusion",
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="pontic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ovate", "Ovate"),
                    ("ridge_lap", "Modified ridge lap"),
                    ("sanitary", "Sanitary (hygienic)"),
                    ("conical", "Conical"),
                ],
                max_length=12,
                verbose_name="pontic design",
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="retention",
            field=models.CharField(
                blank=True,
                choices=[("screw", "Screw-retained"), ("cement", "Cement-retained")],
                max_length=10,
                verbose_name="on implants: retention",
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="shade_cervical",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="cervical third"
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="shade_incisal",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="incisal third"
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="stage",
            field=models.CharField(
                choices=[
                    ("final", "Final work"),
                    ("framework", "Framework try-in"),
                    ("bisque", "Bisque try-in"),
                    ("wax", "Wax try-in / wax-up"),
                    ("temporary", "Temporary (PMMA)"),
                    ("repair", "Repair / remake"),
                ],
                default="final",
                max_length=12,
                verbose_name="send for",
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="stump_shade",
            field=models.CharField(
                blank=True, max_length=5, verbose_name="prepared tooth (stump) shade"
            ),
        ),
    ]
