# Generated by Django 5.2.17 on 2026-09-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0011_detailed_lab_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="labworktype",
            name="category",
            field=models.CharField(
                choices=[
                    ("zirconia", "Zirconia"),
                    ("emax", "E.max (lithium disilicate)"),
                    ("pfm", "Cast metal and porcelain (PFM)"),
                    (
                        "resin_print",
                        "3D printing in resin (models, guides, temporaries)",
                    ),
                    ("pmma", "Milled PMMA (temporaries)"),
                    ("metal_print", "Metal printing (CoCr / titanium)"),
                    ("ti_mill", "Titanium milling"),
                    ("print_mill", "Metal printed, then finished by milling"),
                    ("removable", "Removable dentures"),
                    ("splint", "Splints, night guards and orthodontic appliances"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Gives the usual steps at our lab: e.g. zirconia is designed, milled, sintered, stained and glazed.",
                max_length=15,
                verbose_name="kind of work",
            ),
        ),
        migrations.AddField(
            model_name="labworktype",
            name="unit",
            field=models.CharField(
                choices=[
                    ("tooth", "per tooth / unit"),
                    ("arch", "per arch"),
                    ("case", "per case"),
                ],
                default="tooth",
                max_length=6,
                verbose_name="priced",
            ),
        ),
    ]
