# Generated by Django 5.2.17 on 2026-09-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0012_labworktype_category_labworktype_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentsteptype",
            name="group",
            field=models.CharField(
                choices=[
                    ("records", "Diagnosis and records"),
                    ("surgery", "Surgery and implants"),
                    ("implant_teeth", "Teeth on implants"),
                    ("endo", "Endodontics (root canal)"),
                    ("fillings", "Fillings"),
                    ("fixed", "Crowns and bridges"),
                    ("removable", "Dentures"),
                    ("gums", "Gums and cleaning"),
                    ("ortho", "Orthodontics and TMJ"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="The dentist taps the kind of work, then this step.",
                max_length=20,
                verbose_name="kind of work",
            ),
        ),
        migrations.AddField(
            model_name="treatmentsteptype",
            name="journey_step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("impression", "Primary impression / diagnostic scan"),
                    ("cbct", "CBCT"),
                ],
                help_text="Recording it ticks this step of the patient's file (e.g. a primary impression).",
                max_length=12,
                verbose_name="counts as the file's step",
            ),
        ),
        migrations.AddField(
            model_name="treatmentsteptype",
            name="shots",
            field=models.CharField(
                blank=True,
                help_text="Comma separated: pa_before, pa_working, pa_cone, pa_after, photo_before, photo_after, photo_shade.",
                max_length=120,
                verbose_name="photos and X-rays to take",
            ),
        ),
    ]
