# Generated by Django 5.2.17 on 2026-10-05 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_ownercash"),
        ("clinical", "0014_speed_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentsteptype",
            name="implant_record",
            field=models.CharField(
                blank=True,
                choices=[
                    ("follow_up", "Implant follow-up (the findings)"),
                    ("complication", "Implant complication"),
                ],
                help_text="Recorded on an implant tooth, the page of the implant's follow-up or complication opens next.",
                max_length=12,
                verbose_name="on an implant, also write",
            ),
        ),
        migrations.AddField(
            model_name="treatmentsteptype",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Recording this step offers its bill with this service and its price (round 15).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_types",
                to="billing.service",
                verbose_name="paid service (bill)",
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsteptype",
            name="group",
            field=models.CharField(
                choices=[
                    ("records", "Diagnosis and records"),
                    ("gums", "Periodontics and prevention"),
                    ("fillings", "Operative dentistry (fillings)"),
                    ("endo", "Endodontics (root canal)"),
                    ("fixed", "Fixed prosthodontics (crowns, bridges, veneers)"),
                    ("removable", "Removable prosthodontics (dentures)"),
                    ("surgery", "Oral surgery (extractions)"),
                    ("implant_surgery", "Implant surgery and bone grafting"),
                    ("implant_teeth", "Implant prosthodontics (teeth on implants)"),
                    ("implant_care", "Implant follow-up and complications"),
                    ("ortho", "Orthodontics and TMJ"),
                    ("pedo", "Pediatric dentistry"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="The dentist taps the kind of work, then this step.",
                max_length=20,
                verbose_name="kind of work",
            ),
        ),
    ]
