# Generated by Django 5.2.17 on 2026-09-25 10:01

import apps.surgery.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_userprofile_language"),
        ("dentists", "0002_move_people_to_dentists"),
        ("patients", "0003_remove_patient_assigned_intern"),
        ("scheduling", "0003_dentist_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImplantSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=80, verbose_name="company")),
                (
                    "line",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="implant type / line"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "implant system",
                "verbose_name_plural": "implant systems",
                "ordering": ["company", "line"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "line"), name="unique_implant_system"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("query", models.TextField(verbose_name="filters")),
                (
                    "shared",
                    models.BooleanField(
                        default=True, verbose_name="visible to all managers"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "saved search",
                "verbose_name_plural": "saved searches",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Surgery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="surgery number",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="date",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("moderate", "Moderate"),
                            ("advanced", "Advanced (sinus / GBR / block)"),
                        ],
                        default="simple",
                        max_length=20,
                        verbose_name="case difficulty",
                    ),
                ),
                (
                    "block_graft",
                    models.BooleanField(default=False, verbose_name="block graft"),
                ),
                (
                    "block_donor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chin", "Chin"),
                            ("ramus", "Ramus"),
                            ("tuberosity", "Tuberosity"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="block donor site",
                    ),
                ),
                (
                    "block_donor_other",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="other donor site"
                    ),
                ),
                (
                    "cut_by",
                    models.CharField(
                        blank=True,
                        choices=[("disc", "Disc"), ("piezo", "Piezo")],
                        max_length=10,
                        verbose_name="cut by",
                    ),
                ),
                (
                    "screws_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="number of screws"
                    ),
                ),
                (
                    "bone_particle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("autogenous", "Autogenous only (100%)"),
                            ("xenograft", "Xenograft only (100%)"),
                            ("mix", "Mix autogenous : xenograft"),
                        ],
                        max_length=20,
                        verbose_name="bone particle",
                    ),
                ),
                (
                    "autogenous_percent",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="For a mix: the rest is xenograft.",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="autogenous %",
                    ),
                ),
                (
                    "bone_material",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="bone graft material / brand",
                    ),
                ),
                (
                    "acm_bur_area",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="ACM bur - area"
                    ),
                ),
                ("gbr_notes", models.TextField(blank=True, verbose_name="GBR notes")),
                (
                    "sinus_approach",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="sinus approach"
                    ),
                ),
                (
                    "sinus_fill_material",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="sinus fill material"
                    ),
                ),
                (
                    "sinus_notes",
                    models.TextField(blank=True, verbose_name="sinus notes"),
                ),
                (
                    "membrane_used",
                    models.BooleanField(default=False, verbose_name="membrane used"),
                ),
                (
                    "membrane_size",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="membrane size (mm x mm)",
                    ),
                ),
                (
                    "membrane_material",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="membrane material"
                    ),
                ),
                (
                    "membrane_company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="membrane company"
                    ),
                ),
                (
                    "tacks_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="number of tacks"
                    ),
                ),
                (
                    "tacks_company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="tacks company"
                    ),
                ),
                (
                    "soft_tissue_graft",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fgg", "Free gingival graft"),
                            ("ctg", "Connective tissue graft"),
                            ("other", "Other soft tissue graft"),
                        ],
                        max_length=10,
                        verbose_name="soft tissue graft",
                    ),
                ),
                (
                    "soft_tissue_technique",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="surgery technique"
                    ),
                ),
                (
                    "exposure",
                    models.BooleanField(blank=True, null=True, verbose_name="exposure"),
                ),
                (
                    "custom_healing_teeth",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="customized healing collar - teeth",
                    ),
                ),
                (
                    "donor_site",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="donor site"
                    ),
                ),
                (
                    "soft_tissue_suture_material",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="soft tissue suture material",
                    ),
                ),
                (
                    "soft_tissue_suture_technique",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="soft tissue suture technique",
                    ),
                ),
                (
                    "pack_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="pack type"
                    ),
                ),
                (
                    "recipient_area",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="recipient site - area"
                    ),
                ),
                (
                    "augmentation_sites",
                    models.CharField(
                        blank=True,
                        help_text="Buccal, crestal, lingual, mesial, distal.",
                        max_length=30,
                        verbose_name="augmentation site",
                    ),
                ),
                (
                    "frenectomy",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="frenectomy"
                    ),
                ),
                (
                    "soft_tissue_bone_graft",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="bone graft with soft tissue surgery (type & site)",
                    ),
                ),
                (
                    "soft_tissue_notes",
                    models.TextField(blank=True, verbose_name="soft tissue notes"),
                ),
                (
                    "suture_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3-0", "3-0"),
                            ("4-0", "4-0"),
                            ("5-0", "5-0"),
                            ("6-0", "6-0"),
                            ("7-0", "7-0"),
                        ],
                        max_length=5,
                        verbose_name="suture size",
                    ),
                ),
                (
                    "suture_material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vicryl", "Vicryl"),
                            ("prolene", "Prolene"),
                            ("silk", "Silk"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="suture material",
                    ),
                ),
                (
                    "suture_technique",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="suture technique"
                    ),
                ),
                (
                    "xray_taken",
                    models.BooleanField(default=False, verbose_name="X-ray taken"),
                ),
                (
                    "xray_notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="X-ray notes"
                    ),
                ),
                (
                    "temporary",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("healing_collar", "Healing collar"),
                            ("custom_healing", "Customized healing collar"),
                            ("crown", "Crown"),
                            ("maryland", "Maryland bridge"),
                            ("bridge_on_teeth", "Bridge on teeth"),
                            ("denture_fiber", "Denture with glass fiber"),
                        ],
                        max_length=20,
                        verbose_name="temporary",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "complications",
                    models.TextField(
                        blank=True, verbose_name="complications / post-operative notes"
                    ),
                ),
                (
                    "chart_updated",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="dental chart updated",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgeries",
                        to="scheduling.appointment",
                        verbose_name="visit",
                    ),
                ),
                (
                    "assistant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgeries_assisted",
                        to="dentists.dentist",
                        verbose_name="assistant",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgeries",
                        to="core.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgeries_instructed",
                        to="dentists.dentist",
                        verbose_name="instructor",
                    ),
                ),
                (
                    "operator_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgeries_as_op1",
                        to="dentists.dentist",
                        verbose_name="operator 1",
                    ),
                ),
                (
                    "operator_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgeries_as_op2",
                        to="dentists.dentist",
                        verbose_name="operator 2",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgeries",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "surgery",
                "verbose_name_plural": "surgeries",
                "ordering": ["-date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SurgerySite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tooth",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (18, "18"),
                            (17, "17"),
                            (16, "16"),
                            (15, "15"),
                            (14, "14"),
                            (13, "13"),
                            (12, "12"),
                            (11, "11"),
                            (21, "21"),
                            (22, "22"),
                            (23, "23"),
                            (24, "24"),
                            (25, "25"),
                            (26, "26"),
                            (27, "27"),
                            (28, "28"),
                            (48, "48"),
                            (47, "47"),
                            (46, "46"),
                            (45, "45"),
                            (44, "44"),
                            (43, "43"),
                            (42, "42"),
                            (41, "41"),
                            (31, "31"),
                            (32, "32"),
                            (33, "33"),
                            (34, "34"),
                            (35, "35"),
                            (36, "36"),
                            (37, "37"),
                            (38, "38"),
                        ],
                        verbose_name="tooth",
                    ),
                ),
                (
                    "extraction",
                    models.BooleanField(default=False, verbose_name="extraction"),
                ),
                ("flap", models.BooleanField(default=False, verbose_name="flap")),
                (
                    "simple_implant",
                    models.BooleanField(default=False, verbose_name="simple implant"),
                ),
                (
                    "immediate_implant",
                    models.BooleanField(
                        default=False, verbose_name="immediate implant"
                    ),
                ),
                (
                    "expansion",
                    models.BooleanField(default=False, verbose_name="expansion"),
                ),
                (
                    "splitting",
                    models.BooleanField(default=False, verbose_name="splitting"),
                ),
                (
                    "closed_sinus",
                    models.BooleanField(default=False, verbose_name="closed sinus"),
                ),
                (
                    "open_sinus",
                    models.BooleanField(default=False, verbose_name="open sinus"),
                ),
                ("gbr", models.BooleanField(default=False, verbose_name="GBR")),
                (
                    "guided",
                    models.BooleanField(default=False, verbose_name="guided implant"),
                ),
                (
                    "implant_diameter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="implant diameter (mm)",
                    ),
                ),
                (
                    "implant_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="implant length (mm)",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="lot / ref number"
                    ),
                ),
                (
                    "sticker",
                    models.FileField(
                        blank=True,
                        upload_to=apps.surgery.models.sticker_path,
                        verbose_name="implant sticker (photo)",
                    ),
                ),
                (
                    "insertion_torque",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="insertion torque (Ncm)"
                    ),
                ),
                (
                    "isq",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="ISQ",
                    ),
                ),
                (
                    "subcrestal",
                    models.BooleanField(
                        default=False, verbose_name="implant subcrestal"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "implant_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("placed", "Placed - healing"),
                            ("uncovered", "Uncovered (2nd stage)"),
                            ("impression", "Impression / scan taken"),
                            ("loaded", "Loaded (final prosthesis)"),
                            ("failed", "Failed / removed"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="implant status",
                    ),
                ),
                (
                    "uncovered_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="uncovered on"
                    ),
                ),
                (
                    "impression_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="impression / scan on"
                    ),
                ),
                (
                    "loaded_on",
                    models.DateField(blank=True, null=True, verbose_name="loaded on"),
                ),
                (
                    "failed_on",
                    models.DateField(blank=True, null=True, verbose_name="failed on"),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="failure reason"
                    ),
                ),
                (
                    "implant_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sites",
                        to="surgery.implantsystem",
                        verbose_name="implant type",
                    ),
                ),
                (
                    "surgery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="surgery.surgery",
                    ),
                ),
            ],
            options={
                "verbose_name": "surgical site / implant",
                "verbose_name_plural": "surgical sites / implants",
                "ordering": ["surgery", "tooth"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("surgery", "tooth"), name="unique_tooth_per_surgery"
                    )
                ],
            },
        ),
    ]
