# Generated by Django 5.2.17 on 2026-09-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0004_dentist_arabic_name"),
        ("surgery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgerysite",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                help_text="Operator 2 works on other teeth than operator 1. Empty: operator 1.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operated_sites",
                to="dentists.dentist",
                verbose_name="operator of this tooth",
            ),
        ),
        migrations.AlterField(
            model_name="surgery",
            name="operator_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surgeries_as_op2",
                to="dentists.dentist",
                verbose_name="operator 2 (other teeth)",
            ),
        ),
    ]
