# Generated by Django 5.2.17 on 2026-09-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_implants_from_stock"),
        ("surgery", "0002_operators"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgerysite",
            name="implant_stock_item",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="stock.stockitem",
                verbose_name="implant from stock",
            ),
        ),
        migrations.AddField(
            model_name="surgerysite",
            name="stock_movement",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                help_text="The implant taken out of stock for this tooth.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surgery_site",
                to="stock.stockmovement",
            ),
        ),
    ]
