# Generated by Django 5.2.17 on 2026-09-26 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0009_lab_cycle_shades_days"),
        ("dentists", "0004_dentist_arabic_name"),
        ("patients", "0006_fill_dates_and_governorate_codes"),
        ("surgery", "0003_implants_from_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prosthesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("single", "Single crown on implant"),
                            ("bridge", "Bridge on implants"),
                            ("full_fixed", "Full arch - fixed (All-on-X / hybrid)"),
                            ("overdenture", "Full arch - overdenture (removable)"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="prosthesis",
                    ),
                ),
                (
                    "jaw",
                    models.CharField(
                        blank=True,
                        choices=[("upper", "Upper"), ("lower", "Lower")],
                        max_length=10,
                        verbose_name="jaw",
                    ),
                ),
                (
                    "teeth",
                    models.CharField(
                        blank=True,
                        help_text="Every tooth of the bridge, e.g. 34-37. Teeth without an implant are pontics.",
                        max_length=120,
                        verbose_name="teeth it replaces (units)",
                    ),
                ),
                (
                    "retention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("screw", "Screw-retained"),
                            ("cement", "Cement-retained"),
                            ("locator", "Locators / attachments"),
                            ("bar", "Bar"),
                            ("ball", "Ball attachments"),
                        ],
                        max_length=20,
                        verbose_name="retention",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("zirconia", "Zirconia"),
                            ("pfm", "Porcelain fused to metal"),
                            ("emax", "Lithium disilicate (e.max)"),
                            ("pmma", "PMMA"),
                            ("acrylic_bar", "Acrylic teeth on a titanium bar"),
                            ("acrylic", "Acrylic denture"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="material",
                    ),
                ),
                (
                    "is_temporary",
                    models.BooleanField(
                        default=False,
                        help_text="A temporary does not mark the implants as loaded.",
                        verbose_name="temporary",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("impression", "Impression / scan taken"),
                            ("try_in", "Try-in"),
                            ("delivered", "Delivered"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="stage",
                    ),
                ),
                (
                    "delivered_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="delivered on"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prostheses",
                        to="dentists.dentist",
                        verbose_name="dentist",
                    ),
                ),
                (
                    "implants",
                    models.ManyToManyField(
                        related_name="prostheses",
                        to="surgery.surgerysite",
                        verbose_name="on the implants",
                    ),
                ),
                (
                    "lab_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prostheses",
                        to="clinical.labrequest",
                        verbose_name="lab request",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prostheses",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "implant prosthesis",
                "verbose_name_plural": "implant prostheses",
                "ordering": ["-created_at"],
            },
        ),
    ]
