# Generated by Django 5.2.17 on 2026-09-30 08:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0006_specialty_and_title"),
        ("surgery", "0004_prostheses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                (
                    "ticked",
                    models.JSONField(blank=True, default=list, verbose_name="done"),
                ),
                (
                    "torque_ncm",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(60)],
                        verbose_name="torque (Ncm)",
                    ),
                ),
                (
                    "shade",
                    models.CharField(blank=True, max_length=30, verbose_name="shade"),
                ),
                (
                    "follow_up_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="next check on"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dentists.dentist",
                        verbose_name="dentist",
                    ),
                ),
                (
                    "prosthesis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_check",
                        to="surgery.prosthesis",
                        verbose_name="prosthesis",
                    ),
                ),
            ],
            options={
                "verbose_name": "delivery checklist",
                "verbose_name_plural": "delivery checklists",
            },
        ),
    ]
