# Generated by Django 5.2.17 on 2026-09-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surgery", "0005_delivery_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgery",
            name="pontics",
            field=models.CharField(
                blank=True,
                help_text="The teeth of the planned bridge or full arch with no implant under them (e.g. 15, 25): the chart shows them as pontics, not missing.",
                max_length=120,
                verbose_name="pontics",
            ),
        ),
        migrations.AlterField(
            model_name="surgerysite",
            name="implant_diameter",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="implant diameter (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="surgerysite",
            name="implant_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="implant length (mm)",
            ),
        ),
    ]
