# Generated by Django 5.2.17 on 2026-10-05 17:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0015_treatmentsteptype_implant_record_and_more"),
        ("dentists", "0007_signatures"),
        ("patients", "0013_remove_patient_patient_one_id_per_place_and_more"),
        ("surgery", "0006_implant_sizes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImplantComplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "found_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="found on",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("mucositis", "Peri-implant mucositis"),
                            ("peri_implantitis", "Peri-implantitis"),
                            ("infection", "Early infection of the site"),
                            ("bone_loss", "Marginal bone loss"),
                            ("recession", "Soft tissue recession"),
                            ("fistula", "Fistula / abscess"),
                            ("bleeding", "Bleeding"),
                            ("hematoma", "Hematoma / swelling"),
                            ("dehiscence", "Wound dehiscence"),
                            ("membrane_exposure", "Membrane or graft exposure"),
                            ("graft_loss", "Bone graft lost"),
                            ("sinus_perforation", "Sinus membrane perforation"),
                            ("oroantral", "Oroantral communication"),
                            ("sinusitis", "Sinusitis"),
                            ("adjacent_tooth", "Damage to the next tooth"),
                            ("plate_fracture", "Fracture of the bone plate"),
                            ("no_stability", "No primary stability"),
                            ("malposition", "Implant malposition"),
                            ("paresthesia", "Paresthesia (tingling, pins and needles)"),
                            ("hypoesthesia", "Hypoesthesia (less feeling)"),
                            ("anesthesia", "Anesthesia (no feeling, numbness)"),
                            ("dysesthesia", "Dysesthesia (painful feeling)"),
                            (
                                "screw_loosening",
                                "Abutment / prosthetic screw loosening",
                            ),
                            ("screw_fracture", "Screw fracture"),
                            ("abutment_fracture", "Abutment fracture"),
                            ("implant_fracture", "Implant fracture"),
                            ("chipping", "Veneer chipping / fracture"),
                            ("framework_fracture", "Framework fracture"),
                            ("decementation", "Loss of retention (decementation)"),
                            (
                                "attachment_wear",
                                "Attachment / insert wear (overdenture)",
                            ),
                            ("occlusion", "Occlusal problem / overload"),
                            ("food_impaction", "Food impaction / open contact"),
                            ("grey_show", "Grey showing through the gum"),
                            ("papilla_loss", "Papilla loss / black triangle"),
                            ("esthetic_other", "Other esthetic problem"),
                            (
                                "early_failure",
                                "Early failure (no osseointegration, before loading)",
                            ),
                            ("late_failure", "Late failure (after loading)"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="complication",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("biological", "Biological (tissues around the implant)"),
                            ("surgical", "Surgical (during or after the surgery)"),
                            ("nerve", "Nerve injury (sensory)"),
                            ("mechanical", "Mechanical (implant and its parts)"),
                            ("prosthetic", "Technical (the prosthesis)"),
                            ("esthetic", "Esthetic"),
                            ("failure", "Implant failure"),
                        ],
                        db_index=True,
                        editable=False,
                        max_length=12,
                        verbose_name="group",
                    ),
                ),
                (
                    "timing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("during", "During the surgery"),
                            ("healing", "While healing (before loading)"),
                            ("loaded", "After loading"),
                        ],
                        help_text="Empty: found from the dates of the surgery and the loading.",
                        max_length=8,
                        verbose_name="when it showed",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        default="moderate",
                        max_length=8,
                        verbose_name="severity",
                    ),
                ),
                (
                    "signs",
                    models.TextField(
                        blank=True, verbose_name="signs and what the patient feels"
                    ),
                ),
                (
                    "cause",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="likely cause"
                    ),
                ),
                (
                    "nerve",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ian", "Inferior alveolar nerve"),
                            ("mental", "Mental nerve"),
                            ("lingual", "Lingual nerve"),
                            ("infraorbital", "Infraorbital nerve"),
                            ("nasopalatine", "Nasopalatine nerve"),
                            ("other", "Other"),
                        ],
                        max_length=14,
                        verbose_name="nerve",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("right", "Right"),
                            ("left", "Left"),
                            ("both", "Both"),
                        ],
                        max_length=6,
                        verbose_name="side",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="area felt (lip, chin, tongue, cheek...)",
                    ),
                ),
                (
                    "sensory_test",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="sensory tests (two points, brush, pin, hot / cold)",
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("watch", "Watched only"),
                            (
                                "medicines",
                                "Medicines (antibiotic, analgesic, steroid, vitamin B...)",
                            ),
                            ("cleaning", "Non-surgical cleaning / debridement"),
                            ("surgical", "Surgical treatment"),
                            ("regenerative", "Regenerative surgery (graft / membrane)"),
                            ("retighten", "Screw tightened again"),
                            ("part_replaced", "Part replaced (screw / abutment)"),
                            ("prosthesis", "Prosthesis repaired or remade"),
                            ("removed", "Implant removed"),
                            ("backed_out", "Implant backed out a little"),
                            ("other", "Other"),
                        ],
                        max_length=14,
                        verbose_name="treatment",
                    ),
                ),
                (
                    "treatment_notes",
                    models.TextField(blank=True, verbose_name="treatment details"),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("open", "Still being followed"),
                            ("improving", "Improving"),
                            ("resolved", "Resolved"),
                            ("persistent", "Persistent / permanent"),
                            ("implant_lost", "Implant lost"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=14,
                        verbose_name="outcome",
                    ),
                ),
                (
                    "resolved_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="resolved / ended on"
                    ),
                ),
                (
                    "next_check",
                    models.DateField(blank=True, null=True, verbose_name="next check"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="notes for the follow-up"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implant_complications",
                        to="dentists.dentist",
                        verbose_name="found by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implant_complications",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complications",
                        to="surgery.surgerysite",
                        verbose_name="implant",
                    ),
                ),
                (
                    "treatment_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implant_complications",
                        to="clinical.treatmentstep",
                        verbose_name="treatment step",
                    ),
                ),
            ],
            options={
                "verbose_name": "implant complication",
                "verbose_name_plural": "implant complications",
                "ordering": ["-found_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ImplantFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "checked_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="date of the check",
                    ),
                ),
                (
                    "probing_depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="deepest probing (mm)",
                    ),
                ),
                (
                    "bleeding",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="bleeding on probing"
                    ),
                ),
                (
                    "suppuration",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="suppuration (pus)"
                    ),
                ),
                (
                    "mobility",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="mobility of the implant"
                    ),
                ),
                (
                    "plaque",
                    models.BooleanField(blank=True, null=True, verbose_name="plaque"),
                ),
                (
                    "keratinized_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="keratinized mucosa (mm)",
                    ),
                ),
                (
                    "bone_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="From the bone level at the loading.",
                        max_digits=3,
                        null=True,
                        verbose_name="marginal bone loss on the X-ray (mm)",
                    ),
                ),
                (
                    "xray_taken",
                    models.BooleanField(
                        default=False, verbose_name="periapical X-ray taken"
                    ),
                ),
                (
                    "isq",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="ISQ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("health", "Peri-implant health"),
                            ("mucositis", "Peri-implant mucositis"),
                            ("peri_implantitis", "Peri-implantitis"),
                            ("soft_deficiency", "Soft or hard tissue deficiency"),
                            ("failed", "Failed (mobile / lost)"),
                        ],
                        help_text="Empty: found from the findings.",
                        max_length=20,
                        verbose_name="tissues around the implant",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "next_check",
                    models.DateField(blank=True, null=True, verbose_name="next check"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implant_checks",
                        to="dentists.dentist",
                        verbose_name="dentist",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implant_follow_ups",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="surgery.surgerysite",
                        verbose_name="implant",
                    ),
                ),
                (
                    "treatment_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implant_follow_ups",
                        to="clinical.treatmentstep",
                        verbose_name="treatment step",
                    ),
                ),
            ],
            options={
                "verbose_name": "implant follow-up",
                "verbose_name_plural": "implant follow-ups",
                "ordering": ["-checked_on", "-pk"],
            },
        ),
    ]
