# Generated by Django 5.2.17 on 2026-10-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surgery", "0007_implantcomplication_implantfollowup"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgery",
            name="sutured",
            field=models.BooleanField(
                blank=True,
                help_text="Yes: the size, the material and the technique are needed.",
                null=True,
                verbose_name="sutured",
            ),
        ),
        migrations.AlterField(
            model_name="surgery",
            name="block_donor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chin", "Chin"),
                    ("ramus", "Ramus"),
                    ("tuberosity", "Tuberosity"),
                    ("other", "Other"),
                ],
                max_length=40,
                verbose_name="block donor site",
            ),
        ),
        migrations.AlterField(
            model_name="surgery",
            name="cut_by",
            field=models.CharField(
                blank=True,
                choices=[("disc", "Disc"), ("piezo", "Piezo")],
                max_length=40,
                verbose_name="cut by",
            ),
        ),
        migrations.AlterField(
            model_name="surgery",
            name="soft_tissue_graft",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fgg", "Free gingival graft"),
                    ("ctg", "Connective tissue graft"),
                    ("other", "Other soft tissue graft"),
                ],
                max_length=40,
                verbose_name="soft tissue graft",
            ),
        ),
        migrations.AlterField(
            model_name="surgery",
            name="suture_material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vicryl", "Vicryl"),
                    ("prolene", "Prolene"),
                    ("silk", "Silk"),
                    ("other", "Other"),
                ],
                max_length=40,
                verbose_name="suture material",
            ),
        ),
        migrations.AlterField(
            model_name="surgery",
            name="suture_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3-0", "3-0"),
                    ("4-0", "4-0"),
                    ("5-0", "5-0"),
                    ("6-0", "6-0"),
                    ("7-0", "7-0"),
                ],
                max_length=40,
                verbose_name="suture size",
            ),
        ),
        migrations.AlterField(
            model_name="surgery",
            name="temporary",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("healing_collar", "Healing collar"),
                    ("custom_healing", "Customized healing collar"),
                    ("crown", "Crown"),
                    ("maryland", "Maryland bridge"),
                    ("bridge_on_teeth", "Bridge on teeth"),
                    ("denture_fiber", "Denture with glass fiber"),
                ],
                max_length=40,
                verbose_name="temporary",
            ),
        ),
        migrations.CreateModel(
            name="SurgeryOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("block_donor", "Block donor site"),
                            ("cut_by", "Cut by"),
                            ("soft_tissue_graft", "Soft tissue graft"),
                            ("suture_size", "Suture size"),
                            ("suture_material", "Suture material"),
                            ("temporary", "Temporary"),
                            (
                                "bone_material",
                                "Bone graft material / brand (suggestions)",
                            ),
                            ("sinus_approach", "Sinus approach (suggestions)"),
                            (
                                "sinus_fill_material",
                                "Sinus fill material (suggestions)",
                            ),
                            ("membrane_material", "Membrane material (suggestions)"),
                            ("membrane_company", "Membrane company (suggestions)"),
                            ("tacks_company", "Tacks company (suggestions)"),
                            (
                                "soft_tissue_technique",
                                "Soft tissue technique (suggestions)",
                            ),
                            ("suture_technique", "Suture technique (suggestions)"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="list",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Kept on the surgery charts. Empty: made from the English name.",
                        max_length=20,
                        verbose_name="code",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="name (English)"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="name (Arabic)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "surgery chart list item",
                "verbose_name_plural": "surgery chart lists",
                "ordering": ["kind", "sort_order", "name_en"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "code"), name="one_code_per_surgery_list"
                    )
                ],
            },
        ),
    ]
