# Generated by Django 5.2.17 on 2026-10-05 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_clinicsettings_hba1c_recheck_days_and_more"),
        ("dentists", "0008_dentist_show_in_lists_dentist_work_time_and_more"),
        ("surgery", "0008_surgery_sutured_alter_surgery_block_donor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DaySupervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="date",
                    ),
                ),
                (
                    "from_time",
                    models.TimeField(blank=True, null=True, verbose_name="from"),
                ),
                ("to_time", models.TimeField(blank=True, null=True, verbose_name="to")),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "written_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="written at"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="days_supervised",
                        to="dentists.dentist",
                        verbose_name="supervisor",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="written by",
                    ),
                ),
            ],
            options={
                "verbose_name": "supervisor of the surgery day",
                "verbose_name_plural": "supervisors of the surgery days",
                "ordering": ["date", "from_time", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "date", "supervisor"),
                        name="one_day_supervisor_row",
                    )
                ],
            },
        ),
    ]
