# Generated by Django 5.2.17 on 2026-09-25 07:50

import apps.academy.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "full_name",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="full name"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        error_messages={
                            "unique": "A candidate with this ID number is already registered."
                        },
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="national ID / passport no.",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        error_messages={
                            "unique": "This mobile number is already registered for another candidate."
                        },
                        max_length=20,
                        unique=True,
                        verbose_name="mobile 1 (primary)",
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="mobile 2"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "university",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="university"
                    ),
                ),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="graduation year"
                    ),
                ),
                (
                    "syndicate_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="syndicate registration no.",
                    ),
                ),
                (
                    "id_scan",
                    models.FileField(
                        blank=True,
                        upload_to=apps.academy.models.candidate_id_path,
                        verbose_name="ID scan",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="system login (if intern)",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidate",
                "verbose_name_plural": "candidates",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="course name")),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="code / batch"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="start date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="course fee",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="capacity"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="open")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="core.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "enrolled_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="enrollment date",
                    ),
                ),
                (
                    "agreed_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="agreed fee",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="discount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Studying"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="academy.candidate",
                        verbose_name="candidate",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="academy.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "enrollment",
                "verbose_name_plural": "enrollments",
                "ordering": ["-enrolled_on"],
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="installment no."),
                ),
                ("due_date", models.DateField(db_index=True, verbose_name="due date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="amount",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="academy.enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "installment",
                "verbose_name_plural": "installments",
                "ordering": ["due_date", "number"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="receipt number",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "paid_on",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="payment date",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Visa / card"),
                            ("instapay", "InstaPay"),
                            ("wallet", "Mobile wallet (Vodafone Cash...)"),
                            ("bank", "Bank transfer"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Transfer / InstaPay / wallet reference number, if any.",
                        max_length=100,
                        verbose_name="transaction reference",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="academy.enrollment",
                        verbose_name="enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-paid_on", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("candidate", "course"), name="unique_enrollment"
            ),
        ),
    ]
