# Generated by Django 5.2.17 on 2026-09-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="certificate_name",
            field=models.CharField(
                blank=True,
                help_text="First, middle and last name exactly as it should appear on the certificate.",
                max_length=150,
                verbose_name="name for certificate (English)",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="code",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "Another candidate already has this code."},
                max_length=20,
                null=True,
                unique=True,
                verbose_name="candidate code",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="facebook",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Facebook account"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Instagram account"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="linkedin",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="LinkedIn account"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="nationality"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="referral_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="patients.referralsource",
                verbose_name="how did they hear about us",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="whatsapp",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="WhatsApp number"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="implants_required",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Used to show how many implants are still remaining for each candidate.",
                verbose_name="implants each candidate should place",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="implants_required_override",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="implants required (if different from the course)",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="proof",
            field=models.FileField(
                blank=True,
                help_text="Photo of the transfer / deposit receipt.",
                upload_to="candidates/payments/%Y/%m/",
                verbose_name="payment scan",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="university",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="graduated from (university)"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Visa / card"),
                    ("instapay", "InstaPay"),
                    ("wallet", "Mobile wallet (Vodafone Cash...)"),
                    ("bank", "Bank transfer"),
                    ("bank_deposit", "Bank deposit"),
                    ("cheque", "Cheque"),
                ],
                max_length=20,
                verbose_name="payment method",
            ),
        ),
    ]
