# Generated by Django 5.2.17 on 2026-09-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0002_move_people_to_dentists"),
        ("academy", "0002_candidate_birth_date_candidate_certificate_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="user",
        ),
    ]
