# Generated by Django 5.2.17 on 2026-09-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0003_remove_candidate_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="study_mode",
            field=models.CharField(
                choices=[("offline", "In the academy (offline)"), ("online", "Online")],
                default="offline",
                max_length=10,
                verbose_name="attends",
            ),
        ),
    ]
