# Generated by Django 5.2.17 on 2026-09-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0004_enrollment_study_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Visa / card"),
                    ("instapay", "InstaPay"),
                    ("wallet", "Mobile wallet (Vodafone Cash...)"),
                    ("bank", "Bank transfer"),
                    ("bank_deposit", "Bank deposit"),
                    ("cheque", "Cheque"),
                    ("fawry", "Fawry POS machine"),
                ],
                max_length=20,
                verbose_name="payment method",
            ),
        ),
    ]
