# Generated by Django 5.2.17 on 2026-09-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_fawry_method"),
        ("billing", "0005_places_and_machines"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="fawry_machine",
            field=models.ForeignKey(
                blank=True,
                help_text="For card payments: the machine that took it.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_payments",
                to="billing.fawrymachine",
                verbose_name="Fawry machine",
            ),
        ),
    ]
