# Generated by Django 5.2.17 on 2026-10-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0006_places_and_machines"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-batch_number", "-start_date", "name"],
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="batch_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Batch 1, 2, 3...: the candidates are listed by it.",
                null=True,
                verbose_name="batch number",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="kind",
            field=models.CharField(
                choices=[
                    ("regular", "Regular course (a batch)"),
                    ("private", "Private course"),
                ],
                default="regular",
                help_text="A private course is for one candidate (or a few) at their own times.",
                max_length=10,
                verbose_name="regular or private",
            ),
        ),
    ]
