DATE_FORMAT = "j M Y"
TIME_FORMAT = "g:i A"
DATETIME_FORMAT = "j M Y, g:i A"
YEAR_MONTH_FORMAT = "F Y"
MONTH_DAY_FORMAT = "j F"
SHORT_DATE_FORMAT = "d/m/Y"
SHORT_DATETIME_FORMAT = "d/m/Y g:i A"
FIRST_DAY_OF_WEEK = 6
DATE_INPUT_FORMATS = ["%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y"]
TIME_INPUT_FORMATS = ["%H:%M", "%H:%M:%S", "%I:%M %p"]
DATETIME_INPUT_FORMATS = ["%Y-%m-%dT%H:%M", "%Y-%m-%d %H:%M", "%Y-%m-%d %H:%M:%S", "%d/%m/%Y %H:%M"]
DECIMAL_SEPARATOR = "."
THOUSAND_SEPARATOR = ","
NUMBER_GROUPING = 3
