# Generated by Django 5.2.17 on 2026-09-25 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="dentist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="dentists.dentist",
                verbose_name="dentist",
            ),
        ),
        migrations.AddField(
            model_name="roomshift",
            name="day_type",
            field=models.CharField(
                choices=[("regular", "Regular day"), ("surgery", "Surgery day")],
                default="regular",
                max_length=10,
                verbose_name="day type",
            ),
        ),
        migrations.AddField(
            model_name="roomshift",
            name="dentist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room_shifts",
                to="dentists.dentist",
                verbose_name="dentist",
            ),
        ),
        migrations.AddField(
            model_name="roomshift",
            name="supervisor_dentist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_shifts",
                to="dentists.dentist",
                verbose_name="supervisor",
            ),
        ),
        migrations.AlterField(
            model_name="roomshift",
            name="intern",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room_shifts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="intern doctor",
            ),
        ),
    ]
