# Generated by Django 5.2.17 on 2026-09-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_dentist_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="name (English)"
            ),
        ),
    ]
