# Generated by Django 5.2.17 on 2026-09-25 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_call_lists"),
        ("scheduling", "0004_room_name_en"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("confirmation", "Booking confirmation"),
                            ("reminder", "Appointment reminder"),
                            ("no_show", "Missed appointment"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="message",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Words in braces are filled in: {patient} {day} {date} {time} {dentist} {clinic} {phone} {address}",
                        verbose_name="text",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "WhatsApp message",
                "verbose_name_plural": "WhatsApp messages",
                "ordering": ["kind"],
            },
        ),
        migrations.CreateModel(
            name="SentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("confirmation", "Booking confirmation"),
                            ("reminder", "Appointment reminder"),
                            ("no_show", "Missed appointment"),
                        ],
                        max_length=20,
                        verbose_name="message",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="mobile")),
                ("text", models.TextField(verbose_name="text")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="sent at"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="patients.patient",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp message sent",
                "verbose_name_plural": "WhatsApp messages sent",
                "ordering": ["-sent_at"],
            },
        ),
    ]
