# Generated by Django 5.2.17 on 2026-09-25 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0004_enrollment_study_mode"),
        ("patients", "0005_out_dates_governorates_documents"),
        ("scheduling", "0005_whatsapp_messages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["branch", "is_extra", "sort_order", "name"],
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
            },
        ),
        migrations.AddField(
            model_name="room",
            name="is_extra",
            field=models.BooleanField(
                default=False,
                help_text="Opened only on busy days: shown on the schedules only on the days it has a shift.",
                verbose_name="extra room",
            ),
        ),
        migrations.AddField(
            model_name="sentmessage",
            name="installment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="academy.installment",
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="kind",
            field=models.CharField(
                choices=[
                    ("confirmation", "Booking confirmation"),
                    ("reminder", "Appointment reminder"),
                    ("no_show", "Missed appointment"),
                    ("installment", "Installment reminder"),
                ],
                max_length=20,
                unique=True,
                verbose_name="message",
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="text",
            field=models.TextField(
                help_text="Words in braces are filled in. Appointments: {patient} {day} {date} {time} {dentist} {clinic} {phone} {address}. Installments: {candidate} {course} {amount} {date} {balance} {clinic} {phone}",
                verbose_name="text",
            ),
        ),
        migrations.AlterField(
            model_name="sentmessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("confirmation", "Booking confirmation"),
                    ("reminder", "Appointment reminder"),
                    ("no_show", "Missed appointment"),
                    ("installment", "Installment reminder"),
                ],
                max_length=20,
                verbose_name="message",
            ),
        ),
        migrations.AlterField(
            model_name="sentmessage",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="patients.patient",
            ),
        ),
    ]
