# Generated by Django 5.2.17 on 2026-09-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0006_extra_rooms_and_installment_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reschedule_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="why it was moved"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="rescheduled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="moved on"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="rescheduled_from",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="moved from"
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="kind",
            field=models.CharField(
                choices=[
                    ("confirmation", "Booking confirmation"),
                    ("reminder", "Appointment reminder"),
                    ("no_show", "Missed appointment"),
                    ("rescheduled", "Appointment moved"),
                    ("installment", "Installment reminder"),
                ],
                max_length=20,
                unique=True,
                verbose_name="message",
            ),
        ),
        migrations.AlterField(
            model_name="sentmessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("confirmation", "Booking confirmation"),
                    ("reminder", "Appointment reminder"),
                    ("no_show", "Missed appointment"),
                    ("rescheduled", "Appointment moved"),
                    ("installment", "Installment reminder"),
                ],
                max_length=20,
                verbose_name="message",
            ),
        ),
    ]
