# Generated by Django 5.2.17 on 2026-09-25 23:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0008_treatment_category"),
        ("dentists", "0004_dentist_arabic_name"),
        ("patients", "0006_fill_dates_and_governorate_codes"),
        ("scheduling", "0007_reschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "teeth",
                    models.CharField(blank=True, max_length=100, verbose_name="teeth"),
                ),
                (
                    "minutes",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="time needed (minutes)"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("main", "Main list"),
                            (
                                "backup",
                                "Backup list (call if a main patient cannot come)",
                            ),
                        ],
                        default="main",
                        max_length=10,
                        verbose_name="list",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 - First (most important)"),
                            (2, "2 - Second"),
                            (3, "3 - Third"),
                            (4, "4 - Fourth"),
                            (5, "5 - Fifth"),
                        ],
                        default=2,
                        verbose_name="priority",
                    ),
                ),
                (
                    "wanted_from",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="from"
                    ),
                ),
                (
                    "wanted_to",
                    models.DateField(blank=True, null=True, verbose_name="to"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="notes for the supervisor and the reception",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Waiting for the supervisor"),
                            ("approved", "Approved: reception to call"),
                            ("booked", "Booked"),
                            ("cannot_come", "Patient cannot come"),
                            ("rejected", "Not approved"),
                            ("cancelled", "Cancelled by the dentist"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "approved_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="time given (minutes)"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="decided at"
                    ),
                ),
                (
                    "decision_note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="supervisor's note"
                    ),
                ),
                (
                    "reception_note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="reception's note"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_requests",
                        to="scheduling.appointment",
                        verbose_name="appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="decided by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_requests",
                        to="dentists.dentist",
                        verbose_name="dentist",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dentist_requests",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "step_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinical.treatmentsteptype",
                        verbose_name="step to do",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient asked by a dentist",
                "verbose_name_plural": "patients asked by dentists",
                "ordering": ["dentist", "-kind", "priority", "created_at"],
            },
        ),
    ]
