# Generated by Django 5.2.17 on 2026-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0008_dentist_patient_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="no_follow_up",
            field=models.BooleanField(
                default=False,
                help_text="Ticked by the reception when the patient left and needs no other appointment.",
                verbose_name="no next visit needed",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Booked"),
                    ("confirmed", "Confirmed by phone"),
                    ("arrived", "Arrived - waiting"),
                    ("in_room", "In the room"),
                    ("completed", "Left"),
                    ("no_show", "Did not come"),
                    ("cancelled", "Cancelled"),
                    ("late_not_seen", "Came late — not seen"),
                ],
                db_index=True,
                default="scheduled",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
