# Generated by Django 5.2.17 on 2026-09-26 12:21

import django.db.models.deletion
from django.db import migrations, models


def link_procedures(apps, schema_editor):
    """Old appointments: a purpose that starts with a treatment's name becomes that procedure."""
    StepType = apps.get_model("clinical", "TreatmentStepType")
    Appointment = apps.get_model("scheduling", "Appointment")
    names = []
    for step_type in StepType.objects.all():
        for name in (step_type.name_ar, step_type.name_en):
            if name:
                names.append((name, step_type))
    names.sort(key=lambda item: -len(item[0]))  # the longest name first ("Closed sinus lift" before "Sinus lift")
    for appointment in Appointment.objects.filter(procedure__isnull=True).exclude(purpose=""):
        text = appointment.purpose.strip()
        for name, step_type in names:
            if text == name or text.startswith(name + " "):
                appointment.procedure = step_type
                appointment.purpose = text[len(name):].strip()
                appointment.save(update_fields=["procedure", "purpose"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0008_treatment_category"),
        ("dentists", "0004_dentist_arabic_name"),
        ("scheduling", "0009_late_not_seen_follow_up"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="procedure",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown to each person in their own language.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="clinical.treatmentsteptype",
                verbose_name="procedure",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The dentist who asked the reception for this visit.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_appointments",
                to="dentists.dentist",
                verbose_name="asked by (dentist)",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="second_dentist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assisted_appointments",
                to="dentists.dentist",
                verbose_name="second dentist in the room",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="purpose",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="details (teeth, notes)"
            ),
        ),
        migrations.RunPython(link_procedures, migrations.RunPython.noop),
    ]
