# Generated by Django 5.2.17 on 2026-09-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0004_dentist_arabic_name"),
        ("scheduling", "0010_procedure_asked_by_second_dentist"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomshift",
            name="second_dentist",
            field=models.ForeignKey(
                blank=True,
                help_text="Two dentists in the same room, e.g. a candidate with a CIA dentist.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_shifts",
                to="dentists.dentist",
                verbose_name="second dentist in the room",
            ),
        ),
    ]
