# Generated by Django 5.2.17 on 2026-09-26 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0008_treatment_category"),
        ("dentists", "0004_dentist_arabic_name"),
        ("patients", "0006_fill_dates_and_governorate_codes"),
        ("scheduling", "0011_shift_second_dentist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "minutes",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="time needed (minutes)"
                    ),
                ),
                (
                    "wanted_from",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="from"
                    ),
                ),
                (
                    "wanted_to",
                    models.DateField(blank=True, null=True, verbose_name="to"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="e.g. only mornings, can come within 30 minutes",
                        max_length=255,
                        verbose_name="notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for a place"),
                            ("booked", "Booked"),
                            ("removed", "Removed from the list"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waiting_entries",
                        to="scheduling.appointment",
                        verbose_name="appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty if any dentist will do.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waiting_entries",
                        to="dentists.dentist",
                        verbose_name="dentist",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiting_entries",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="clinical.treatmentsteptype",
                        verbose_name="procedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "waiting list entry",
                "verbose_name_plural": "waiting list",
                "ordering": ["created_at"],
            },
        ),
    ]
