# Generated by Django 5.2.17 on 2026-09-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0012_waiting_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="notes_escalated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="supervisor told the visit notes are missing",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="notes_reminded_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="dentist reminded to write the visit notes",
            ),
        ),
    ]
