# Generated by Django 5.2.17 on 2026-09-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0013_visit_notes_reminders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Booked"),
                    ("confirmed", "Confirmed by phone"),
                    ("arrived", "Arrived - waiting"),
                    ("in_room", "In the room"),
                    ("completed", "Left"),
                    ("no_show", "Did not come"),
                    ("cancelled", "Cancelled"),
                    ("late_not_seen", "Came late — not seen"),
                    ("pending", "Waiting for approval (not the dentist's day)"),
                ],
                db_index=True,
                default="scheduled",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
