# Generated by Django 5.2.17 on 2026-09-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0014_pending_bookings"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitingentry",
            name="calls",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="calls"),
        ),
        migrations.AddField(
            model_name="waitingentry",
            name="last_call",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_answer", "No answer"),
                    ("not_that_day", "Cannot come that day"),
                    ("not_interested", "Does not want it any more"),
                ],
                max_length=15,
                verbose_name="last call",
            ),
        ),
        migrations.AddField(
            model_name="waitingentry",
            name="last_call_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="called at"),
        ),
    ]
