# Generated by Django 5.2.17 on 2026-09-28 06:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_reception_sees"),
        ("patients", "0008_patients_per_place"),
        ("scheduling", "0015_waiting_calls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("prescription", "Prescription"),
                            ("instructions", "Post-op instructions"),
                            ("bill", "Bill"),
                            ("report", "Case report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="what",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="The page the reception opens to send it.",
                        max_length=300,
                        verbose_name="page",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="note for the reception",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="asked at"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_requests",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="asked by",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sent by",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp request",
                "verbose_name_plural": "WhatsApp requests",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["branch", "sent_at"],
                        name="scheduling__branch__f27829_idx",
                    )
                ],
            },
        ),
    ]
