# Generated by Django 5.2.17 on 2026-10-01 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0014_speed_indexes"),
        ("core", "0018_speed_indexes"),
        ("dentists", "0006_specialty_and_title"),
        ("patients", "0010_medicalconsult"),
        ("scheduling", "0016_whatsapp_requests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["branch", "scheduled_at"], name="appointment_place_time"
            ),
        ),
    ]
