# Generated by Django 5.2.17 on 2026-10-05 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_clinicsettings_one_device_per_login_and_more"),
        ("patients", "0012_alter_patient_travel_minutes"),
        ("scheduling", "0017_speed_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="For you, e.g. Eid greetings, the new implant offer.",
                        max_length=120,
                        verbose_name="title",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="{patient} is replaced by each one's name; {clinic}, {phone} and {address} by the place's.",
                        verbose_name="message",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="sent to"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp message to many",
                "verbose_name_plural": "WhatsApp messages to many",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("phone", models.CharField(max_length=20, verbose_name="mobile")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                ("skipped", models.BooleanField(default=False, verbose_name="skipped")),
                (
                    "bulk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="scheduling.bulkmessage",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="patients.lead",
                        verbose_name="expected patient",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sent by",
                    ),
                ),
            ],
            options={
                "verbose_name": "person to send to",
                "verbose_name_plural": "people to send to",
                "ordering": ["pk"],
            },
        ),
    ]
