# Generated by Django 5.2.17 on 2026-10-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0018_bulkmessage_bulkrecipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomshift",
            name="day_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular day"),
                    ("preparation", "Preparation day"),
                    ("surgery", "Surgery day"),
                ],
                default="regular",
                max_length=12,
                verbose_name="day type",
            ),
        ),
    ]
