# Generated by Django 5.2.17 on 2026-09-25 07:50

import apps.patients.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="name (English)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_alert",
                    models.BooleanField(
                        default=True,
                        help_text="Highlight in red on the patient file.",
                        verbose_name="show as alert",
                    ),
                ),
            ],
            options={
                "verbose_name": "medical condition",
                "verbose_name_plural": "medical conditions",
                "ordering": ["sort_order", "name_ar"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReferralSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="name (English)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "asks_for_patient",
                    models.BooleanField(
                        default=False,
                        help_text="Tick for sources like 'referred by a patient' so the secretary links the referring patient.",
                        verbose_name="ask for the referring patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral source",
                "verbose_name_plural": "referral sources",
                "ordering": ["sort_order", "name_ar"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="full name"),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="mobile 1"
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="mobile 2"
                    ),
                ),
                (
                    "preferred_phone",
                    models.CharField(
                        choices=[
                            ("primary", "First mobile"),
                            ("secondary", "Second mobile"),
                        ],
                        default="primary",
                        max_length=10,
                        verbose_name="preferred mobile",
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="age"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="city / area"
                    ),
                ),
                (
                    "missing_teeth",
                    models.CharField(
                        choices=[
                            ("single", "Single tooth"),
                            ("multiple", "Multiple teeth"),
                            ("full_arch", "Full arch"),
                            ("both_arches", "Both arches (full mouth)"),
                            ("unknown", "Not sure"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="missing teeth",
                    ),
                ),
                (
                    "missing_teeth_notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="missing teeth details"
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(blank=True, verbose_name="other medical notes"),
                ),
                (
                    "referral_notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="referral details"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("follow_up", "Call back later"),
                            ("booked", "Appointment booked"),
                            ("converted", "Became a patient"),
                            ("not_interested", "Not interested"),
                            ("unreachable", "Unreachable"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "next_call_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="next call"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="core.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "medical_conditions",
                    models.ManyToManyField(
                        blank=True,
                        to="patients.medicalcondition",
                        verbose_name="medical history (as told by the caller)",
                    ),
                ),
            ],
            options={
                "verbose_name": "expected patient",
                "verbose_name_plural": "expected patients (call list)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("called_at", models.DateTimeField(verbose_name="call time")),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("answered", "Answered"),
                            ("no_answer", "No answer"),
                            ("busy", "Busy / closed"),
                            ("wrong_number", "Wrong number"),
                            ("call_back", "Asked to call back"),
                            ("booked", "Booked an appointment"),
                        ],
                        max_length=20,
                        verbose_name="result",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="patients.lead",
                        verbose_name="expected patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "call",
                "verbose_name_plural": "calls",
                "ordering": ["-called_at"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "file_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="file number",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        verbose_name="full name (as on ID)",
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("nid", "Egyptian national ID"),
                            ("passport", "Passport"),
                        ],
                        default="nid",
                        max_length=10,
                        verbose_name="ID type",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        error_messages={
                            "unique": "A patient with this ID number is already registered."
                        },
                        max_length=20,
                        unique=True,
                        verbose_name="national ID / passport no.",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        error_messages={
                            "unique": "This mobile number is already registered for another patient."
                        },
                        max_length=20,
                        unique=True,
                        verbose_name="mobile 1 (primary)",
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="mobile 2"
                    ),
                ),
                (
                    "preferred_phone",
                    models.CharField(
                        choices=[
                            ("primary", "First mobile"),
                            ("secondary", "Second mobile"),
                        ],
                        default="primary",
                        max_length=10,
                        verbose_name="preferred mobile",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="city / area"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="occupation"
                    ),
                ),
                (
                    "missing_teeth",
                    models.CharField(
                        choices=[
                            ("single", "Single tooth"),
                            ("multiple", "Multiple teeth"),
                            ("full_arch", "Full arch"),
                            ("both_arches", "Both arches (full mouth)"),
                            ("unknown", "Not sure"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="missing teeth",
                    ),
                ),
                (
                    "missing_teeth_notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="missing teeth details"
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(blank=True, verbose_name="other medical notes"),
                ),
                (
                    "referral_notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="referral details"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Under treatment"),
                            ("finished", "Treatment finished"),
                            ("inactive", "Stopped / inactive"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "assigned_intern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_patients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsible intern",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients",
                        to="core.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "medical_conditions",
                    models.ManyToManyField(
                        blank=True,
                        to="patients.medicalcondition",
                        verbose_name="medical history (self-reported)",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_patients",
                        to="patients.patient",
                        verbose_name="referred by patient",
                    ),
                ),
                (
                    "referral_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patients.referralsource",
                        verbose_name="who referred you / how did you hear about us",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient",
                "verbose_name_plural": "patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="converted_patient",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_lead",
                to="patients.patient",
                verbose_name="patient file",
            ),
        ),
        migrations.CreateModel(
            name="PatientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("id_front", "ID card - front"),
                            ("id_back", "ID card - back"),
                            ("passport", "Passport"),
                            ("consent", "Signed consent"),
                            ("xray", "X-ray / CBCT"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="document type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.patients.models.patient_document_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient document",
                "verbose_name_plural": "patient documents",
                "ordering": ["kind", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="referral_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patients.referralsource",
                verbose_name="how did they hear about us",
            ),
        ),
        migrations.CreateModel(
            name="PatientRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("relative", "Relative"),
                            ("spouse", "Spouse"),
                            ("parent_child", "Parent / child"),
                            ("sibling", "Brother / sister"),
                            ("friend", "Friend"),
                            ("neighbour", "Neighbour"),
                            ("colleague", "Work colleague"),
                        ],
                        max_length=20,
                        verbose_name="relation",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_from",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "related_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_to",
                        to="patients.patient",
                        verbose_name="related patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient relation",
                "verbose_name_plural": "patient relations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "related_patient"),
                        name="unique_patient_relation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("patient", models.F("related_patient")), _negated=True
                        ),
                        name="relation_not_self",
                    ),
                ],
            },
        ),
    ]
