# Generated by Django 5.2.17 on 2026-09-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="assigned_dentist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_patients",
                to="dentists.dentist",
                verbose_name="responsible dentist",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="governorate",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="governorate"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                max_length=10,
                verbose_name="marital status",
            ),
        ),
    ]
