# Generated by Django 5.2.17 on 2026-09-25 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_language"),
        ("patients", "0003_remove_patient_assigned_intern"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                (
                    "message",
                    models.TextField(
                        blank=True, verbose_name="what to tell the patients"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_lists",
                        to="core.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "list of patients to call",
                "verbose_name_plural": "lists of patients to call",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="why"),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Not called yet"),
                            ("booked", "Booked an appointment"),
                            ("call_back", "Call again later"),
                            ("not_interested", "Not interested now"),
                            ("no_answer", "No answer"),
                            ("wrong_number", "Wrong / closed number"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="result",
                    ),
                ),
                (
                    "response",
                    models.TextField(blank=True, verbose_name="patient's answer"),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="calls made"
                    ),
                ),
                (
                    "called_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last call"
                    ),
                ),
                (
                    "call_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="patients.calllist",
                    ),
                ),
                (
                    "called_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="called by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_entries",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient to call",
                "verbose_name_plural": "patients to call",
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("call_list", "patient"),
                        name="unique_patient_per_call_list",
                    )
                ],
            },
        ),
    ]
