# Generated by Django 5.2.17 on 2026-09-25 18:29

import apps.patients.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_call_lists"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="name (English)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "reason for being out",
                "verbose_name_plural": "reasons for being out",
                "ordering": ["sort_order", "name_ar"],
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="lead",
            options={
                "ordering": ["first_call_on", "created_at"],
                "verbose_name": "expected patient",
                "verbose_name_plural": "expected patients (call list)",
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="first_call_on",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.localdate,
                help_text="Today by itself. Change it only when typing in older calls.",
                verbose_name="first called on",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="out_notes",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="details of why out"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="registered_on",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.localdate,
                help_text="Today by itself. When typing in old paper files, write the date the file was opened.",
                verbose_name="file opened on",
            ),
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="original",
            field=models.FileField(
                blank=True,
                help_text="The picture as it was uploaded, before the card was cut out.",
                upload_to=apps.patients.models.patient_document_path,
                verbose_name="original scan",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Cairo"),
                    ("02", "Alexandria"),
                    ("03", "Port Said"),
                    ("04", "Suez"),
                    ("11", "Damietta"),
                    ("12", "Dakahlia"),
                    ("13", "Sharqia"),
                    ("14", "Qalyubia"),
                    ("15", "Kafr El Sheikh"),
                    ("16", "Gharbia"),
                    ("17", "Monufia"),
                    ("18", "Beheira"),
                    ("19", "Ismailia"),
                    ("21", "Giza"),
                    ("22", "Beni Suef"),
                    ("23", "Fayoum"),
                    ("24", "Minya"),
                    ("25", "Asyut"),
                    ("26", "Sohag"),
                    ("27", "Qena"),
                    ("28", "Aswan"),
                    ("29", "Luxor"),
                    ("31", "Red Sea"),
                    ("32", "New Valley"),
                    ("33", "Matrouh"),
                    ("34", "North Sinai"),
                    ("35", "South Sinai"),
                    ("88", "Outside Egypt"),
                ],
                max_length=60,
                verbose_name="governorate",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Under treatment"),
                    ("finished", "Treatment finished"),
                    ("inactive", "Stopped / inactive"),
                    ("out", "Out"),
                ],
                default="active",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="out_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="patients.outreason",
                verbose_name="why out",
            ),
        ),
    ]
