# Generated by Django 5.2.17 on 2026-09-27 15:29

import apps.patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_fill_dates_and_governorate_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdocument",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="For a CBCT (DICOM files, too big to upload): the folder on the server or the viewer link from the centre, e.g. \\\\CIA-SERVER\\CBCT\\CIA-00020 or https://…",
                max_length=500,
                verbose_name="where the full scan is kept",
            ),
        ),
        migrations.AlterField(
            model_name="patientdocument",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="A picture or PDF: the X-ray, the CBCT report or a few screenshots of it.",
                upload_to=apps.patients.models.patient_document_path,
                verbose_name="file",
            ),
        ),
    ]
