# Generated by Django 5.2.17 on 2026-09-28 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_backup_runs"),
        ("dentists", "0005_places"),
        ("patients", "0007_document_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="transferred_to",
            field=models.ForeignKey(
                blank=True,
                help_text="The new file opened when the patient moved to another place.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferred_from",
                to="patients.patient",
                verbose_name="moved to the file",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="national_id",
            field=models.CharField(
                db_index=True, max_length=20, verbose_name="national ID / passport no."
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_primary",
            field=models.CharField(
                db_index=True, max_length=20, verbose_name="mobile 1 (primary)"
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("branch", "national_id"), name="patient_one_id_per_place"
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("branch", "phone_primary"), name="patient_one_mobile_per_place"
            ),
        ),
    ]
