# Generated by Django 5.2.17 on 2026-09-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0006_specialty_and_title"),
        ("patients", "0008_patients_per_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="brought_by",
            field=models.ForeignKey(
                blank=True,
                help_text="A doctor who brought his own patient to the clinic. His work on this patient is paid as his own patient (e.g. 40%); every other patient is the clinic's (e.g. 30%).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brought_patients",
                to="dentists.dentist",
                verbose_name="the doctor's own patient (brought by)",
            ),
        ),
    ]
