# Generated by Django 5.2.17 on 2026-09-30 08:56

import apps.patients.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_round10_options"),
        ("dentists", "0006_specialty_and_title"),
        ("patients", "0009_patient_brought_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalConsult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for the physician's answer"),
                            ("answered", "Answered"),
                            (
                                "not_needed",
                                "No consultation needed (the dentist's decision)",
                            ),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "reasons",
                    models.CharField(blank=True, max_length=200, verbose_name="why"),
                ),
                (
                    "findings",
                    models.TextField(
                        blank=True,
                        help_text="Written in the letter: the diseases, the medicines and the readings.",
                        verbose_name="medical history and readings",
                    ),
                ),
                (
                    "physician",
                    models.CharField(
                        blank=True,
                        help_text="The name, if the patient knows it.",
                        max_length=120,
                        verbose_name="to the physician",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        default="Internal medicine",
                        max_length=80,
                        verbose_name="specialty",
                    ),
                ),
                (
                    "procedures",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="planned procedure"
                    ),
                ),
                (
                    "procedure_details",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 4 implants in the lower jaw with a bone graft",
                        max_length=255,
                        verbose_name="details of the procedure",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        default="About 1 hour",
                        max_length=60,
                        verbose_name="expected duration",
                    ),
                ),
                (
                    "bleeding",
                    models.CharField(
                        choices=[("minor", "Minor"), ("moderate", "Moderate")],
                        default="minor",
                        max_length=10,
                        verbose_name="expected bleeding",
                    ),
                ),
                (
                    "anesthesia",
                    models.CharField(
                        blank=True,
                        default="Artinibsa 4% (articaine 4% with epinephrine 1:100,000), local infiltration, 2 to 4 cartridges",
                        max_length=200,
                        verbose_name="anaesthesia",
                    ),
                ),
                (
                    "medications",
                    models.TextField(
                        blank=True,
                        help_text="One per line.",
                        verbose_name="medicines after the surgery",
                    ),
                ),
                ("question", models.TextField(blank=True, verbose_name="our question")),
                (
                    "sent_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="date of the letter",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fit", "Fit for the surgery"),
                            ("precautions", "Fit, with precautions"),
                            ("postpone", "Postpone: control first, then check again"),
                            ("not_fit", "Not fit for the surgery"),
                        ],
                        max_length=12,
                        verbose_name="the physician's answer",
                    ),
                ),
                (
                    "answer_notes",
                    models.TextField(
                        blank=True,
                        verbose_name="precautions / what the physician wrote",
                    ),
                ),
                (
                    "answered_by",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="answered by (physician)",
                    ),
                ),
                (
                    "answered_on",
                    models.DateField(blank=True, null=True, verbose_name="answered on"),
                ),
                (
                    "answer_file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.patients.models.consult_answer_path,
                        verbose_name="photo of the answer",
                    ),
                ),
                (
                    "recheck_on",
                    models.DateField(
                        blank=True,
                        help_text="For a surgery postponed: when to see the patient's readings again.",
                        null=True,
                        verbose_name="check again on",
                    ),
                ),
                (
                    "answer_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_consults",
                        to="dentists.dentist",
                        verbose_name="dentist",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_consults",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "medical consultation",
                "verbose_name_plural": "medical consultations",
                "ordering": ["-sent_on", "-pk"],
            },
        ),
    ]
