# Generated by Django 5.2.17 on 2026-10-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0010_medicalconsult"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="preferred_days",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="days he prefers"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="preferred_times",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="times he prefers"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="travel_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="About how many minutes the patient takes to come to the clinic.",
                null=True,
                verbose_name="how far he lives (minutes)",
            ),
        ),
    ]
