# Generated by Django 5.2.17 on 2026-10-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0010_medicalconsult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdocument",
            name="kind",
            field=models.CharField(
                choices=[
                    ("id_front", "ID card - front"),
                    ("id_back", "ID card - back"),
                    ("passport", "Passport"),
                    ("consent", "Signed consent"),
                    ("xray", "X-ray / CBCT"),
                    ("old_file", "Old paper file (scanned)"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="document type",
            ),
        ),
    ]
