# Generated by Django 5.2.17 on 2026-10-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0011_visit_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="travel_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="About how long the patient takes to come to the clinic: hours and minutes.",
                null=True,
                verbose_name="how far he lives",
            ),
        ),
    ]
