# Generated by Django 5.2.17 on 2026-10-05 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_clinicsettings_one_device_per_login_and_more"),
        ("dentists", "0007_signatures"),
        ("patients", "0012_alter_patient_travel_minutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="patient",
            name="patient_one_id_per_place",
        ),
        migrations.AddField(
            model_name="patient",
            name="is_expected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="expected patient: the file is completed when he comes",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="national_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                verbose_name="national ID / passport no.",
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("national_id", ""), _negated=True),
                fields=("branch", "national_id"),
                name="patient_one_id_per_place",
            ),
        ),
    ]
