# Generated by Django 5.2.17 on 2026-10-05 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0013_remove_patient_patient_one_id_per_place_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("hba1c", "HbA1c above the limit"),
                            ("glucose", "High blood sugar"),
                            ("pressure", "High blood pressure"),
                            ("heart", "Heart disease"),
                            ("blood_thinner", "Blood thinners"),
                            ("bone_drugs", "Bisphosphonates or other bone drugs"),
                            ("other", "Other medical issue"),
                        ],
                        max_length=15,
                        verbose_name="why",
                    ),
                ),
                (
                    "reading",
                    models.CharField(max_length=120, verbose_name="the reading"),
                ),
                ("reading_on", models.DateField(verbose_name="reading of")),
                ("due_on", models.DateField(db_index=True, verbose_name="call on")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "To call"),
                            ("done", "New test done"),
                            ("stopped", "Not needed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=8,
                        verbose_name="status",
                    ),
                ),
                (
                    "calls",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="calls made"
                    ),
                ),
                (
                    "last_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("will_do", "He will do the test"),
                            ("no_answer", "No answer"),
                            ("done", "He did it: the result is written"),
                            ("refused", "He does not want to"),
                        ],
                        max_length=10,
                        verbose_name="last answer",
                    ),
                ),
                (
                    "last_call_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last call"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "last_call_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="called by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_recalls",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "call for a new test",
                "verbose_name_plural": "calls for a new test",
                "ordering": ["due_on", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "reason", "reading_on"),
                        name="one_recall_per_reading",
                    )
                ],
            },
        ),
    ]
