# Generated by Django 5.2.17 on 2026-10-02 06:21

import apps.papers.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0018_speed_indexes"),
        ("patients", "0011_old_paper_file_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.papers.models.new_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "upload",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The files sent together: one notice when all of them are read.",
                        max_length=32,
                    ),
                ),
                (
                    "suggested_reason",
                    models.CharField(blank=True, max_length=200, verbose_name="why"),
                ),
                (
                    "original",
                    models.FileField(
                        upload_to=apps.papers.models.original_path,
                        verbose_name="the scan as it was uploaded",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="file name"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("now", "Now (full price, about a minute a file)"),
                            (
                                "batch",
                                "In a batch (half price, back within a few hours)",
                            ),
                        ],
                        default="batch",
                        max_length=10,
                        verbose_name="sent",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting to be read"),
                            ("reading", "Being read"),
                            ("review", "To check"),
                            ("approved", "Saved in the patient's file"),
                            ("set_aside", "Set aside (typed by hand)"),
                            ("failed", "Could not be read"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "page_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="pages"),
                ),
                (
                    "cover_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="file number on the cover sheet",
                    ),
                ),
                (
                    "error",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="problem"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_files",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="patients.patientdocument",
                        verbose_name="the file in the patient's documents",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Known when the file is sent from the patient's page, else chosen when it is approved.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paper_files",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "suggested",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="patients.patient",
                        verbose_name="seems to be",
                    ),
                ),
            ],
            options={
                "verbose_name": "old paper file",
                "verbose_name_plural": "old paper files",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PaperPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="page")),
                (
                    "image",
                    models.FileField(
                        upload_to=apps.papers.models.page_path, verbose_name="picture"
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cover", "Cover sheet (file number)"),
                            ("id_front", "ID card - front"),
                            ("id_back", "ID card - back"),
                            ("registration", "Registration (patient's data)"),
                            ("history", "Medical and dental history"),
                            ("examination", "Examination"),
                            ("tooth_chart", "Dental chart (drawing of the teeth)"),
                            ("plan", "Treatment plan"),
                            ("surgery", "Surgery chart"),
                            ("treatment_log", "Treatment log (visits)"),
                            ("prescription", "Prescription"),
                            ("lab", "Lab paper"),
                            ("consent", "Signed consent"),
                            ("receipt", "Receipt or payments"),
                            ("xray", "X-ray, CBCT or photo"),
                            ("other", "Other"),
                            ("blank", "Blank page"),
                        ],
                        max_length=20,
                        verbose_name="what the page is",
                    ),
                ),
                (
                    "turned",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="turned (degrees, clockwise)"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=300, verbose_name="notes"),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="papers.paperfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
                "ordering": ["file", "number"],
            },
        ),
        migrations.CreateModel(
            name="PaperField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("value", models.TextField(blank=True, verbose_name="value")),
                (
                    "written",
                    models.TextField(
                        blank=True, verbose_name="as written on the paper"
                    ),
                ),
                (
                    "other",
                    models.TextField(blank=True, verbose_name="the second reading"),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("sure", "Sure"),
                            ("check", "Please check"),
                            ("unclear", "Cannot be read"),
                        ],
                        default="sure",
                        max_length=10,
                        verbose_name="certainty",
                    ),
                ),
                ("problems", models.JSONField(blank=True, default=list)),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Claude's note"
                    ),
                ),
                (
                    "box",
                    models.JSONField(
                        blank=True,
                        help_text="[left, top, right, bottom] on the upright page picture.",
                        null=True,
                    ),
                ),
                (
                    "checked",
                    models.BooleanField(
                        default=False, verbose_name="checked by a person"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="papers.paperfile",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="papers.paperpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "value read",
                "verbose_name_plural": "values read",
                "ordering": ["file", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PaperReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(default=1, verbose_name="reading"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("sending", "Being sent"),
                            ("sent", "Sent"),
                            ("done", "Read"),
                            ("failed", "Not read"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("batched", models.BooleanField(default=False)),
                (
                    "model",
                    models.CharField(blank=True, max_length=60, verbose_name="model"),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("cache_write_tokens", models.PositiveIntegerField(default=0)),
                (
                    "error",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="problem"
                    ),
                ),
                ("tries", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="papers.paperpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "reading",
                "verbose_name_plural": "readings",
                "ordering": ["page", "number"],
            },
        ),
        migrations.CreateModel(
            name="PaperSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="The pages leave the clinic's server and go to Anthropic (the company that makes Claude) over the internet to be read. Anthropic does not use them to train its models. Switch on only after the patients' consent and your lawyer's advice.",
                        verbose_name="send the scanned pages to Claude to read",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("claude-opus-5-5", "Claude Opus 5.5 (the most accurate)"),
                            ("claude-sonnet-5-5", "Claude Sonnet 5.5 (half the price)"),
                        ],
                        default="claude-opus-5-5",
                        max_length=40,
                        verbose_name="model",
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        choices=[
                            ("low", "Low (the cheapest)"),
                            ("medium", "Medium (usual)"),
                            ("high", "High (hard handwriting; costs more)"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="how hard it thinks",
                    ),
                ),
                (
                    "two_readings",
                    models.BooleanField(
                        default=True,
                        help_text="Where the two readings differ, the field is marked for checking. It catches more mistakes and costs twice as much.",
                        verbose_name="read each page twice and compare",
                    ),
                ),
                (
                    "default_mode",
                    models.CharField(
                        choices=[
                            ("now", "Now (full price, about a minute a file)"),
                            (
                                "batch",
                                "In a batch (half price, back within a few hours)",
                            ),
                        ],
                        default="batch",
                        max_length=10,
                        verbose_name="usual way of sending",
                    ),
                ),
                (
                    "monthly_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        help_text="Nothing more is sent this month when the month's cost reaches it. 0 = no limit.",
                        max_digits=8,
                        verbose_name="monthly limit (US dollars)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper files settings",
                "verbose_name_plural": "paper files settings",
            },
        ),
        migrations.AddIndex(
            model_name="paperfile",
            index=models.Index(fields=["branch", "status"], name="paper_place_status"),
        ),
        migrations.AddConstraint(
            model_name="paperpage",
            constraint=models.UniqueConstraint(
                fields=("file", "number"), name="paper_page_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="paperfield",
            constraint=models.UniqueConstraint(
                fields=("file", "name"), name="paper_field_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="paperreading",
            constraint=models.UniqueConstraint(
                fields=("page", "number"), name="paper_reading_once"
            ),
        ),
    ]
