# Generated by Django 5.2.17 on 2026-10-02 11:56

import apps.papers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_speed_indexes"),
        ("papers", "0001_initial"),
        ("patients", "0011_old_paper_file_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # The reading moved to the separate Paper Reader program: the tables of the reading are dropped.
    operations = [
        migrations.DeleteModel(
            name="PaperField",
        ),
        migrations.DeleteModel(
            name="PaperReading",
        ),
        migrations.DeleteModel(
            name="PaperPage",
        ),
        migrations.DeleteModel(
            name="PaperFile",
        ),
        migrations.DeleteModel(
            name="PaperSettings",
        ),
        migrations.CreateModel(
            name="PaperImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="file name")),
                (
                    "package",
                    models.FileField(
                        blank=True,
                        help_text="Kept until it is imported; the documents then live in the patients' files.",
                        upload_to=apps.papers.models.package_path,
                        verbose_name="package",
                    ),
                ),
                ("manifest", models.JSONField(default=dict, verbose_name="contents")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("checked", "Looked at, not imported yet"),
                            ("done", "Imported"),
                        ],
                        default="checked",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="imported at"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_imports",
                        to="core.branch",
                        verbose_name="place",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="imported by",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper files package",
                "verbose_name_plural": "paper files packages",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ImportedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=32)),
                ("name", models.CharField(max_length=255, verbose_name="file name")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "Saved into the patient's file"),
                            ("failed", "Not imported"),
                            ("skipped", "Already imported before"),
                        ],
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "new_patient",
                    models.BooleanField(default=False, verbose_name="new file"),
                ),
                ("message", models.TextField(blank=True, verbose_name="what happened")),
                ("at", models.DateTimeField(auto_now_add=True, verbose_name="at")),
                (
                    "change",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.changerequest",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paper_imports",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "paper_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="papers.paperimport",
                    ),
                ),
            ],
            options={
                "verbose_name": "imported paper file",
                "verbose_name_plural": "imported paper files",
                "ordering": ["paper_import", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="importedfile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "imported")),
                fields=("token",),
                name="paper_file_imported_once",
            ),
        ),
    ]
