# Generated by Django 5.2.17 on 2026-09-25 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academy", "0002_candidate_birth_date_candidate_certificate_name_and_more"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dentist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "full_name",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="full name"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("candidate", "Course candidate"),
                            ("training", "Training dentist"),
                            ("fulltime", "Full-time dentist"),
                            ("supervisor", "Supervisor"),
                            ("specialist", "Specialist"),
                            ("freelancer", "Freelance dentist"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="mobile"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick when they leave, so they no longer appear in the lists.",
                        verbose_name="working now",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dentists",
                        to="core.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        blank=True,
                        help_text="For course candidates: links the dentist to their batch, payments and implant count.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dentist",
                        to="academy.candidate",
                        verbose_name="academy candidate file",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dentist",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="system login",
                    ),
                ),
            ],
            options={
                "verbose_name": "dentist",
                "verbose_name_plural": "dentists",
                "ordering": ["kind", "full_name"],
            },
        ),
    ]
