# Generated by Django 5.2.17 on 2026-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0002_move_people_to_dentists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dentist",
            name="kind",
            field=models.CharField(
                choices=[
                    ("candidate", "Course candidate"),
                    ("training", "Training dentist"),
                    ("fulltime", "CIA dentist (full / part time)"),
                    ("supervisor", "Supervisor"),
                    ("specialist", "Specialist"),
                    ("freelancer", "Freelance dentist"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
