# Generated by Django 5.2.17 on 2026-09-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0003_cia_dentist_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="name_ar",
            field=models.CharField(
                blank=True,
                help_text="e.g. د. منى رفعت — used on the Arabic screens and in the WhatsApp messages to patients.",
                max_length=150,
                verbose_name="name in Arabic",
            ),
        ),
    ]
