# Generated by Django 5.2.17 on 2026-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_places"),
        ("dentists", "0004_dentist_arabic_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="places",
            field=models.ManyToManyField(
                blank=True,
                help_text="The places this dentist works in, e.g. CIA and CIC. They are offered on the bookings and the room schedule of these places.",
                related_name="place_dentists",
                to="core.branch",
                verbose_name="works at",
            ),
        ),
    ]
