# Generated by Django 5.2.17 on 2026-09-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0005_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="specialty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "General dentist"),
                    ("prosthodontist", "Prosthodontist"),
                    ("endodontist", "Endodontist"),
                    ("oral_surgeon", "Oral surgeon"),
                    ("tmj", "TMJ specialist (oral surgeon)"),
                    ("orthodontist", "Orthodontist"),
                    ("periodontist", "Periodontist"),
                    ("pedodontist", "Paediatric dentist"),
                    ("implantologist", "Implantologist"),
                    ("cosmetic", "Cosmetic dentist"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="specialty",
            ),
        ),
        migrations.AddField(
            model_name="dentist",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="e.g. Consultant of prosthodontics — printed under the name on treatment plans and referrals.",
                max_length=150,
                verbose_name="title on printed papers",
            ),
        ),
    ]
