# Generated by Django 5.2.17 on 2026-10-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0006_specialty_and_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="signature",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="For a doctor without a login: drawn on his page, printed on his prescriptions and receipts.",
                verbose_name="signature",
            ),
        ),
    ]
