# Generated by Django 5.2.17 on 2026-10-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentists", "0007_signatures"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="show_in_lists",
            field=models.BooleanField(
                default=True,
                help_text="Untick for someone who comes rarely: his work stays, he is not offered on the forms. Candidates leave the lists by themselves when their course ends.",
                verbose_name="in the drop lists",
            ),
        ),
        migrations.AddField(
            model_name="dentist",
            name="work_time",
            field=models.CharField(
                blank=True,
                choices=[("full", "Full time"), ("part", "Part time")],
                max_length=4,
                verbose_name="full or part time",
            ),
        ),
        migrations.AlterField(
            model_name="dentist",
            name="kind",
            field=models.CharField(
                choices=[
                    ("candidate", "Course candidate"),
                    ("training", "Training dentist"),
                    ("fulltime", "CIA junior dentist (full / part time)"),
                    ("supervisor", "Supervisor"),
                    ("specialist", "Specialist"),
                    ("freelancer", "Freelance dentist"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
