# Generated by Django 5.2.17 on 2026-09-25 10:01

import apps.charting.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0003_remove_patient_assigned_intern"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "exam_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="date of examination",
                    ),
                ),
                (
                    "referral",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="referral"
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(blank=True, verbose_name="chief complaint"),
                ),
                (
                    "teeth_carious",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="carious"
                    ),
                ),
                (
                    "teeth_filled",
                    models.CharField(blank=True, max_length=120, verbose_name="filled"),
                ),
                (
                    "teeth_missing",
                    models.CharField(blank=True, max_length=120, verbose_name="missed"),
                ),
                (
                    "teeth_not_sure",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="not sure"
                    ),
                ),
                (
                    "teeth_mobility",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="mobility"
                    ),
                ),
                (
                    "teeth_hopeless",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="hopeless teeth"
                    ),
                ),
                (
                    "teeth_implant_placed",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="implant placed (before coming to us)",
                    ),
                ),
                (
                    "teeth_implant_failed",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="implant failed (before coming to us)",
                    ),
                ),
                (
                    "inter_arch_space_right",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="inter-arch space - right",
                    ),
                ),
                (
                    "inter_arch_space_left",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="inter-arch space - left",
                    ),
                ),
                (
                    "operator_notices",
                    models.TextField(
                        blank=True, verbose_name="operator important notices"
                    ),
                ),
                (
                    "cbct_requested",
                    models.BooleanField(default=False, verbose_name="CBCT requested"),
                ),
                (
                    "cbct_done",
                    models.BooleanField(default=False, verbose_name="CBCT done"),
                ),
                (
                    "new_cbct_requested",
                    models.BooleanField(
                        default=False, verbose_name="new CBCT requested"
                    ),
                ),
                (
                    "general_health",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="general health"
                    ),
                ),
                (
                    "pregnant",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        verbose_name="pregnant?",
                    ),
                ),
                (
                    "lactating",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        verbose_name="lactating?",
                    ),
                ),
                (
                    "under_treatment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="being treated for anything now?",
                    ),
                ),
                (
                    "recent_surgery",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="recent surgery?"
                    ),
                ),
                (
                    "medical_comment",
                    models.TextField(blank=True, verbose_name="comment"),
                ),
                (
                    "other_condition",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="other disease"
                    ),
                ),
                (
                    "conditions_comment",
                    models.TextField(blank=True, verbose_name="comments on diseases"),
                ),
                (
                    "bp_last_systolic",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="last BP reading - systolic"
                    ),
                ),
                (
                    "bp_last_diastolic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="last BP reading - diastolic",
                    ),
                ),
                (
                    "bp_last_when",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="BP - when?"
                    ),
                ),
                (
                    "bp_drug",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="BP drug"
                    ),
                ),
                (
                    "bp_clinic_systolic",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="BP in clinic - systolic"
                    ),
                ),
                (
                    "bp_clinic_diastolic",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="BP in clinic - diastolic"
                    ),
                ),
                (
                    "glucose_level",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="glucose level"
                    ),
                ),
                (
                    "glucose_last",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="last glucose reading (mg/dl)",
                    ),
                ),
                (
                    "glucose_last_when",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="glucose - when?"
                    ),
                ),
                (
                    "glucose_random_clinic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="random glucose in clinic (mg/dl)",
                    ),
                ),
                (
                    "hba1c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="HbA1c (%)",
                    ),
                ),
                (
                    "hba1c_date",
                    models.DateField(blank=True, null=True, verbose_name="HbA1c date"),
                ),
                (
                    "allergy_penicillin",
                    models.BooleanField(
                        default=False, verbose_name="allergic to penicillin"
                    ),
                ),
                (
                    "allergy_sulfa",
                    models.BooleanField(
                        default=False, verbose_name="allergic to sulfa"
                    ),
                ),
                (
                    "allergy_other",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="other allergy"
                    ),
                ),
                (
                    "bleeding_or_aspirin",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="prolonged bleeding or taking aspirin?",
                    ),
                ),
                (
                    "digestion_problem",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="chronic problem with digestion?",
                    ),
                ),
                (
                    "illegal_drugs",
                    models.BooleanField(default=False, verbose_name="illegal drugs"),
                ),
                (
                    "illegal_drugs_notes",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="illegal drugs - details",
                    ),
                ),
                (
                    "operator_comments",
                    models.TextField(blank=True, verbose_name="operator comments"),
                ),
                (
                    "drugs_taken",
                    models.TextField(
                        blank=True,
                        help_text="One drug per line.",
                        verbose_name="drugs taken by patient",
                    ),
                ),
                (
                    "sensitive_hot_cold",
                    models.BooleanField(
                        default=False, verbose_name="sensitive to hot or cold"
                    ),
                ),
                (
                    "sensitive_sweets",
                    models.BooleanField(
                        default=False, verbose_name="sensitive to sweets"
                    ),
                ),
                (
                    "sensitive_biting",
                    models.BooleanField(
                        default=False, verbose_name="sensitive to biting or chewing"
                    ),
                ),
                (
                    "bruxism",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="clench or grind teeth (awake / sleep)?",
                    ),
                ),
                (
                    "smoker",
                    models.BooleanField(default=False, verbose_name="smokes tobacco"),
                ),
                (
                    "cigarettes_per_day",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="cigarettes per day"
                    ),
                ),
                (
                    "mouth_injury",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="serious injury to the mouth?",
                    ),
                ),
                (
                    "satisfied_appearance",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="satisfied with teeth appearance?",
                    ),
                ),
                (
                    "cooperation_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                        verbose_name="patient cooperative (0-10)",
                    ),
                ),
                (
                    "implant_willingness_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                        verbose_name="willing for implant treatment (0-10)",
                    ),
                ),
            ],
            options={
                "verbose_name": "examination & history",
                "verbose_name_plural": "examinations & histories",
                "ordering": ["-exam_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PhotoType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="name (English)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("diagnostic", "1st visit (diagnostic)"),
                            ("surgery", "Surgery: simple, moderate, guided"),
                            ("sinus_gbr", "Sinus lifting and GBR"),
                            ("follow_up", "Follow-up after surgery"),
                            ("soft_tissue", "Soft tissue surgery"),
                            ("second_stage", "2nd stage surgery"),
                            ("impression", "Impression"),
                            ("delivery", "Try-in & delivery"),
                        ],
                        max_length=20,
                        verbose_name="stage",
                    ),
                ),
                (
                    "optional",
                    models.BooleanField(default=False, verbose_name="optional"),
                ),
            ],
            options={
                "verbose_name": "photo checklist item",
                "verbose_name_plural": "photo checklist",
                "ordering": ["stage", "sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 - Urgent / disease control"),
                            (2, "2 - Preparation (extractions, perio, restorations)"),
                            (3, "3 - Surgical (implants, grafts)"),
                            (4, "4 - Prosthetic (impression, delivery)"),
                            (5, "5 - Follow-up / maintenance"),
                        ],
                        default=2,
                        verbose_name="phase",
                    ),
                ),
                (
                    "teeth",
                    models.CharField(blank=True, max_length=100, verbose_name="teeth"),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="details"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "done_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="done at"),
                ),
            ],
            options={
                "verbose_name": "plan item",
                "verbose_name_plural": "plan items",
                "ordering": ["phase", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ToothChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tooth",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (18, "18"),
                            (17, "17"),
                            (16, "16"),
                            (15, "15"),
                            (14, "14"),
                            (13, "13"),
                            (12, "12"),
                            (11, "11"),
                            (21, "21"),
                            (22, "22"),
                            (23, "23"),
                            (24, "24"),
                            (25, "25"),
                            (26, "26"),
                            (27, "27"),
                            (28, "28"),
                            (48, "48"),
                            (47, "47"),
                            (46, "46"),
                            (45, "45"),
                            (44, "44"),
                            (43, "43"),
                            (42, "42"),
                            (41, "41"),
                            (31, "31"),
                            (32, "32"),
                            (33, "33"),
                            (34, "34"),
                            (35, "35"),
                            (36, "36"),
                            (37, "37"),
                            (38, "38"),
                        ],
                        verbose_name="tooth",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="time"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("exam", "Examination"),
                            ("treatment", "Treatment"),
                            ("surgery", "Surgery"),
                            ("manual", "Edited on the chart"),
                        ],
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                ("summary", models.CharField(max_length=255, verbose_name="change")),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "chart change",
                "verbose_name_plural": "chart history",
                "ordering": ["-changed_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ToothState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tooth",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (18, "18"),
                            (17, "17"),
                            (16, "16"),
                            (15, "15"),
                            (14, "14"),
                            (13, "13"),
                            (12, "12"),
                            (11, "11"),
                            (21, "21"),
                            (22, "22"),
                            (23, "23"),
                            (24, "24"),
                            (25, "25"),
                            (26, "26"),
                            (27, "27"),
                            (28, "28"),
                            (48, "48"),
                            (47, "47"),
                            (46, "46"),
                            (45, "45"),
                            (44, "44"),
                            (43, "43"),
                            (42, "42"),
                            (41, "41"),
                            (31, "31"),
                            (32, "32"),
                            (33, "33"),
                            (34, "34"),
                            (35, "35"),
                            (36, "36"),
                            (37, "37"),
                            (38, "38"),
                        ],
                        verbose_name="tooth",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Natural tooth"),
                            ("missing", "Missing"),
                            ("implant", "Implant"),
                            ("root_remnant", "Root remnant"),
                            ("impacted", "Impacted"),
                            ("pontic", "Bridge pontic"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("caries", models.BooleanField(default=False, verbose_name="caries")),
                (
                    "caries_surfaces",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="caries surfaces"
                    ),
                ),
                ("filled", models.BooleanField(default=False, verbose_name="filled")),
                (
                    "filling_surfaces",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="filled surfaces"
                    ),
                ),
                (
                    "filling_material",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="filling material"
                    ),
                ),
                (
                    "rct",
                    models.BooleanField(
                        default=False, verbose_name="root canal treated"
                    ),
                ),
                ("crown", models.BooleanField(default=False, verbose_name="crown")),
                (
                    "crown_material",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="crown material"
                    ),
                ),
                (
                    "hopeless",
                    models.BooleanField(default=False, verbose_name="hopeless"),
                ),
                (
                    "fractured",
                    models.BooleanField(default=False, verbose_name="fractured"),
                ),
                (
                    "not_sure",
                    models.BooleanField(default=False, verbose_name="not sure"),
                ),
                (
                    "mobility",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "0"), (1, "I"), (2, "II"), (3, "III")],
                        default=0,
                        verbose_name="mobility grade",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "tooth condition",
                "verbose_name_plural": "dental chart",
                "ordering": ["patient", "tooth"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "title",
                    models.CharField(
                        default="Treatment plan",
                        max_length=150,
                        verbose_name="plan title",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved by supervisor"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="proposed",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "treatment plan",
                "verbose_name_plural": "treatment plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("diagnostic", "1st visit (diagnostic)"),
                            ("surgery", "Surgery: simple, moderate, guided"),
                            ("sinus_gbr", "Sinus lifting and GBR"),
                            ("follow_up", "Follow-up after surgery"),
                            ("soft_tissue", "Soft tissue surgery"),
                            ("second_stage", "2nd stage surgery"),
                            ("impression", "Impression"),
                            ("delivery", "Try-in & delivery"),
                        ],
                        max_length=20,
                        verbose_name="stage",
                    ),
                ),
                (
                    "teeth",
                    models.CharField(blank=True, max_length=100, verbose_name="teeth"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.charting.models.photo_path,
                        verbose_name="photo / video",
                    ),
                ),
                (
                    "taken_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_photos",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "clinical photo",
                "verbose_name_plural": "clinical photos",
                "ordering": ["stage", "photo_type__sort_order", "-taken_on"],
            },
        ),
    ]
