# Generated by Django 5.2.17 on 2026-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charting", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentplan",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("simple", "Simple"),
                    ("moderate", "Moderate"),
                    ("advanced", "Advanced (sinus / GBR / block)"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="case difficulty",
            ),
        ),
    ]
