# Generated by Django 5.2.17 on 2026-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charting", "0003_treatmentplan_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="history_only",
            field=models.BooleanField(
                default=False,
                help_text="Only the medical and dental history, asked at the reception; the dentist completes it.",
                verbose_name="history taken by the reception",
            ),
        ),
    ]
