# Generated by Django 5.2.17 on 2026-09-25 22:36

import apps.charting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charting", "0004_history_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalphoto",
            name="file",
            field=models.FileField(
                max_length=400,
                upload_to=apps.charting.models.photo_path,
                verbose_name="photo / video",
            ),
        ),
    ]
