# Generated by Django 5.2.17 on 2026-09-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charting", "0005_readable_photo_folders"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="dental_taken",
            field=models.BooleanField(
                default=True, verbose_name="dental history taken"
            ),
        ),
        migrations.AddField(
            model_name="examination",
            name="medical_taken",
            field=models.BooleanField(
                default=True, verbose_name="medical history taken"
            ),
        ),
    ]
