# Generated by Django 5.2.17 on 2026-09-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charting", "0006_file_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="toothchange",
            name="stage_from",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="toothchange",
            name="stage_to",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="toothchange",
            name="structured",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
