# Generated by Django 5.2.17 on 2026-09-28 06:58

import apps.charting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charting", "0007_history_in_each_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalphoto",
            name="original",
            field=models.FileField(
                blank=True,
                help_text="The photo as it was taken, kept when it is cropped or turned.",
                max_length=400,
                upload_to=apps.charting.models.photo_path,
                verbose_name="original photo",
            ),
        ),
    ]
