# Generated by Django 5.2.17 on 2026-09-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charting", "0008_photo_original"),
        ("dentists", "0006_specialty_and_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="planitem",
            name="dentist",
            field=models.ForeignKey(
                blank=True,
                help_text="Who does this part, e.g. the endodontist for the root canals.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dentists.dentist",
                verbose_name="by the doctor",
            ),
        ),
        migrations.AddField(
            model_name="planitem",
            name="fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="expected fee",
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="alternatives",
            field=models.TextField(
                blank=True,
                help_text="Printed on the plan, e.g. a removable denture instead of implants.",
                verbose_name="other options explained",
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="comprehensive",
            field=models.BooleanField(
                default=False,
                help_text="The printed plan then shows the treatment team: each doctor with his part of the work.",
                verbose_name="comprehensive case (several doctors)",
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="diagnosis",
            field=models.TextField(
                blank=True, verbose_name="diagnosis, in words for the patient"
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="duration",
            field=models.CharField(
                blank=True,
                help_text="e.g. 4 to 6 months",
                max_length=100,
                verbose_name="expected duration",
            ),
        ),
    ]
