# Generated by Django 5.2.17 on 2026-09-30 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charting", "0009_printed_plan"),
        ("clinical", "0013_step_kinds"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalphoto",
            name="shot",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="photo / X-ray of the step"
            ),
        ),
        migrations.AddField(
            model_name="clinicalphoto",
            name="treatment_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="clinical.treatmentstep",
                verbose_name="treatment step",
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="cbct_planned",
            field=models.BooleanField(
                default=False, verbose_name="planned on the CBCT"
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="chart_checked",
            field=models.BooleanField(
                default=False, verbose_name="dental chart checked again"
            ),
        ),
        migrations.AlterField(
            model_name="clinicalphoto",
            name="stage",
            field=models.CharField(
                choices=[
                    ("diagnostic", "1st visit (diagnostic)"),
                    ("surgery", "Surgery: simple, moderate, guided"),
                    ("sinus_gbr", "Sinus lifting and GBR"),
                    ("follow_up", "Follow-up after surgery"),
                    ("soft_tissue", "Soft tissue surgery"),
                    ("second_stage", "2nd stage surgery"),
                    ("impression", "Impression"),
                    ("delivery", "Try-in & delivery"),
                    ("treatment", "Treatment steps: photos and X-rays"),
                ],
                max_length=20,
                verbose_name="stage",
            ),
        ),
        migrations.AlterField(
            model_name="phototype",
            name="stage",
            field=models.CharField(
                choices=[
                    ("diagnostic", "1st visit (diagnostic)"),
                    ("surgery", "Surgery: simple, moderate, guided"),
                    ("sinus_gbr", "Sinus lifting and GBR"),
                    ("follow_up", "Follow-up after surgery"),
                    ("soft_tissue", "Soft tissue surgery"),
                    ("second_stage", "2nd stage surgery"),
                    ("impression", "Impression"),
                    ("delivery", "Try-in & delivery"),
                    ("treatment", "Treatment steps: photos and X-rays"),
                ],
                max_length=20,
                verbose_name="stage",
            ),
        ),
    ]
