# Generated by Django 5.2.17 on 2026-10-01 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charting", "0010_step_kinds"),
        ("clinical", "0013_step_kinds"),
        ("dentists", "0006_specialty_and_title"),
        ("patients", "0010_medicalconsult"),
        ("surgery", "0006_implant_sizes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="clinicalphoto",
            index=models.Index(fields=["patient", "stage"], name="photo_patient_stage"),
        ),
        migrations.AddIndex(
            model_name="examination",
            index=models.Index(
                fields=["patient", "exam_date"], name="exam_patient_date"
            ),
        ),
    ]
